### PR TITLE
8288719: [arm32] SafeFetch32 thumb interleaving causes random crashes

### PR DESCRIPTION
**Pull request by snazarkin**
Hi!

This is follow up for #1557.  The backport is not clean since [JDK-8285675](https://bugs.openjdk.org/browse/JDK-8285675) was skipped intentionally. 

Tested with gtest:all on RPi3

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8288719](https://bugs.openjdk.org/browse/JDK-8288719): [arm32] SafeFetch32 thumb interleaving causes random crashes (**Bug** - P4)
 * [JDK-8284997](https://bugs.openjdk.org/browse/JDK-8284997): arm32 build crashes since JDK-8283326 (**Bug** - P3)
 * [JDK-8285675](https://bugs.openjdk.org/browse/JDK-8285675): Temporary fix for arm32 SafeFetch (**Bug** - P4)

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to [404b6992](https://git.openjdk.org/jdk17u-dev/pull/1577/files/404b6992cd6593496ab32ff24ffe3b6958eb7381)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1577/head:pull/1577` \
`$ git checkout pull/1577`

Update a local copy of the PR: \
`$ git checkout pull/1577` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1577/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1577`

View PR using the GUI difftool: \
`$ git pr show -t 1577`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1577.diff">https://git.openjdk.org/jdk17u-dev/pull/1577.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1577#issuecomment-1634074320)

### CODE REVIEW

**Comment by tstuefe** [comment]
> Hi!
> 
> This is follow up for #1557. The backport is not clean since [JDK-8285675](https://jira.azulsystems.com/browse/JDK-8285675) was skipped intentionally.
> 
> Tested with gtest:all on RPi3
> ### Progress
> 
>     * [ ]  Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
> 
>     * [x]  Change must not contain extraneous whitespace
> 
>     * [x]  Commit message must refer to an issue
> 
> 
> ### Integration blocker
> 
>  warning Dependency #1557 must be integrated first
> ### Issues
> 
>     * [JDK-8288719](https://bugs.openjdk.org/browse/JDK-8288719): [arm32] SafeFetch32 thumb interleaving causes random crashes (**Bug** - P4)
> 
>     * [JDK-8284997](https://bugs.openjdk.org/browse/JDK-8284997): arm32 build crashes since JDK-8283326 (**Bug** - P3)
> 
> 
> ### Reviewing
> Using `git`
> Using Skara CLI tools
> Using diff file
> ### Webrev
> 
> [Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1577#issuecomment-1634074320)

Please use links to JBS, not to Azul-internal bug trackers (also I'm too lazy to lookup 8285675 manually :).

**Comment by snazarkin** [comment]
Oops! Updated the link to JBS

**Review by tstuefe — APPROVED** [review]
Okay. 

Note that the test needs to be executed on a machine where gcc uses mthumb by default, IIRC.

OTOH the patch is so basic that this is fine even without testing.

**Comment by GoeLin** [comment]
Can you please do /  isuue add JDK-8285675  as this subsumes that change.
And mention so in a fix request comment on 8285675?

**Comment by snazarkin** [comment]
> And mention so in a fix request comment on 8285675?
Do you mean [8288719](https://bugs.openjdk.org/browse/JDK-8288719)?

**Comment by snazarkin** [comment]
Got the push approval.

/integrate

**Pull request closed without merging**
