### PR TITLE
6782021: It is not possible to read local computer certificates with the SunMSCAPI provider

### PR DESCRIPTION
**Pull request by karianna**
Backport of 5e5500cbd79b40a32c20547ea0cdb81ef6904a3d

On Windows you can now access the local machine keystores using the strings "Windows-MY-LOCALMACHINE" and "Windows-ROOT-LOCALMACHINE"; note the application requires admin privileges.

"Windows-MY" and "Windows-ROOT" remain unchanged, however given these original keystore strings mapped to the current user, I added "Windows-MY-CURRENTUSER" and "Windows-ROOT-CURRENTUSER" so that a developer can explicitly specify the current user location. These two new strings simply map to the original two strings, i.e. no duplication of code paths etc

keystore functionality and API remains unchanged, the local machine keystore types require the manual tests to run in admin mode

Tested on windows, passes tier1 (via GH Actions) and manual tests provided in the patch

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires a CSR request to be approved

### Issues
 * [JDK-6782021](https://bugs.openjdk.org/browse/JDK-6782021): It is not possible to read local computer certificates with the SunMSCAPI provider
 * [JDK-8284850](https://bugs.openjdk.org/browse/JDK-8284850): It is not possible to read local computer certificates with the SunMSCAPI provider (**CSR**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/630/head:pull/630` \
`$ git checkout pull/630`

Update a local copy of the PR: \
`$ git checkout pull/630` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/630/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 630`

View PR using the GUI difftool: \
`$ git pr show -t 630`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/630.diff">https://git.openjdk.org/jdk17u-dev/pull/630.diff</a>

</details>

### CODE REVIEW

**Comment by RealCLanger** [comment]
I've approved the backport and can help to sponsor it.

**Comment by macarte** [comment]
Thanks @RealCLanger , much appreciated - @karianna is away this week, I've been helping him through the backport process, can you or I '/integrate" this?

**Comment by RealCLanger** [comment]
> Thanks @RealCLanger , much appreciated - @karianna is away this week, I've been helping him through the backport process, can you or I '/integrate" this?

Nope, we'll have to wait. The alternative is that you create another PR with the same content. But I guess it's not a problem since there will be further transports from jdk17u-dev to jdk17u until 30th of August. So it'll hit the October CPU still when you integrate it next week.

**Pull request closed without merging**
