### PR TITLE
8291650: Add delay to ClassUnloadEventTest before exiting to give time for JVM to send all events before VMDeath

### PR DESCRIPTION
**Pull request by adinn**
Backport of JDK-8291650

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8291650](https://bugs.openjdk.org/browse/JDK-8291650): Add delay to ClassUnloadEventTest before exiting to give time for JVM to send all events before VMDeath

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/824/head:pull/824` \
`$ git checkout pull/824`

Update a local copy of the PR: \
`$ git checkout pull/824` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/824/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 824`

View PR using the GUI difftool: \
`$ git pr show -t 824`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/824.diff">https://git.openjdk.org/jdk17u-dev/pull/824.diff</a>

</details>

### CODE REVIEW

**Review by adinn — COMMENTED** [review]
I'm not clear why this is in need of a review -- it is a clean backport.

**Comment by jerboaa** [comment]
@adinn It's not recognizing this as a backport. Try using PR title: `Backport a6564d495b6c2354b82cd49243d3c8793d95f2cb`

**Comment by adinn** [comment]
@jerboaa Thanks for the advice. I have updated the remaining dependent PRs in the same way and they now all have backport and clean labels. Two of them still seem to have an rfr label but they are not marked as requiring a review.

**Pull request closed without merging**
