### PR TITLE
8290023: Remove use of IgnoreUnrecognizedVMOptions in gc tests

### PR DESCRIPTION
**Pull request by sendaoYan**
Hi,
 This is backport of [JDK-8290023](https://bugs.openjdk.org/browse/JDK-8290023) and [JDK-8290269](https://bugs.openjdk.org/browse/JDK-8290269), this PR is prefixed PR of backport 
[JDK-8293503](https://github.com/openjdk/jdk17u-dev/pull/2431 )

Only change the testcase, additional testing:

- [x] jtreg tier1/tier2/tier3 etc. tests on linux x64 release build
- [x] jtreg tier1/tier2/tier3 etc. tests on linux x64 fastdebug build
- [x] jtreg tier1/tier2/tier3 etc. tests on linux aarch64 release build
- [x] jtreg tier1/tier2/tier3 etc. tests on linux aarch64 fastdebug build

It's not clean backport:
1. test/hotspot/jtreg/gc/g1/TestLargePageUseForAuxMemory.java has PR `8210708` before `8290023` jdk20
2. There is no test/hotspot/jtreg/gc/g1/TestVerificationInConcurrentCycle.java in jdk17u-dev
3. test/hotspot/jtreg/gc/metaspace/CompressedClassSpaceSizeInJmapHeap.java has been backported `8298073` and `8241293` after `8290023`  in jdk17u-dev
4. test/hotspot/jtreg/gc/metaspace/TestPerfCountersAndMemoryPools.java has PR `8284161` before `8290023` in jdk20

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8290269](https://bugs.openjdk.org/browse/JDK-8290269) needs maintainer approval
- [x] [JDK-8290023](https://bugs.openjdk.org/browse/JDK-8290023) needs maintainer approval

### Issues
 * [JDK-8290023](https://bugs.openjdk.org/browse/JDK-8290023): Remove use of IgnoreUnrecognizedVMOptions in gc tests (**Enhancement** - P4 - Approved)
 * [JDK-8290269](https://bugs.openjdk.org/browse/JDK-8290269): gc/shenandoah/TestVerifyJCStress.java fails due to invalid tag: required after JDK-8290023 (**Bug** - P4 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) 🔄 Re-review required (review applies to [98df7caf](https://git.openjdk.org/jdk17u-dev/pull/2438/files/98df7caf19a9a9de7edf8ad949bbafee5ec174c6))

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2438/head:pull/2438` \
`$ git checkout pull/2438`

Update a local copy of the PR: \
`$ git checkout pull/2438` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2438/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2438`

View PR using the GUI difftool: \
`$ git pr show -t 2438`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2438.diff">https://git.openjdk.org/jdk17u-dev/pull/2438.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2438#issuecomment-2081417848)

### CODE REVIEW

**Comment by sendaoYan** [comment]
/approval request Backport to remove unnecessary use of IgnoreUnrecognizedVMOptions in gc tests, test fix only, the change has been verified, no risk.

**Comment by GoeLin** [comment]
Hi Sendao, 
please only label for approval if you have a review.
I will only approve reviewed changes, but there is no way I can filter for this.
So I revisit changes labeled for approval but not reviewed every time I do approvals, badly wasting my time.
I will remove the fix-request labels next time I visit changes not reviewed. You can label again once a review is there.
Thanks.

**Comment by sendaoYan** [comment]
> Hi Sendao, please only label for approval if you have a review. I will only approve reviewed changes, but there is no way I can filter for this. So I revisit changes labeled for approval but not reviewed every time I do approvals, badly wasting my time. I will remove the fix-request labels next time I visit changes not reviewed. You can label again once a review is there. Thanks.

Sorry for that. I will cancel approval of all the PRs which have not been review yet.
Sorry.

**Review by phohensee — CHANGES_REQUESTED** [review]
Please remove copyright date updates that are not in the original commit, and use the latest copyright dates from the original commit rather than 2024.

**Comment by sendaoYan** [comment]
> Please remove copyright date updates that are not in the original commit, and use the latest copyright dates from the original commit rather than 2024.

Thanks for the review. The copyright mis-updates has been reverted.

**Review by phohensee — APPROVED** [review]
Thank you. Ltgm.

**Comment by sendaoYan** [comment]
> Thank you. Ltgm.

In [JDK-8290023](https://bugs.openjdk.org/browse/JDK-8290023), there is a typo bug, which fixed by [JDK-8290269](https://bugs.openjdk.org/browse/JDK-8290269), I think we should include backport of [JDK-8290269](https://bugs.openjdk.org/browse/JDK-8290269) in this PR, the backport commit is [4e02](https://github.com/openjdk/jdk17u-dev/pull/2438/commits/4e0213bc9bf6237fa4155d804754bba63aa7ac6f). Can you review this PR again, thanks.

**Comment by sendaoYan** [comment]
open

**Comment by sendaoYan** [comment]
Give up backport to 17u.

**Pull request closed without merging**
