### PR TITLE
8313322: RISC-V: implement MD5 intrinsic

### PR DESCRIPTION
**Pull request by Ilyagavrilin**
Please review this backport of md5 intrinsics to jdk17u-dev.

Backport is not clean because:

- There was no iterator for `class AbstractRegSet`, as an example `RegSetIterator` from aarch64 used: https://github.com/openjdk/jdk17u-dev/blob/0ddf1ebe3df119be2029b12feee93d0128e7cae0/src/hotspot/cpu/aarch64/register_aarch64.hpp#L379-L421
- Method `uint AbstractRegSet::size()` was missing
- Also for `size()` method we need `population_count()` function, so included `population_count.hpp` in `register_riscv.hpp`
- MD5 generation requires huge `codeBuffer`, with old codeBuffer sizes got error during intrinsic generation, so extended them:
```
  code_size1: 19000 -> 20000
  code_size2: 28000  -> 30000
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8313322](https://bugs.openjdk.org/browse/JDK-8313322) needs maintainer approval

### Issue
 * [JDK-8313322](https://bugs.openjdk.org/browse/JDK-8313322): RISC-V: implement MD5 intrinsic (**Enhancement** - P4 - Approved)

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1739/head:pull/1739` \
`$ git checkout pull/1739`

Update a local copy of the PR: \
`$ git checkout pull/1739` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1739/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1739`

View PR using the GUI difftool: \
`$ git pr show -t 1739`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1739.diff">https://git.openjdk.org/jdk17u-dev/pull/1739.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1739#issuecomment-1719298362)

### CODE REVIEW

**Review by RealFYang — APPROVED** [review]
Looks good to me. Any tests performed?

**Comment by RealFYang** [comment]
PS: I just realized that this fix is not there in jdk21u. I think this should be backported to jdk21u first. Then we can consider jdk17u-dev backport.

**Comment by Ilyagavrilin** [comment]
> Looks good to me. Any tests performed?

Yes, some performance results (measured on thead board):
Without intrinsic: 
```
Benchmark                    (digesterName)  (length)  (provider)   Mode  Cnt    Score   Error   Units
MessageDigests.digest                   md5        64     DEFAULT  thrpt   50  731.274 ± 1.250  ops/ms
MessageDigests.digest                   md5      1024     DEFAULT  thrpt   50  107.604 ± 0.164  ops/ms
MessageDigests.digest                   md5     16384     DEFAULT  thrpt   50    7.301 ± 0.026  ops/ms
MessageDigests.getAndDigest             md5      1024     DEFAULT  thrpt   50   96.412 ± 0.517  ops/ms
MessageDigests.getAndDigest             md5     16384     DEFAULT  thrpt   50    7.251 ± 0.039  ops/ms
```
With intrinsic:
```
Benchmark                    (digesterName)  (length)  (provider)   Mode  Cnt    Score   Error   Units
MessageDigests.digest                   md5        64     DEFAULT  thrpt   50  772.265 ± 3.972  ops/ms
MessageDigests.digest                   md5      1024     DEFAULT  thrpt   50  120.391 ± 0.363  ops/ms
MessageDigests.digest                   md5     16384     DEFAULT  thrpt   50    8.294 ± 0.012  ops/ms
MessageDigests.getAndDigest             md5      1024     DEFAULT  thrpt   50  107.167 ± 0.102  ops/ms
MessageDigests.getAndDigest             md5     16384     DEFAULT  thrpt   50    8.170 ± 0.036  ops/ms
```
Also, tier1 and hotspot:tier2 passed.

**Comment by Ilyagavrilin** [comment]
> PS: I just realized that this fix is not there in jdk21u. I think this should be backported to jdk21u first. Then we can consider jdk17u-dev backport.

Created pr to jdk21u with MD5 backport: https://github.com/openjdk/jdk21u/pull/184 . Backport to jdk21u clean.

**Comment by Ilyagavrilin** [comment]
/approval request I would like to backport this into jdk17u; Applied to jdk21u, low-risk, risc-v only change, Testing: tier1/hotspot:tier2 on risc-v board

**Pull request closed without merging**
