### PR TITLE
8302491: NoClassDefFoundError omits the original cause of an error

### PR DESCRIPTION
**Pull request by Larry-N**
The backporting of this patch enhances the workflow of JDK-8048190 by expanding the range of scenarios in which the root cause of a NoClassDefFoundError can be accurately reported. The patch carries a low risk as it only corrects the process of creating ExceptionInInitializerError for a specific scenario.
The patch does not apply cleanly to 17u, a little adjustment have been done.
Tested the patch with tier1 and tier2 tests.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8302491](https://bugs.openjdk.org/browse/JDK-8302491): NoClassDefFoundError omits the original cause of an error

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1226/head:pull/1226` \
`$ git checkout pull/1226`

Update a local copy of the PR: \
`$ git checkout pull/1226` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1226/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1226`

View PR using the GUI difftool: \
`$ git pr show -t 1226`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1226.diff">https://git.openjdk.org/jdk17u-dev/pull/1226.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1226#issuecomment-1487542841)

### CODE REVIEW

**Comment by GoeLin** [comment]
Please enable Github actions. Only tag the change if it is reveiwed.  Please follow instructions in https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix

**Review by phohensee — CHANGES_REQUESTED** [review]
The only non-clean place I can see is line 2735 in javaClasses.cpp, where you substituted nullptr for NULL. That isn't in the original commit, and adding it here would complicate a possible future NULL -> nullptr backport. Please change it back to NULL.

Also, please enable pre-submit testing on your repo.

**Review by phohensee — APPROVED** [review]
Looks good now.

If you're not an Author, once the pre-submit tests are done, I can tag the JBS issue on your behalf and sponsor the commit once the backport is approved.

**Pull request closed without merging**
