### PR TITLE
8308593: Add KEEPALIVE Extended Socket Options Support for Windows

### PR DESCRIPTION
**Pull request by tkyc**
This is an unclean backport of [JDK-8308593](https://bugs.openjdk.org/browse/JDK-8308593), which provides support for the keepalive extended socket options on Windows.

The following changes were made in these files to resolve conflicts and issues:
1. make/modules/jdk.net/Lib.gmk -- I updated this script to support building extnet for Windows.

2. jdk.net/share/classes/jdk/net/ExtendedSocketOptions.java -- I added a case to support returning an instance of WindowsSocketOptions in PlatformSocketOptions.

Tier 1 tests were ran and they're passing along with the existing keepalive tests. I also manually tested and confirmed the patch to be working on Windows.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8308593](https://bugs.openjdk.org/browse/JDK-8308593) needs maintainer approval

### Issue
 * [JDK-8308593](https://bugs.openjdk.org/browse/JDK-8308593): Add KEEPALIVE Extended Socket Options Support for Windows (**Enhancement** - P4 - Approved)

### Reviewers
 * [Daniel Jeliński](https://openjdk.org/census#djelinski) (@djelinski - no project role) ⚠️ Review applies to [7c75b9dd](https://git.openjdk.org/jdk17u-dev/pull/1751/files/7c75b9ddbffaf2670efefdb28ec29a9890afc5b7)
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1751/head:pull/1751` \
`$ git checkout pull/1751`

Update a local copy of the PR: \
`$ git checkout pull/1751` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1751/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1751`

View PR using the GUI difftool: \
`$ git pr show -t 1751`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1751.diff">https://git.openjdk.org/jdk17u-dev/pull/1751.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1751#issuecomment-1724173627)

### CODE REVIEW

**Comment by tkyc** [comment]
/approval request The reason for the backport to 17u is to have keepalive parity with the other OS platforms. The risk is low as the backported code introduces a new code path that only takes effect when keepalive extended socket options are set on a Windows platform. I manually tested the patch and Tier 1 tests were ran and they're passing. No new tests were added as there are existing tests in 17u that cover this scenario.

**Comment by tkyc** [comment]
Hello, let me know if I need to do anything else on my part to progress this PR to get a reviewer to take a look.

**Comment by GoeLin** [comment]
You need to ask someone in the community to give you a review, best someone with expertise in the area.

**Review by djelinski — APPROVED** [review]
LGTM.

**Comment by tkyc** [comment]
Thanks for the quick review.

**Review by phohensee — CHANGES_REQUESTED** [review]
You need a review before you can integrate.

In Lib.gmk, the copyright line should read

# Copyright (c) 2016, 2023, Oracle and/or its affiliates. All rights reserved.

Similarly in ExtendedSocketOptions.java, the copyright line should red

* Copyright (c) 2014, 2023 Oracle and/or its affiliates. All rights reserved.

The changes to Lib.gmk come from [JDK-8284890](https://bugs.openjdk.org/browse/JDK-8284890). It seems to me can't be backported because it involved a public API change, so adding linker options in this backport is ok. Same with the change in ExtendedSocketOptions.java to return a Windows-specific PlatformSocketOptions object, and the addition of WindowsSocketOptions.java/c.

So, aside from the above trivial copyright line changes, ltgm.

**Comment by tkyc** [comment]
Awesome, thanks for the review.

**Review by phohensee — APPROVED** [review]

**Comment by phohensee** [comment]
The GHA failure appears to be an infrastructure issue.

**Pull request closed without merging**
