### PR TITLE
8048190: NoClassDefFoundError omits original ExceptionInInitializerError

### PR DESCRIPTION
**Pull request by GoeLin**
I backport this for parity with 17.0.7-oracle.

I had to adapt the declaration of _initialization_error_table because "8270061: Change parameter order of ResourceHashtable" is not in 17.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8048190](https://bugs.openjdk.org/browse/JDK-8048190): NoClassDefFoundError omits original ExceptionInInitializerError

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [4cee8df5](https://git.openjdk.org/jdk17u-dev/pull/1195/files/4cee8df5f35976c578b7b535e2680b7f1a1b276e)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/1195/head:pull/1195` \
`$ git checkout pull/1195`

Update a local copy of the PR: \
`$ git checkout pull/1195` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/1195/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1195`

View PR using the GUI difftool: \
`$ git pr show -t 1195`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1195.diff">https://git.openjdk.org/jdk17u-dev/pull/1195.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by GoeLin** [comment]
Pre submit failure: Error: make: Failed to download resource "make_bottle_manifest"
infra problem, unrelated.

**Comment by GoeLin** [comment]
Restarted tests passed.

**Pull request closed without merging**
