### PR TITLE
8290322: Optimize Vector.rearrange over byte vectors for AVX512BW targets.

### PR DESCRIPTION
**Pull request by jatin-bhateja**
Backport of [JDK-8290322](https://bugs.openjdk.org/browse/JDK-8290322). 

Due to merge conflicts, original patch could not be auto-merged by bot,  only change w.r.t original PR is in 
predicate conditions of instruction patterns, in JDK17 vector_length and vector_element_basic_type were static functions defined in AD files which were moved into Matcher class in latest code. 

Patch enables wide vector byte level permutation for AVX512BW targets and benefits multiple generations of Intel's Xeon servers (SKX, CLX, CPX) prior to Ice lake which provides a direct HW instruction (VPERMB). JIT instruction sequence emitted in this case is specific to Vector.rearrange API, hence the scope of the patch is limited to VectorAPIs which is an incubating module currently.

Vector API jtreg test suite contains multiple tests cases for ByteVector.SPECIES_512 to extensively tests the patch.

Original patch review was done with [PR 9498](https://github.com/openjdk/jdk/pull/9498)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8290322](https://bugs.openjdk.org/browse/JDK-8290322): Optimize Vector.rearrange over byte vectors for AVX512BW targets.

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)
 * [Sandhya Viswanathan](https://openjdk.org/census#sviswanathan) (@sviswa7 - no project role)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/917/head:pull/917` \
`$ git checkout pull/917`

Update a local copy of the PR: \
`$ git checkout pull/917` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/917/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 917`

View PR using the GUI difftool: \
`$ git pr show -t 917`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/917.diff">https://git.openjdk.org/jdk17u-dev/pull/917.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
Lgtm.

**Review by sviswa7 — APPROVED** [review]

**Review by phohensee — APPROVED** [review]
Thank you, Sandhya. Waiting for maintainer approval.

**Comment by GoeLin** [comment]
Hi @jatin-bhateja,
1. The change is not clean if it requires merges.  Using the clean command is not allowed in this case. Obviously you even introduced two formatting errors when resolving (which might make follow up backports unclean).
2. you should not type integrate if you do not have a fix-yes label on the JBS bug.
Please follow the instructions in https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix for your next backport.

**Comment by jatin-bhateja** [comment]
> Hi @jatin-bhateja,
> 
> 1. The change is not clean if it requires merges.  Using the clean command is not allowed in this case. Obviously you even introduced two formatting errors when resolving (which might make follow up backports unclean).
> 2. you should not type integrate if you do not have a fix-yes label on the JBS bug.
>    Please follow the instructions in https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix for your next backport.

Hi @GoeLin , Thanks for your guidance and suggestions, I have updated the patch description to reflect the exact change from original pull request and removed the mention of 'clean backport',  will take precautions in future. Patch is regressed and approved by JDK reviewers.

**Pull request closed without merging**
