### PR TITLE
8321025: Enable Neoverse N1 optimizations for Neoverse V2

### PR DESCRIPTION
**Pull request by pengxiaolong**
### Notes

Backport 8321025: Enable Neoverse N1 optimizations for Neoverse V2  to jdk17, it is not a clean backport, the method ```model_is(0xd40) ``` is in jdk17, equivalent code in jdk17 is like ```(_model == 0xd40 || _model2 == 0xd40)```. 

### Verification
Not able to test it on CPU with Neoverse V2, I don't have server supports Neoverse V2 yet, but the code has been backported to [Amazon Corretto 17](https://github.com/corretto/corretto-17/blob/release-17.0.11.9.1/CHANGELOG.md) since January 16, 2024, overall it should be a low risk.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8321025](https://bugs.openjdk.org/browse/JDK-8321025) needs maintainer approval

### Issue
 * [JDK-8321025](https://bugs.openjdk.org/browse/JDK-8321025): Enable Neoverse N1 optimizations for Neoverse V2 (**Enhancement** - P4 - Approved)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2579/head:pull/2579` \
`$ git checkout pull/2579`

Update a local copy of the PR: \
`$ git checkout pull/2579` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2579/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2579`

View PR using the GUI difftool: \
`$ git pr show -t 2579`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2579.diff">https://git.openjdk.org/jdk17u-dev/pull/2579.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2579#issuecomment-2173603673)

### CODE REVIEW

**Comment by shipilev** [comment]
In Corretto 17, we picked up `is_model`: https://github.com/corretto/corretto-17/commit/3d11b555446102e07bcaf60d077364d499bc82a5. Seeing how this backport is already not clean, I think we should do the same here. It would also provide a bit more credence to the patch, as we propose exactly the same patch that already runs in prod.

**Comment by shipilev** [comment]
Yup, Corretto 21 did a similar thing: https://github.com/corretto/corretto-21/commit/6325710782b295bc09373df15b0305508f3ca89f

**Comment by pengxiaolong** [comment]
> Yup, Corretto 21 did a similar thing: [corretto/corretto-21@6325710](https://github.com/corretto/corretto-21/commit/6325710782b295bc09373df15b0305508f3ca89f)

Updated both PRs, thanks!

**Review by shipilev — APPROVED** [review]

**Comment by pengxiaolong** [comment]
/approval request Backport [JDK-8321025](https://bugs.openjdk.org/browse/JDK-8321025) to jdk17 for to enable Neoverse N1 optimizations for Neoverse V2, it was not a clean backport, also backported VM_Version::model_is from [openjdk/jdk@3283328](https://github.com/openjdk/jdk/commit/3283328) when resolving the conflicts. Risk should be low, it was backported Correto-jdk-17 in Jan 2024, no known issue so far.

**Comment by pengxiaolong** [comment]
Thanks for the review and approval! I'll start to integrate

**Pull request closed without merging**
