### PR TITLE
8303942: os::write should write completely

### PR DESCRIPTION
**Pull request by elifaslan1**
This is not a clean backport. There were multiple merge conflicts related to undefined parameters and existing methods. This backport is required to address a crash observed in Amazon production. Please refer to the related [PR](https://github.com/openjdk/jdk17u-dev/pull/2281), which has already been merged.

In addition to GHA Tier 1, runtime hotspot, JFR, and hotspot GC tests have been run on macOS.

```
   TEST                                              TOTAL  PASS  FAIL ERROR
   jtreg:test/hotspot/jtreg:hotspot_runtime            880   880     0     0
==============================
TEST SUCCESS

Finished building target 'test' in configuration 'macosx-x86_64-server-release'
```
Additinonally, added clean backport of [JDK-8316468] (https://github.com/openjdk/jdk/commit/7ce5bd159024e70f5a997c47ed2ce962d6e6091b)

After new commit reran runtime hotspot tests and they all passed

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8303942](https://bugs.openjdk.org/browse/JDK-8303942) needs maintainer approval
- [x] [JDK-8183227](https://bugs.openjdk.org/browse/JDK-8183227) needs maintainer approval
- [x] [JDK-8316468](https://bugs.openjdk.org/browse/JDK-8316468) needs maintainer approval

### Issues
 * [JDK-8303942](https://bugs.openjdk.org/browse/JDK-8303942): os::write should write completely (**Bug** - P4 - Approved)
 * [JDK-8316468](https://bugs.openjdk.org/browse/JDK-8316468): os::write incorrectly handles partial write (**Bug** - P2 - Approved)
 * [JDK-8183227](https://bugs.openjdk.org/browse/JDK-8183227): read/write APIs in class os shall return ssize_t (**Enhancement** - P4 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [ce92b16d](https://git.openjdk.org/jdk17u-dev/pull/2490/files/ce92b16de7f30e58d15b71b3074633c368fea0bd)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2490/head:pull/2490` \
`$ git checkout pull/2490`

Update a local copy of the PR: \
`$ git checkout pull/2490` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2490/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2490`

View PR using the GUI difftool: \
`$ git pr show -t 2490`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2490.diff">https://git.openjdk.org/jdk17u-dev/pull/2490.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2490#issuecomment-2127891887)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by elifaslan1** [comment]
/approval JDK-8303942 request Not a clean backport.There were multiple merge conflicts related to undefined parameters and existing methods. This backport is required to address a crash observed in Amazon production. Testing: hotspot,jfr  and GHA tests passed.

**Comment by shipilev** [comment]
There is a P2 regression from this fix: [JDK-8316468](https://bugs.openjdk.org/browse/JDK-8316468). It needs to go in this PR as well to avoid non-atomic breakage of 17u-dev.

**Comment by elifaslan1** [comment]
/approval JDK-8303942 request Not a clean backport.There were multiple merge conflicts related to undefined parameters and existing methods. This backport is required to address a crash observed in Amazon production. Additionally [JDK-8316468](https://bugs.openjdk.org/browse/JDK-8316468)  regression has been adressed and added as a clean backport to the PR. Testing: hotspot,jfr and GHA tests passed.

**Comment by shipilev** [comment]
You need to say `/issue add JDK-8316468` to record that this PR includes both fixes.

**Comment by elifaslan1** [comment]
/approval JDK-8316468 request clean backport to address a regression in os::write() that could cause heap dump corruption. Testing: hotspot,jfr and GHA tests passed.

**Review by phohensee — APPROVED** [review]

**Comment by shipilev** [comment]
This is a tad intrusive change, please make sure that all tests are pass. For example:

```
JTREG_KEYWORDS="\!headful & \!external-dep & \!printer" make test TEST=all
```

**Comment by elifaslan1** [comment]
I ran tests for both my branch and master , the results look the same.

**Comment by elifaslan1** [comment]
Thanks Aleksey, it is much cleaner with [this](https://github.com/openjdk/jdk/commit/4ff6720573f9b55eb397d1aac9b398228faf2ceb) commit and there was only 3 conflicted files. First I applied the commit that you referred , after that I applied the last 2 commits.

**Comment by elifaslan1** [comment]
/approval JDK-8183227 request not clean backport. Current backport is dependent on this backport to address a regression in os::write() that could cause heap dump corruption. Testing: hotspot,jfr and GHA tests passed.

**Comment by shipilev** [comment]
Thanks, I'll take a look at these three tomorrow.

**Review by shipilev — APPROVED** [review]
Looks good to me. Make sure to re-run `all` tests before integrating.

**Pull request closed without merging**
