### PR TITLE
8278834: Error "Cannot read field "sym" because "this.lvar[od]" is null" when compiling

### PR DESCRIPTION
**Pull request by Glavo**
---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8278834](https://bugs.openjdk.org/browse/JDK-8278834): Error "Cannot read field "sym" because "this.lvar[od]" is null" when compiling

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1141/head:pull/1141` \
`$ git checkout pull/1141`

Update a local copy of the PR: \
`$ git checkout pull/1141` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1141/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1141`

View PR using the GUI difftool: \
`$ git pr show -t 1141`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1141.diff">https://git.openjdk.org/jdk17u-dev/pull/1141.diff</a>

</details>

### CODE REVIEW

**Comment by phohensee** [comment]
@Glavo, please add a note describing the reason for the backport, testing, and risk.

**Comment by Glavo** [comment]
@phohensee 

javac crashed when we compiled the following code using JDK 17:

```java
import java.util.*;

public class Main {
    public static void main(String[] args) {
        Integer b = 1;
        new Main(b) {
            private final List<String> list = this.o instanceof Integer i ? new ArrayList<String>(i) : new ArrayList<String>();
        }.run();
    }

    protected final Object o;

    public Main(Object o) {
        this.o = o;
    }

    public void run() {

    }
}
```

javac output:

```
An exception has occurred in the compiler (17.0.6). Please file a bug against the Java compiler via the Java bug reporting page (https://bugreport.java.com) after checking the Bug Database (https://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
java.lang.NullPointerException: Cannot read field "sym" because "this.lvar[od]" is null
        at jdk.compiler/com.sun.tools.javac.jvm.Code.emitop1w(Code.java:956)
        at jdk.compiler/com.sun.tools.javac.jvm.Items$LocalItem.load(Items.java:401)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genArgs(Gen.java:902)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.visitNewClass(Gen.java:1967)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1852)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:877)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.visitSelect(Gen.java:2316)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2450)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:877)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.visitApply(Gen.java:1875)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1797)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:877)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.visitExec(Gen.java:1748)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1584)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genDef(Gen.java:610)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:645)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:631)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStats(Gen.java:682)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.visitBlock(Gen.java:1097)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1091)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genDef(Gen.java:610)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:645)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genMethod(Gen.java:967)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.visitMethodDef(Gen.java:930)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:921)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genDef(Gen.java:610)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genClass(Gen.java:2420)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.genCode(JavaCompiler.java:737)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1617)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1585)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
        at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
        at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
printing javac parameters to: /mnt/d/Downloads/javac.20230202_005046.args
```

This backport is to fix this problem. I think there are no known risks.

What tests should I run for javac?

**Comment by phohensee** [comment]
Thank you for the info. The langtools tier1 tests would be the right ones to use. These are run as part of pre-submit testing, which should be configured on your repo (click on "Details" on the left of Pre-submit test status". Also, did the backport fix the crash? I assume it did, but that needs to be stated. I've tagged the JBS issue on your behalf.

**Comment by Glavo** [comment]
> Thank you for the info. The langtools tier1 tests would be the right ones to use. These are run as part of pre-submit testing, which should be configured on your repo (click on "Details" on the left of Pre-submit test status". Also, did the backport fix the crash? I assume it did, but that needs to be stated. I've tagged the JBS issue on your behalf.

I ran and passed the pre-submit test.

**Comment by phohensee** [comment]
Excellent, thank you. Now we wait for maintainer approval. Once we have that, I can sponsor.

**Comment by GoeLin** [comment]
Hi Glavo,
 Please don't integrate as long as you don't have the fix-yes tag on the JBS issue!!!  I'll block this by asking for a review.
 Passing Pre-submit tests is only a minimal test precondition. You should run additional tests to test the fix and to assure there are no regressions. E.g., all langtool tests, some compile jobs that stress javac etc. 

Also, this is a 17.0.8 change. We are still working on 17.0.7. Usually, we keep these in-sync. Also, the fix is brand-new in head.   Is there a good reason you need this in 17.0.7?  I would prefer to wait for 17.0.8.  See also the project homepage for the timetables.

**Comment by GoeLin** [comment]
Fixes to test can always be backported as they don't have an effect on the deliverable.

**Review by phohensee — APPROVED** [review]
I'm not a javac expert, but this looks like a fix for a case where expected state (currentMethodSym) could be silently trashed, resulting in a later NPE. The code is tip is more complex, but retains the "restoration of state" idea in this code. Also, the patch includes a test (which passes) derived from the one attached to the original JBS issue.

**Comment by phohensee** [comment]
Re-tagged the JBS issue.

**Comment by GoeLin** [comment]
@Glavo, can you please merge head so that thye pre submit tests run?
Click on you branch at the top, then on "Sync fork".

**Review by phohensee — APPROVED** [review]
Re-review. Backport has been approved, I can sponsor as soon as I see /integrate.

**Comment by Glavo** [comment]
I ran the tier1 and tier2 tests. Tier1 all passed. Two tests in tier2 failed, but none of them seemed to be related to this PR.

**Pull request closed without merging**
