### PR TITLE
8290908: misc tests fail: assert(!thread->owns_locks()) failed: must release all locks when leaving VM

### PR DESCRIPTION
**Pull request by adinn**
Backport of follow up fix to correct JCK failure after 8256811.

The backport involved minor adjustment of the original patch to allow for interbening changes.

This backport is dependent on prior backport of JDK-8256811

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8290908](https://bugs.openjdk.org/browse/JDK-8290908): misc tests fail: assert(!thread->owns_locks()) failed: must release all locks when leaving VM

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/636/head:pull/636` \
`$ git checkout pull/636`

Update a local copy of the PR: \
`$ git checkout pull/636` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/636/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 636`

View PR using the GUI difftool: \
`$ git pr show -t 636`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/636.diff">https://git.openjdk.org/jdk17u-dev/pull/636.diff</a>

</details>

### CODE REVIEW

**Comment by jerboaa** [comment]
@adinn Please use PR title `Backport 0ae834105740f7cf73fe96be22e0f564ad29b18d` as we know the sha of the mainline patch. Please also target branch `pr/635` over `master` since that's the PR this depends on (uses the depending pull requests feature).

**Comment by adinn** [comment]
@jerboaa How do I make this patch target pr/635? n.b. I raised the PR from a branch that is derived from the one used to raise pr/635.

**Comment by jerboaa** [comment]
@adinn In the UI when you create a PR, the target branch should be `openjdk:pr/635` instead of `openjdk:master`. "See [adinn](https://github.com/adinn) wants to merge 2 commits into [openjdk:master](https://github.com/openjdk/jdk17u-dev) from [adinn:JDK-8290908](https://github.com/adinn/jdk17u-dev/tree/JDK-8290908)" above. You can re-use the branch you have, but by comparing it to `pr/635` only the changes on top would show up in the "changes" tab. It might mean you'd have to recreate the PR and close this one. Not sure if you have a widget to change the target branch (I don't, but I didn't create the PR).

**Comment by adinn** [comment]
@jerboaa I have created a new backport PR that targets pr/635. I am closing this one.

**Comment by RealCLanger** [comment]
> @jerboaa I have created a new backport PR that targets pr/635. I am closing this one.

That was not necessary. As a PR author, you can change the target branch via an edit button that you should have. But it's ok this way either. 😉

**Comment by adinn** [comment]
Right, I found the button too late -- in case anyone else is as clueless a n00b as me I'll mention: it pops up after you click on Edit on the top right of the PR title.

**Pull request closed without merging**
