### PR TITLE
8309254: Implement fast-path for ASCII-compatible CharsetEncoders on RISC-V

### PR DESCRIPTION
**Pull request by DingliZhang**
I would like to backport [JDK-8309254](https://bugs.openjdk.org/browse/JDK-8309254). 
The backport is not clean because 17u has no  [JDK-8302908](https://bugs.openjdk.org/browse/JDK-8302908), which use v0 as mask register.
The test `test/hotspot/jtreg/compiler/intrinsics/string/TestEncodeIntrinsics.java` passed and command log with "-XX:+PrintOptoAssembly" output is similar to the mainline:
```
...
240     Encode ISO array R12, R11, R13 -&gt; R10 # KILL R12, R11, R13, R28, V1-V3
...
0118    Encode ASCII array R12, R11, R13 -&gt; R10 # KILL R12, R11, R13, R25, V1-V3
...
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8309254](https://bugs.openjdk.org/browse/JDK-8309254): Implement fast-path for ASCII-compatible CharsetEncoders on RISC-V (**Enhancement** - P4)

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1567/head:pull/1567` \
`$ git checkout pull/1567`

Update a local copy of the PR: \
`$ git checkout pull/1567` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1567/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1567`

View PR using the GUI difftool: \
`$ git pr show -t 1567`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1567.diff">https://git.openjdk.org/jdk17u-dev/pull/1567.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1567#issuecomment-1630455985)

### CODE REVIEW

**Review by RealFYang — APPROVED** [review]
Looks good. (Not a JDK Update Reviewer)
I think this is on par with https://bugs.openjdk.org/browse/JDK-8274243 which has been backported into jdk17u.

**Comment by DingliZhang** [comment]
Tier1-3 with UseRVV likes look.
Could we have a Reviewer?

**Review by RealFYang — APPROVED** [review]

**Comment by DingliZhang** [comment]
@RealFYang Thanks for the review!
/integrate

**Pull request closed without merging**
