### PR TITLE
8281522: Rename ADLC classes which have the same name as hotspot variants

### PR DESCRIPTION
**Pull request by tstuefe**
I'd like to bring this into JDK17. Its a purely mechanical renaming of classes in ADLC. It does not apply cleanly, but the only conflicts were copyright headers (ADLC gets touched very rarely).

The reason I want this downported is to make future code changes easier and to simplify development. I was on the fence about this one, but since its really low risk, I think it makes sense to downport this.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8281522](https://bugs.openjdk.java.net/browse/JDK-8281522): Rename ADLC classes which have the same name as hotspot variants

### Reviewers
 * [Martin Doerr](https://openjdk.java.net/census#mdoerr) (@TheRealMDoerr - **Reviewer**) ⚠️ Review applies to e18b4943d78a675faaa03a287665cd0a86b3487d

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17u-dev pull/332/head:pull/332` \
`$ git checkout pull/332`

Update a local copy of the PR: \
`$ git checkout pull/332` \
`$ git pull https://git.openjdk.java.net/jdk17u-dev pull/332/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 332`

View PR using the GUI difftool: \
`$ git pr show -t 332`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17u-dev/pull/332.diff">https://git.openjdk.java.net/jdk17u-dev/pull/332.diff</a>

</details>

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
I think this makes sense. It's always good to be able to distinguish the ADLC stuff from the rest.

**Comment by tstuefe** [comment]
> I think this makes sense. It's always good to be able to distinguish the ADLC stuff from the rest.

Thanks Martin!

**Comment by TheRealMDoerr** [comment]
Note that this PR is still draft!

**Pull request closed without merging**
