### PR TITLE
8248001: javadoc generates invalid HTML pages whose ftp:// links are broken

### PR DESCRIPTION
**Pull request by ktakakuri**
I would like to backport
8248001: javadoc generates invalid HTML pages whose ftp:// links are broken.
This is a clean backport.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8248001](https://bugs.openjdk.org/browse/JDK-8248001): javadoc generates invalid HTML pages whose ftp:// links are broken

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1236/head:pull/1236` \
`$ git checkout pull/1236`

Update a local copy of the PR: \
`$ git checkout pull/1236` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1236/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1236`

View PR using the GUI difftool: \
`$ git pr show -t 1236`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1236.diff">https://git.openjdk.org/jdk17u-dev/pull/1236.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1236#issuecomment-1511064036)

### CODE REVIEW

**Comment by ktakakuri** [comment]
Could someone please review this backport?

**Comment by RealCLanger** [comment]
Hi,

generally it looks ok. Plese revert the copyright modifications. In backports, we don't increment to the current year but only take over the copyright modifications from the upstream patch, if there were any.

Also, can you please run GHA tests.

Thanks!

**Comment by ktakakuri** [comment]
> Hi,
> 
> generally it looks ok. Please revert the copyright modifications. In backports, we don't increment to the current year but only take over the copyright modifications from the upstream patch, if there were any.
> 
> Also, can you please run GHA tests.
> 
> Thanks!

Thank you for your review.
I reverted the copyright modifications.
Is there a problem with issuing a Fix Request?

**Comment by ktakakuri** [comment]
Thank you, I added the label.

**Comment by RealCLanger** [comment]
> Thank you, I added the label.

Great, could you merge the PR branch with current master to eliminate the GHA failures? Did you run the langtools tests (including the one that is added here)?

I will run the PR through our nightlies. In case everything is good, I'll approve the backport.

**Comment by RealCLanger** [comment]
> I will run the PR through our nightlies. In case everything is good, I'll approve the backport.

Testing looks good. I have approved the backport - this one is ready to integrate.

**Pull request closed without merging**
