### PR TITLE
8300584: Accelerate AVX-512 CRC32C for small buffers

### PR DESCRIPTION
**Pull request by yftsai**
Backport 7c2f77a42293eb79829fce99bfce82e89a5df6d7

The following tests have passed.
```
jtreg:test/hotspot/jtreg/compiler/intrinsics/zip/TestCRC32C.java
jtreg:test/jdk/java/util/zip/TestCRC32C.java
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8300584](https://bugs.openjdk.org/browse/JDK-8300584): Accelerate AVX-512 CRC32C for small buffers (**Enhancement** - P2)

### Reviewers
 * [Scott Gibbons](https://openjdk.org/census#sgibbons) (@asgibbons - no project role)
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1346/head:pull/1346` \
`$ git checkout pull/1346`

Update a local copy of the PR: \
`$ git checkout pull/1346` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1346/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1346`

View PR using the GUI difftool: \
`$ git pr show -t 1346`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1346.diff">https://git.openjdk.org/jdk17u-dev/pull/1346.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1346#issuecomment-1548346028)

### CODE REVIEW

**Review by asgibbons — APPROVED** [review]

**Review by phohensee — APPROVED** [review]
Looks clean. Perhaps the bot doesn't recognize that due to the way the backport PR was created.

**Comment by GoeLin** [comment]
Hi @yftsai, 
could you please elaborate on the risk and testing in the jdk17u fix reqeust comment?
As this  changes an essential algorithm on an essential platform this needs considerable additional testing please.

**Comment by asgibbons** [comment]
This has been running in mainline since early February with no issues found.  I believe this backport is low risk, since both large and small buffer code are already executed - there was just a change in the definition of "small" vs. "large".

**Pull request closed without merging**
