### PR TITLE
8331331: :tier1 target explanation in doc/testing.md is incorrect

### PR DESCRIPTION
**Pull request by sendaoYan**
Hi,
  This is backport of [JDK-8331331](https://bugs.openjdk.org/browse/JDK-8331331). The `doc/testing.html` can not backport cleanly because of it's a prefixed patch [JDK-8295663](https://bugs.openjdk.org/browse/JDK-8295663).

  The commit being backported was authored by SendaoYan on 3 May 2024 and was reviewed by Erik Joelsson, David Holmes and Magnus Ihse Bursie.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8331331](https://bugs.openjdk.org/browse/JDK-8331331) needs maintainer approval

### Issue
 * [JDK-8331331](https://bugs.openjdk.org/browse/JDK-8331331): :tier1 target explanation in doc/testing.md is incorrect (**Bug** - P4 - Approved)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2447/head:pull/2447` \
`$ git checkout pull/2447`

Update a local copy of the PR: \
`$ git checkout pull/2447` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2447/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2447`

View PR using the GUI difftool: \
`$ git pr show -t 2447`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2447.diff">https://git.openjdk.org/jdk17u-dev/pull/2447.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2447#issuecomment-2094723197)

### CODE REVIEW

**Comment by sendaoYan** [comment]
Only change the guide doc files, no risk.

**Comment by sendaoYan** [comment]
/approval request Backport to correct the document description, only change the guide doc files, no risk.

**Review by MBaesken — APPROVED** [review]

**Comment by sendaoYan** [comment]
Thanks for the review.

**Comment by sendaoYan** [comment]
Thanks for the approved.
/integrate

**Comment by sendaoYan** [comment]
Thanks fr the sponsor.

**Pull request closed without merging**
