### PR TITLE
8293834: Update CLDR data following tzdata 2022c update

### PR DESCRIPTION
**Pull request by gnu-andrew**
Moving this here from https://github.com/openjdk/jdk17u/pull/355 as I guess this missed review before freeze. Do we need more people actively monitoring 17u during the rampdown period?

This patch updates the CLDR data following the tzdata bump in JDK-8292579.

This will be handled in trunk by a larger update to CLDRv42.

It differs from the 19u version in that we also bring in a change from the CLDR v41 update (JDK-8265315) to use "Kyiv" rather than "Kiev" as the zone description. This change is already in 19u.

The test fails with 17.0.4 (using system tzdata 2022c) as follows:

~~~
$ grep 'AssertionError' test.1663972846/jdk/JTwork/sun/util/resources/cldr/TimeZoneNamesTest.jtr 
java.lang.AssertionError: expected [Eastern European Standard Time] but found [Kyiv Standard Time]
java.lang.AssertionError: expected [heure normale d\u2019Europe de l\u2019Est] but found [Kyiv (heure standard)]
java.lang.AssertionError: expected [Osteurop\u00e4ische Normalzeit] but found [Kyiv Normalzeit]
~~~

and passes with the patched build.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8293834](https://bugs.openjdk.org/browse/JDK-8293834): Update CLDR data following tzdata 2022c update

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/752/head:pull/752` \
`$ git checkout pull/752`

Update a local copy of the PR: \
`$ git checkout pull/752` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/752/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 752`

View PR using the GUI difftool: \
`$ git pr show -t 752`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/752.diff">https://git.openjdk.org/jdk17u-dev/pull/752.diff</a>

</details>

### CODE REVIEW

**Comment by gnu-andrew** [comment]
Ping?

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by gnu-andrew** [comment]
Ping?

> Lgtm.

Thanks Paul. Flagged for approval.

**Comment by GoeLin** [comment]
Hi @gnu-andrew, this is ready to be pushed, isn't it?

**Comment by gnu-andrew** [comment]
Now I see `jdk17u-fix-yes`, yes :)

**Pull request closed without merging**
