### PR TITLE
8302800: Augment NaN handling tests of FDLIBM methods

### PR DESCRIPTION
**Pull request by amosshi**
Backport of [JDK-8302800](https://bugs.openjdk.org/browse/JDK-8302800)
- This PR contains two PR
- `commit 1` is made by the `git apply` which is `clean` 
- `commit 2` adds the missing file `test/jdk/java/lang/Math/InverseTrigTests.java` currently does not exist in `jdk17u-dev`, it was originally added by [JDK-8302026](https://bugs.openjdk.org/browse/JDK-8302026) via [commit](https://github.com/openjdk/jdk/commit/3ba156082b73c4a8e9d890a57a42fb68df2bf98f)

Testing
- Local: Test passed on `MacOS 14.5` on Apple M1 Max
  - `CubeRootTests.java`: Test results: passed: 1
  - `Expm1Tests.java`: Test results: passed: 1
  - `HyperbolicTests.java`: Test results: passed: 1
  - `Log10Tests.java`: Test results: passed: 1
  - `Log1pTests.java`: Test results: passed: 1
  - `Tests.java`: Not applicable: not a test
  - `InverseTrigTests.java`: Test results: passed: 1
- Pipeline: 
  - Linux, Windows - Passed
  - MacOS - Skipped (`This request was automatically failed because there were no enabled runners online to process the request for more than 1 days.`)
- Testing Machine: SAP nightlies Passed on `2024-08-07`
  - Automated jtreg test: jtreg_jdk_tier1, Started at 2024-08-06 20:35:20+01:00
  - java/lang/Math/CubeRootTests.java: SUCCESSFUL GitHub 📊 - [20:41:53.428 -> 166 msec]
  - java/lang/Math/Expm1Tests.java: SUCCESSFUL GitHub 📊 - [20:41:54.175 -> 253 msec]
  - java/lang/Math/HyperbolicTests.java: SUCCESSFUL GitHub 📊 - [20:41:54.428 -> 307 msec]
  - java/lang/Math/Log10Tests.java: SUCCESSFUL GitHub 📊 - [20:41:55.238 -> 196 msec]
  - java/lang/Math/Log1pTests.java: SUCCESSFUL GitHub 📊 - [20:41:55.434 -> 202 msec]
  - java/lang/Math/InverseTrigTests.java: SUCCESSFUL GitHub 📊 - [20:41:55.038 -> 199 msec]

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8302800](https://bugs.openjdk.org/browse/JDK-8302800) needs maintainer approval

### Issue
 * [JDK-8302800](https://bugs.openjdk.org/browse/JDK-8302800): Augment NaN handling tests of FDLIBM methods (**Sub-task** - P4 - Approved)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2779/head:pull/2779` \
`$ git checkout pull/2779`

Update a local copy of the PR: \
`$ git checkout pull/2779` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2779/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2779`

View PR using the GUI difftool: \
`$ git pr show -t 2779`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2779.diff">https://git.openjdk.org/jdk17u-dev/pull/2779.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2779#issuecomment-2266289206)

### CODE REVIEW

**Comment by MBaesken** [comment]
JDK-8302026  which contains the 'missing' InverseTrigTests.java test was never backported to 17 so please check again that the test is really stable.

**Comment by amosshi** [comment]
Hi @MBaesken ,

FYI: we have monitored the test case for another week, so far so good, all passed:

- Started at `2024-08-15 00:54:43+01:00`
  - Automated jtreg test: jtreg_jdk_tier1 
  - java/lang/Math/InverseTrigTests.java: SUCCESSFUL GitHub 📊 - [01:00:38.234 -> 578 msec]
- Started at `2024-08-13 22:27:17+01:00`
  - Automated jtreg test: jtreg_jdk_tier1
  - java/lang/Math/InverseTrigTests.java: SUCCESSFUL GitHub 📊 - [22:41:57.003 -> 3,551 msec]
- Started at `2024-08-12 09:51:13+01:00`
  - Automated jtreg test: jtreg_jdk_tier1
  - java/lang/Math/InverseTrigTests.java: SUCCESSFUL GitHub 📊 - [09:57:48.239 -> 119 msec]
- Started at `2024-08-11 22:25:03+01:00`
  - Automated jtreg test: jtreg_jdk_tier1
  - java/lang/Math/InverseTrigTests.java: SUCCESSFUL GitHub 📊 - [22:39:57.485 -> 454 msec]
- Started at `2024-08-09 23:02:03+01:00`
  - Automated jtreg test: jtreg_jdk_tier1
  - java/lang/Math/InverseTrigTests.java: SUCCESSFUL GitHub 📊 - [23:16:11.723 -> 577 msec]
- Started at `2024-08-09 18:38:52+01:00`
  - Automated jtreg test: jtreg_jdk_tier1
  - java/lang/Math/InverseTrigTests.java: SUCCESSFUL GitHub 📊 - [18:53:29.160 -> 515 msec]


Regards
Amos
A Happy Developer

**Review by MBaesken — APPROVED** [review]

**Comment by amosshi** [comment]
/approval request "Backporting for parity with 17.0.13-oracle. No risk, test fix. Un-Clean backport. Test passes and SAP nightlies pass on 2024-08-07,15”

**Comment by GoeLin** [comment]
There are red tests, what is wrong?

**Comment by amosshi** [comment]
> There are red tests, what is wrong?

Reason
- `This request was automatically failed because there were no enabled runners online to process the request for more than 1 days.`

Action
- I will re-trigger

**Pull request closed without merging**
