### PR TITLE
8279164: Disable TLS_ECDH_* cipher suites

### PR DESCRIPTION
**Pull request by TheRealMDoerr**
Backport of [JDK-8279164](https://bugs.openjdk.org/browse/JDK-8279164). The test changes in DisabledAlgorithms.java needed manual integration. The rest applies cleanly.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8279164](https://bugs.openjdk.org/browse/JDK-8279164) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8332812](https://bugs.openjdk.org/browse/JDK-8332812) to be approved

### Issues
 * [JDK-8279164](https://bugs.openjdk.org/browse/JDK-8279164): Disable TLS_ECDH_* cipher suites (**Enhancement** - P3 - Approved)
 * [JDK-8332812](https://bugs.openjdk.org/browse/JDK-8332812): Disable TLS_ECDH_* cipher suites (**CSR**)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2559/head:pull/2559` \
`$ git checkout pull/2559`

Update a local copy of the PR: \
`$ git checkout pull/2559` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2559/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2559`

View PR using the GUI difftool: \
`$ git pr show -t 2559`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2559.diff">https://git.openjdk.org/jdk17u-dev/pull/2559.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2559#issuecomment-2157977695)

### CODE REVIEW

**Review by MBaesken — APPROVED** [review]

**Comment by TheRealMDoerr** [comment]
Thanks for the review!

**Comment by TheRealMDoerr** [comment]
/approval request Should get backported for parity with 17.0.13-oracle. The backport has been reviewed and tier 1-4 have passed.

**Comment by gnu-andrew** [comment]
I believe there's an error in this backport. In trunk, the change in `test/jdk/javax/net/ssl/ciphersuites/DisabledAlgorithms.java` is as follows:

~~~
-    // supported 3DES, DES, RC4, NULL, and anon cipher suites
-    // it does not contain KRB5 cipher suites because they need a KDC
-    private static final String[] desede_des_rc4_null_anon_ciphersuites
+    // disabled 3DES, DES, RC4, NULL, anon, and ECDH cipher suites
+    private static final String[] disabled_ciphersuites
~~~

and

~~~
@@ -109,7 +108,19 @@ public class DisabledAlgorithms {
         "SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA",
         "TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA",
         "TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA",
-        "SSL_RSA_WITH_3DES_EDE_CBC_SHA"
+        "SSL_RSA_WITH_3DES_EDE_CBC_SHA",
+        "TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384",
~~~

In backporting to 17u, changes related to 3DES from [JDK-8163327](https://bugs.openjdk.org/browse/JDK-8163327) have been incorporated that don't belong in this fix.

~~~
-    // supported RC4, NULL, and anon cipher suites
-    // it does not contain KRB5 cipher suites because they need a KDC
-    private static final String[] rc4_null_anon_ciphersuites = new String[] {
+    // disabled 3DES, DES, RC4, NULL, anon, and ECDH cipher suites
+    private static final String[] disabled_ciphersuites
+        = new String[] {
~~~

and

~~~
-        "TLS_ECDH_anon_WITH_RC4_128_SHA"
+        "TLS_ECDH_anon_WITH_RC4_128_SHA",
+        "SSL_RSA_WITH_3DES_EDE_CBC_SHA",
+        "TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384",
~~~

We shouldn't be adding 3DES here. This is not part of this PR. I'll file a bug to get this fixed. It also seems to affect the 11u backport. I spotted this when reviewing the 8u one, which, being based on trunk, did not have this addition when compared with the 11u one.

**Comment by TheRealMDoerr** [comment]
You're right. `"SSL_RSA_WITH_3DES_EDE_CBC_SHA"` should get removed again. Thanks for spotting it! Yes, please file a test bug for 17u and 11u (related to [JDK-8333998](https://bugs.openjdk.org/browse/JDK-8333998) and [JDK-8334194](https://bugs.openjdk.org/browse/JDK-8334194)).

**Comment by gnu-andrew** [comment]
Filed https://bugs.openjdk.org/browse/JDK-8334335

**Pull request closed without merging**
