### PR TITLE
8277503: compiler/onSpinWait/TestOnSpinWaitAArch64DefaultFlags.java failed with "OnSpinWaitInst with the expected value 'isb' not found."

### PR DESCRIPTION
**Pull request by eastig**
The backport of JDK-8277137 "Set OnSpinWaitInst/OnSpinWaitInstCount defaults to "isb"/1 for Arm Neoverse N1" adds a new test: TestOnSpinWaitAArch64DefaultFlags.java. The test has a bug. It fails on release builds.
This is a backport of the test fix. The original patch removed the test from test/hotspot/jtreg/ProblemList.txt. This change causes a conflict in ProblemList.txt because the test does not exist and is not excluded in jdk17.
The change to the test applies cleanly.

As the backport does not change anything in JVM sources, it can be tested with TestOnSpinWaitAArch64DefaultFlags.java on fastdebug and release builds.

Tested: release and fastdebug builds

- `make test TEST=hotspot/jtreg/compiler/onSpinWait/TestOnSpinWaitAArch64DefaultFlags.java`: Passed

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8277503](https://bugs.openjdk.java.net/browse/JDK-8277503): compiler/onSpinWait/TestOnSpinWaitAArch64DefaultFlags.java failed with "OnSpinWaitInst with the expected value 'isb' not found."

### Reviewers
 * [Paul Hohensee](https://openjdk.java.net/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17u-dev pull/107/head:pull/107` \
`$ git checkout pull/107`

Update a local copy of the PR: \
`$ git checkout pull/107` \
`$ git pull https://git.openjdk.java.net/jdk17u-dev pull/107/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 107`

View PR using the GUI difftool: \
`$ git pr show -t 107`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17u-dev/pull/107.diff">https://git.openjdk.java.net/jdk17u-dev/pull/107.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
In case it's needed, lgtm.

**Comment by eastig** [comment]
@phohensee Thank you.

**Comment by GoeLin** [comment]
@easting, please enable Pre-submit tests. We see results when you rebase the change after pushing 8277137.

Strange that this was not marked as clean. Maybe it will be marked clean after rebasing.

**Comment by eastig** [comment]
> @easting, please enable Pre-submit tests. We see results when you rebase the change after pushing 8277137.
> 
> Strange that this was not marked as clean. Maybe it will be marked clean after rebasing.

Sorry, I should have written the reason of this here. The original patch removed the test from test/hotspot/jtreg/ProblemList.txt. This change causes a conflict in ProblemList.txt because the test does not exist and is not excluded in jdk17.

**Pull request closed without merging**
