### PR TITLE
8307423: [s390x] Represent Registers as values

### PR DESCRIPTION
**Pull request by offamitkumar**
Hi all,

This pull request contains a backport of commit [8bbd264c](https://github.com/openjdk/jdk/commit/8bbd264c6e4b4045a218f11ae6b5b4f395bc2aa9) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Amit Kumar on 8 May 2023 and was reviewed by Martin Doerr and Lutz Schmidt.

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8307423](https://bugs.openjdk.org/browse/JDK-8307423) needs maintainer approval
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8307423](https://bugs.openjdk.org/browse/JDK-8307423): [s390x] Represent Registers as values (**Enhancement** - P3 - Approved)

### Reviewers
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**) ⚠️ Review applies to [23939e02](https://git.openjdk.org/jdk17u-dev/pull/2453/files/23939e02de5970918e149f7c233af9bd243f23cf)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2453/head:pull/2453` \
`$ git checkout pull/2453`

Update a local copy of the PR: \
`$ git checkout pull/2453` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2453/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2453`

View PR using the GUI difftool: \
`$ git pr show -t 2453`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2453.diff">https://git.openjdk.org/jdk17u-dev/pull/2453.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2453#issuecomment-2103267460)

### CODE REVIEW

**Comment by offamitkumar** [comment]
I ran tier1 test and no new failure appeared. 

@RealLucy please review. Initially it was clean patch but I had to delete `register_definitions_s390.cpp` and following that a minor change in `vmStruct.cpp`.

**Review by RealLucy — APPROVED** [review]
Looks good.
A lot of tedious work! Thank you.

**Comment by offamitkumar** [comment]
/approval request backporting this change as we are getting warnings while build jdk17 with gcc-11.4, Performed tier1 and no new failure appeared.

**Comment by TheRealMDoerr** [comment]
Please merge and make sure it the change in [vmStructs.cpp](https://github.com/openjdk/jdk17u-dev/pull/2453#diff-7d448441e80a0b784429d5d8aee343fcb131c224b8ec7bc70ea636f78d561ecd) works on both platforms: `NOT_S390( NOT_PPC64(`. Thanks!

**Comment by offamitkumar** [comment]
I ran tier1 test again after the code change, on fastdebug build. Result is good there and GHA also looks good. 

Thanks @RealLucy for review and Martin in resolving merge conflict :-) 

/integrate

**Pull request closed without merging**
