### PR TITLE
8293114: JVM should trim the native heap

### PR DESCRIPTION
**Pull request by shipilev**
Unclean backport to get useful experimental feature to LTS users.

In addition to usual contextual differences, there is a number of differences against upstream version:
 - `synchronizer.cpp` hunks are different, since we do not have [JDK-8256302](https://github.com/openjdk/jdk/commit/6402004852ccc993bb6e879c49fb71e2afdcdfbe) in JDK 17
 - `NativeHeapTrimmer_lock` changed from `Mutex::safepoint` to `Mutex::leaf`, since [JDK-8273915](https://github.com/openjdk/jdk/commit/111d5e1a9324cb5e8d98627f6329d17fcbc9c13d) renamed it after JDK 17
 - `NativeHeapTrimmer_lock` should also allow VMThread block and never require safepoint checks; this was simplified by [JDK-8274004](https://bugs.openjdk.org/browse/JDK-8274004) later
 - `vmError.cpp` code was rewritten in JDK 17 style
 - gtest uses `EXPECT_NOT_NULL`, only brought by [JDK-8295865](https://github.com/openjdk/jdk/commit/657a0b2f1564e1754dbd64b776c53a52c480c901#diff-35b3b4703decd15bfd2fc614d431e909727a6cf4d399cf05c7a12466e61ab8a0R58-R59) -- I rewrote them to EXPECT_NE/EQ.

Additional testing:
 - [x] Linux x86_64 fastdebug, trim tests
 - [x] Linux x86_64 fastdebug, `tier1`
 - [x] Linux x86_64 fastdebug, `tier2`
 - [x] Linux x86_64 fastdebug, `tier3`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8293114](https://bugs.openjdk.org/browse/JDK-8293114): JVM should trim the native heap (**Enhancement** - P4)

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1616/head:pull/1616` \
`$ git checkout pull/1616`

Update a local copy of the PR: \
`$ git checkout pull/1616` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1616/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1616`

View PR using the GUI difftool: \
`$ git pr show -t 1616`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1616.diff">https://git.openjdk.org/jdk17u-dev/pull/1616.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1616#issuecomment-1646064692)

### CODE REVIEW

**Comment by shipilev** [comment]
@tstuefe, please review if you have time.

**Review by tstuefe — APPROVED** [review]
Good! Thanks for doing this, and sorry for the delay, I'm swamped.

I would wait a bit though, and let the patch cook upstream, before pushing. It will obviously also need https://bugs.openjdk.org/browse/JDK-8312525.

**Comment by shipilev** [comment]
I think we are ready for jdk17u integration. Do you agree, @tstuefe?

**Comment by tstuefe** [comment]
Hold up , I'll ask my SAP collegues first to put this through their backport CI.

**Comment by shipilev** [comment]
> Hold up , I'll ask my SAP collegues first to put this through their backport CI.

I see `jdk17u-fix-yes` from Goetz set today. Have you heard about testing results?

**Comment by tstuefe** [comment]
> > Hold up , I'll ask my SAP collegues first to put this through their backport CI.
> 
> I see `jdk17u-fix-yes` from Goetz set today. Have you heard about testing results?

Martin reported some errors. I suspect he sees the known ones that had been fixed with 8312525, but I need to confirm.

**Comment by TheRealMDoerr** [comment]
The backport looks good, but the test has issues in head as well. Thanks, Thomas, for investigating!

**Comment by shipilev** [comment]
No problem, we can wait for that test to be fixed, and the backport for it lined up for 17u-dev, before we proceed with this integration. Then we would not break anyone's CI, hopefully.

**Comment by shipilev** [comment]
> Okay, we see still problems in head at SAP. https://bugs.openjdk.org/browse/JDK-8314426. Lets wait with the downport till that one is fixed. Should be quick, hopefully.

OK, I lined up the backport to 17u-dev for that fix here: #1687. Assuming that passes GHA testing, are we good with integrating all three PRs in 17u-dev? I would like to reserve some time to deal with any other low-probability fallout before 17.0.9 stabilization form.

**Comment by tstuefe** [comment]
> > Okay, we see still problems in head at SAP. https://bugs.openjdk.org/browse/JDK-8314426. Lets wait with the downport till that one is fixed. Should be quick, hopefully.
> 
> OK, I lined up the backport to 17u-dev for that fix here: #1687. Assuming that passes GHA testing, are we good with integrating all three PRs in 17u-dev? I would like to reserve some time to deal with any other low-probability fallout before 17.0.9 stabilization form.

I'm fine with it, but note that I will be gone throughout September.

**Comment by tstuefe** [comment]
I see you have all follow-ups already neatly aligned; will you ship it today or so to still get into the rapidly closing window?

**Comment by shipilev** [comment]
> I see you have all follow-ups already neatly aligned; will you ship it today or so to still get into the rapidly closing window?

Yes, my plan is to integrate today. I was checking if GHAs are still good with this PR.

**Comment by shipilev** [comment]
Testing is clean. Review is here. Push approval granted.

/integrate

**Pull request closed without merging**
