### PR TITLE
8293826: Closed test fails after JDK-8276108 on aarch64

### PR DESCRIPTION
**Pull request by martinuy**
Hi all,

This pull request contains a backport of commit [6d3fd860d748a092a65ab9700b47686099b81bf4](https://github.com/openjdk/jdk/commit/6d3fd860d748a092a65ab9700b47686099b81bf4) from the [openjdk/jdk](https://github.com/openjdk/jdk) repository.

This backport is a follow up fix of [JDK-8277928](https://bugs.openjdk.org/browse/JDK-8277928).

This backport applied cleanly.

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8293826](https://bugs.openjdk.org/browse/JDK-8293826): Closed test fails after JDK-8276108 on aarch64

### Reviewers
 * [Goetz Lindenmaier](https://openjdk.org/census#goetz) (@GoeLin - **Reviewer**) ⚠️ Review applies to [a04a1e60](https://git.openjdk.org/jdk17u-dev/pull/669/files/a04a1e6076c12ec246576ffa923ec92fc3e771bf)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/669/head:pull/669` \
`$ git checkout pull/669`

Update a local copy of the PR: \
`$ git checkout pull/669` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/669/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 669`

View PR using the GUI difftool: \
`$ git pr show -t 669`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/669.diff">https://git.openjdk.org/jdk17u-dev/pull/669.diff</a>

</details>

### CODE REVIEW

**Comment by martinuy** [comment]
The Skara tools have had issues with this backport PR because JDK-8278417 is not public. A review will apparently be needed but the original patch (from openjdk/jdk) applies cleanly.

**Review by GoeLin — APPROVED** [review]
This is a clean backport.

**Comment by GoeLin** [comment]
Pre-submit failure. The change only touches aarch specific code, so this windows x86_64 failure can not be related.

**Comment by GoeLin** [comment]
Hi @martinuy,
please change the title to "Backport 6d3fd860d748a092a65ab9700b47686099b81bf4"
I think this works for closed changes, too.

**Comment by martinuy** [comment]
Hi @GoeLin ,

I made the title change but it looks like the Skara bot is not acknowledging it. Can you please approve it manually?

Thanks,
Martin.-

**Comment by RealCLanger** [comment]
> Hi @GoeLin ,
> 
> I made the title change but it looks like the Skara bot is not acknowledging it. Can you please approve it manually?
> 
> Thanks, Martin.-

OK, then I suggest to create a JBS Backport issue manually and change the PR title to its JDK-nnn ID. Then it should be correctly handled.

**Comment by martinuy** [comment]
@RealCLanger going back to JDK-8293826, which is the backport ticket created referencing JDK-8278417 as the procedure for non-public JBS describes. Please notice that I've tried this already: https://github.com/openjdk/jdk17u-dev/pull/669#event-7390100363. It seems like it's not finding the original commit hash-id, which makes sense because the reference from JDK-8293826 to JDK-8278417 is not public and apparently the bot is not looking for hashes directly in the repository.

**Comment by GoeLin** [comment]
Hi,
I can not approve it. The bots have to add the ready tag.
Christoph, Martin already tried making a Backport JBS Issue which is 8293826.

Martin, did you try naming the PR "8277928: Closed test fails after JDK-8276108 on aarch64",
i.e. with the closed bug-id? (No prefix JDK-!)

If this all does not work, you could try changing 8293826 to be a "bug". 
When it is pushed, you can change it back to "Backport".

**Comment by RealCLanger** [comment]
Now it looks as if JDK-8293826 has been hijacked by an Oracle 11.0.18 backport. @martinuy seems like you have to create another backport bug and change the title to the new bug id. Please do so and then we'll check whether we can get the PR to the ready state. If all does not work we might need to contact the Skara folks.

**Comment by RealCLanger** [comment]
Ah, I've just seen that the bot won't allow PRs against backport bugs. So the workaround would then really be to change the JBS backport item into a bug, integrate and then change the jbs back to backport. Maybe really something that needs a revisit by Skara folks.

**Comment by martinuy** [comment]
Seems like turning 8293826 into a bug (instead of a backport) made the trick. I'll integrate it this Monday and turn 8293826 back into a backport.

Thanks!

**Comment by RealCLanger** [comment]
I made some adjustments to the JBS bugs. It should hopefully look quite straightforward now.

**Pull request closed without merging**
