### PR TITLE
8318607: Enable parallelism in vmTestbase/nsk/stress/jni tests

### PR DESCRIPTION
**Pull request by elifaslan1**
Clean backport to enable parallelism in vmTestbase/nsk/stress/jni tests

Tested with GHA

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8318607](https://bugs.openjdk.org/browse/JDK-8318607) needs maintainer approval

### Issue
 * [JDK-8318607](https://bugs.openjdk.org/browse/JDK-8318607): Enable parallelism in vmTestbase/nsk/stress/jni tests (**Enhancement** - P4 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2109/head:pull/2109` \
`$ git checkout pull/2109`

Update a local copy of the PR: \
`$ git checkout pull/2109` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2109/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2109`

View PR using the GUI difftool: \
`$ git pr show -t 2109`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2109.diff">https://git.openjdk.org/jdk17u-dev/pull/2109.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2109#issuecomment-1879841773)

### CODE REVIEW

**Comment by shipilev** [comment]
You need the maintainer approval request, @elifaslan1 ;)

**Comment by elifaslan1** [comment]
/approval request Enables parallelism in vmTestbase/nsk/stress/jni tests. Clean backport. Tests pass.

**Pull request closed without merging**
