### PR TITLE
8296715: CLDR v42 update for tzdata 2022f

### PR DESCRIPTION
**Pull request by MBaesken**
backport of 8296715;
avoid [make/data/cldr/common/dtd/ldmlSupplemental.dtd](https://github.com/openjdk/jdk/commit/54c986e7d5d0b48a22b4da81c13153ce431c9f2f#diff-0854244a893369539d4984ea67bc7e8788659b4f059c6e5f61a8cdf7f23c80c2)
changes like it has been done in the 19u and 15u backports;  test files need manual adjustment because of changes in the stride

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8296715](https://bugs.openjdk.org/browse/JDK-8296715): CLDR v42 update for tzdata 2022f

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/942/head:pull/942` \
`$ git checkout pull/942`

Update a local copy of the PR: \
`$ git checkout pull/942` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/942/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 942`

View PR using the GUI difftool: \
`$ git pr show -t 942`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/942.diff">https://git.openjdk.org/jdk17u-dev/pull/942.diff</a>

</details>

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
LGTM. Thanks for backporting!

**Comment by gnu-andrew** [comment]
The change looks good to me, but I think this should be a critical request for openjdk/jdk17u instead, so it makes 17.0.6 (17u went into rampdown yesterday: https://mail.openjdk.org/pipermail/jdk-updates-dev/2022-November/019048.html). Note that Oracle have included this in their 17.0.6.

Do you plan to handle 11u as well?

**Comment by MBaesken** [comment]
> Do you plan to handle 11u as well?

I am preparing an 11u-dev PR as well.

**Comment by gnu-andrew** [comment]
> > Do you plan to handle 11u as well?
> 
> I am preparing an 11u-dev PR as well.

Great. Same thing, please aim for 11u so we can get this in with the tzdata 2022f change.

**Comment by MBaesken** [comment]
https://wiki.openjdk.org/display/JDKUpdates/JDK+17u
Tuesday, **December 6 2022: Rampdown; last merge from jdk17u-dev to jdk17u**  - so no critical request needed.

/integrate

**Comment by gnu-andrew** [comment]
> > Do you plan to handle 11u as well?
> 
> I am preparing an 11u-dev PR as well.

Great. Same thing, please aim for 11u so we can get this in with the tzdata 2022f change.

> https://wiki.openjdk.org/display/JDKUpdates/JDK+17u Tuesday, **December 6 2022: Rampdown; last merge from jdk17u-dev to jdk17u** - so no critical request needed.
> 
> /integrate

Ok this is strange. Why is 11u & 17u rampdown so late? 8u's was last week.

**Pull request closed without merging**
