### PR TITLE
8280940: gtest os.release_multi_mappings_vm is racy

### PR DESCRIPTION
**Pull request by tstuefe**
Fixes intermittent errors in multi-release gtest. Low risk. Does not apply cleanly; minor fixes were needed (needed include memTracker.hpp, and needed some resolving w/o resulting changes)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8280940](https://bugs.openjdk.java.net/browse/JDK-8280940): gtest os.release_multi_mappings_vm is racy

### Reviewers
 * [Martin Doerr](https://openjdk.java.net/census#mdoerr) (@TheRealMDoerr - **Reviewer**) ⚠️ Review applies to e1cf89d61b1c811eb2cbac261d7dba7d77ce9bc7

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17u-dev pull/328/head:pull/328` \
`$ git checkout pull/328`

Update a local copy of the PR: \
`$ git checkout pull/328` \
`$ git pull https://git.openjdk.java.net/jdk17u-dev pull/328/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 328`

View PR using the GUI difftool: \
`$ git pr show -t 328`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17u-dev/pull/328.diff">https://git.openjdk.java.net/jdk17u-dev/pull/328.diff</a>

</details>

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
LGTM.

**Comment by GoeLin** [comment]
Hi @tstuefe, 
I seems you have not enabled the github actions for this repo.
Can you please check, and, as they won't run on this PR any more, state what testing you have done?
Thanks!

**Comment by tstuefe** [comment]
> Hi @tstuefe, I seems you have not enabled the github actions for this repo. Can you please check, and, as they won't run on this PR any more, state what testing you have done? Thanks!

Oh. :-( I missed that. How do I do that again? It seems to work for my 11 repo, and I can't remember doing anything special there.

**Pull request closed without merging**
