### PR TITLE
8275320: NMT should perform buffer overrun checks

### PR DESCRIPTION
**Pull request by tstuefe**
Not a clean downport:

- testutils.cpp/.hpp does not exist yet. I took this over (it is just a bunch of test helpers for gtests)
- os.cpp, in os::malloc, the size overflow check added with the downport of JDK-8286519 needed to be reformulated.

I also added a small, JDK17 only gtest to test for size argument overflow. Ideally that should have been done with JDK-8286519. It is release only since in debug we will get an assert which is fine but I did not feel like adding a death test for it. 

Note that in head, I am in the process of fixing https://bugs.openjdk.org/browse/JDK-8295865, and that will introduce much more thorough regression tests. Should we ever downport JDK-8295865 to 17, the test introduced here can be removed.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8275320](https://bugs.openjdk.org/browse/JDK-8275320): NMT should perform buffer overrun checks
 * [JDK-8275320](https://bugs.openjdk.org/browse/JDK-8275320): NMT should perform buffer overrun checks
 * [JDK-8275301](https://bugs.openjdk.org/browse/JDK-8275301): Unify C-heap buffer overrun checks into NMT

### Reviewers
 * [Goetz Lindenmaier](https://openjdk.org/census#goetz) (@GoeLin - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/842/head:pull/842` \
`$ git checkout pull/842`

Update a local copy of the PR: \
`$ git checkout pull/842` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/842/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 842`

View PR using the GUI difftool: \
`$ git pr show -t 842`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/842.diff">https://git.openjdk.org/jdk17u-dev/pull/842.diff</a>

</details>

### CODE REVIEW

**Comment by tstuefe** [comment]
Ping.

**Review by GoeLin — APPROVED** [review]
The only adaption in the live coding I spotted is that below // Check for overflow. in os.cpp.
Thanks for adding the thorough testing for the feature. 

LGTM

**Comment by RealCLanger** [comment]
@tstuefe would you mind moving this from draft to non-draft?

**Pull request closed without merging**
