### PR TITLE
8305819: LogConfigurationTest intermittently fails on AArch64

### PR DESCRIPTION
**Pull request by mmyxym**
Hi all,

This pull request contains a backport of commit [911cc7cb](https://github.com/openjdk/jdk/commit/911cc7cb07ed44b24b4c20977d7d6e475bd1b234) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

It fixed a logging crash due to arm weak memory model.

The commit being backported was authored by gaogao-mem on 15 May 2023 and was reviewed by Andrew Haley, David Holmes and Xin Liu.

The conflicts only come from the difference of "NULL" and "nullptr".

Additional testing:
- [x] Verified the test case in original PR.

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8305819](https://bugs.openjdk.org/browse/JDK-8305819) needs maintainer approval

### Issue
 * [JDK-8305819](https://bugs.openjdk.org/browse/JDK-8305819): LogConfigurationTest intermittently fails on AArch64 (**Bug** - P4 - Approved)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2460/head:pull/2460` \
`$ git checkout pull/2460`

Update a local copy of the PR: \
`$ git checkout pull/2460` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2460/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2460`

View PR using the GUI difftool: \
`$ git pr show -t 2460`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2460.diff">https://git.openjdk.org/jdk17u-dev/pull/2460.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2460#issuecomment-2107208113)

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
LGTM.

**Comment by mmyxym** [comment]
/approval request backport of fixing crash due to weak memory model. Conflicts come from  the difference of "NULL" and "nullptr". Risk is very low.

**Comment by mmyxym** [comment]
Could committers please help to sponsor?

**Pull request closed without merging**
