### PR TITLE
8315559: Delay TempSymbol cleanup to avoid symbol table churn

### PR DESCRIPTION
**Pull request by olivergillespie**
Hi all,

This pull request contains a backport of commit [d23f4f12](https://github.com/openjdk/jdk/commit/d23f4f12adf1ea26b8c340efe2c3854e50b68301) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Oli Gillespie on 4 Dec 2023 and was reviewed by Coleen Phillimore, Kim Barrett and Aleksey Shipilev.

Thanks!

The backport is not clean. `symbolHandle` does not exist in 17, so I put the same functionality in `symbolTable` where `TempNewSymbol` resides for 17. The functionality itself is essentially identical, with the other change being that `maybe_decrement_refcount` helper also does not exist, so I just added a null check.
`test/hotspot/gtest/classfile/test_placeholders.cpp` does not exist, so it didn't need to be fixed. `test_symbolTable.cpp` failed as expected before fixing, and applied cleanly.

Testing on the original benchmark confirms this fixes the performance regression:
```
java -Xmx1G -Xms1G -XX:+AlwaysPreTouch -jar dacapo-9.120-MR1.jar --size large --iterations 30 pmd

Before:
...
===== DaCapo 9.12-MR1 pmd PASSED in 1072 msec =====

After:
...
===== DaCapo 9.12-MR1 pmd PASSED in 1013 msec =====
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8315559](https://bugs.openjdk.org/browse/JDK-8315559) needs maintainer approval

### Issue
 * [JDK-8315559](https://bugs.openjdk.org/browse/JDK-8315559): Delay TempSymbol cleanup to avoid symbol table churn (**Bug** - P3 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2424/head:pull/2424` \
`$ git checkout pull/2424`

Update a local copy of the PR: \
`$ git checkout pull/2424` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2424/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2424`

View PR using the GUI difftool: \
`$ git pr show -t 2424`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2424.diff">https://git.openjdk.org/jdk17u-dev/pull/2424.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2424#issuecomment-2069939272)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by olivergillespie** [comment]
/approval request Fixes non-trivial performance regression in class-loading (dacapo pmd). Not clean due to file movement but simple to merge. Confirmed that the performance regression is present before the change and fixed after, using the original benchmark. Medium risk as it affects Symbol creation, but has been working in tip and 21 for a few months with no associated issues.

**Review by shipilev — APPROVED** [review]
Looks fine to me.

**Comment by GoeLin** [comment]
I'll approve this for the October update.

**Comment by olivergillespie** [comment]
Cool, thanks!

**Comment by olivergillespie** [comment]
(keepalive)

**Pull request closed without merging**
