### PR TITLE
8307732: build-test-lib is broken

### PR DESCRIPTION
**Pull request by vish-chan**
- This PR backports JDK-8274345, JDK-8303922, JDK-8307732 to jdk17u-dev. The build-test-lib target is broken on jdk17 and is needed to build wb.jar and test-lib.jar.
- `make build-test-lib` works as expected after the change.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8274345](https://bugs.openjdk.org/browse/JDK-8274345) needs maintainer approval
- [x] Commit message must refer to an issue
- [x] [JDK-8303922](https://bugs.openjdk.org/browse/JDK-8303922) needs maintainer approval
- [x] [JDK-8307732](https://bugs.openjdk.org/browse/JDK-8307732) needs maintainer approval

### Issues
 * [JDK-8307732](https://bugs.openjdk.org/browse/JDK-8307732): build-test-lib is broken (**Bug** - P4 - Approved)
 * [JDK-8274345](https://bugs.openjdk.org/browse/JDK-8274345): make build-test-lib is broken (**Bug** - P4 - Approved)
 * [JDK-8303922](https://bugs.openjdk.org/browse/JDK-8303922): build-test-lib target is broken (**Enhancement** - P4 - Approved)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1801/head:pull/1801` \
`$ git checkout pull/1801`

Update a local copy of the PR: \
`$ git checkout pull/1801` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1801/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1801`

View PR using the GUI difftool: \
`$ git pr show -t 1801`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1801.diff">https://git.openjdk.org/jdk17u-dev/pull/1801.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1801#issuecomment-1737242936)

### CODE REVIEW

**Comment by shipilev** [comment]
I was confused a bit why this backport is not marked by bots as `clean`.

Digging a bit, this PR is effectively a combination of three others, right?
https://bugs.openjdk.org/browse/JDK-8274345
https://bugs.openjdk.org/browse/JDK-8303922
https://bugs.openjdk.org/browse/JDK-8307732

Are they applying cleanly as the series?

**Comment by parttimenerd** [comment]
Thanks for the backport :)

**Comment by vish-chan** [comment]
I've updated the PR with a stack of clean commits.

**Comment by shipilev** [comment]
Aha! So we missed the hunk in `[test/lib/jdk/test/lib/hexdump/ASN1Formatter.java](https://github.com/openjdk/jdk17u-dev/pull/1801/files#diff-e1e2d7227c36a4b597376f217cb9e41e351ef6bed60831735460eaf3d5b56e1c)`, which new PR now has. Very nice!

**Comment by vish-chan** [comment]
/approval request Fixes build-test-lib target. Applies as stack of three clean commits. make build-test-lib now works.

**Comment by vish-chan** [comment]
/approval JDK-8274345 request Fixes build-test-lib target. Applies as stack of three clean commits. make build-test-lib now works.
/approval JDK-8303922 request  Fixes build-test-lib target. Applies as stack of three clean commits. make build-test-lib now works.
/approval JDK-8307732 request Fixes build-test-lib target. Applies as stack of three clean commits. make build-test-lib now works.

**Pull request closed without merging**
