### PR TITLE
8322985: [BACKOUT] 8318562: Computational test more than 2x slower when AVX instructions are used

### PR DESCRIPTION
**Pull request by shipilev**
This reverts the patch that caused recently identified regression. Luckily, we have it only in 17.0.11, which gives us a normal opportunity to revert it.

The complication is that mainline patch is not applying cleanly, because JDK 17u backport is contextually different. So I `git revert`-ed the jdk17u-dev commit instead: https://github.com/openjdk/jdk17u-dev/commit/9a104e08f79fecabf5de2e0ece914260319d2f28. But that makes the backport formally unclean.

Additional testing:
 - [x] GHA

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8322985](https://bugs.openjdk.org/browse/JDK-8322985) needs maintainer approval

### Issue
 * [JDK-8322985](https://bugs.openjdk.org/browse/JDK-8322985): [BACKOUT] 8318562: Computational test more than 2x slower when AVX instructions are used (**Sub-task** - P1 - Approved)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2103/head:pull/2103` \
`$ git checkout pull/2103`

Update a local copy of the PR: \
`$ git checkout pull/2103` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2103/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2103`

View PR using the GUI difftool: \
`$ git pr show -t 2103`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2103.diff">https://git.openjdk.org/jdk17u-dev/pull/2103.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2103#issuecomment-1878900316)

### CODE REVIEW

**Comment by shipilev** [comment]
/approval request This reverts the patch that caused recently identified regression. Clean git revert on jdk17u-dev commit works without problems. GHA will sanity-check it.

**Review by vnkozlov — APPROVED** [review]
Good.

**Pull request closed without merging**
