### PR TITLE
8326591: New test JmodExcludedFiles.java fails on Windows when --with-external-symbols-in-bundles=public is used

### PR DESCRIPTION
**Pull request by SoniaZaldana**
Hi all, 

This PR contains a backport of [43c6f0b5880899b797fab2f851bd35be1c342439](https://github.com/openjdk/jdk/commit/43c6f0b5880899b797fab2f851bd35be1c342439). 

Patch is not clean. Test won't build in 17 because it can't find ```import jdk.internal.util.OperatingSystem```.

This class was introduced in 21 as part of [JDK-8303485](https://bugs.openjdk.org/browse/JDK-8303485).

I've worked around that by removing the dependency to that utility function and checking the operating system with ```test/lib/jdk/test/lib/Platform.java```.

Testing: 
- [x] Modified test case passes 

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8326591](https://bugs.openjdk.org/browse/JDK-8326591) needs maintainer approval

### Issue
 * [JDK-8326591](https://bugs.openjdk.org/browse/JDK-8326591): New test JmodExcludedFiles.java fails on Windows when --with-external-symbols-in-bundles=public is used (**Bug** - P4 - Approved)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2321/head:pull/2321` \
`$ git checkout pull/2321`

Update a local copy of the PR: \
`$ git checkout pull/2321` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2321/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2321`

View PR using the GUI difftool: \
`$ git pr show -t 2321`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2321.diff">https://git.openjdk.org/jdk17u-dev/pull/2321.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2321#issuecomment-2015201369)

### CODE REVIEW

**Comment by GoeLin** [comment]
Hi Sonia, 
the usual way would be to use test/lib/jdk/test/lib/Platform.java instead of System.getProperty("os.name").

**Comment by amosshi** [comment]
SAP nightlies passed on `2024-05-01`
- Automated jtreg test: jtreg_jdk_tier1
- jdk/modules/etc/JmodExcludedFiles.java: SUCCESSFUL GitHub 📊⏲ - [526 msec]

**Review by TheRealMDoerr — APPROVED** [review]
LGTM. Thanks for backporting it!

**Pull request closed without merging**
