### PR TITLE
8296967: [JVMCI] rationalize relationship between getCodeSize and getCode in ResolvedJavaMethod

### PR DESCRIPTION
**Pull request by jerboaa**
Not clean. Copyright in `HotSpotResolvedJavaMethodImpl.java`. `getCodeSizeTest` in
`TestResolvedJavaMethod.java` fixed up manually, as well as omitted `equalsTest` changes
as that test is not in 17u (because both, JDK-8289687 and JDK-8289094 are not in 17u).

HotSpotResolvedJavaFieldTest.java will need a follow-up, JDK-8297590, in order to fix the test
and let it run. I'll get that backported to 17u once it's in JDK tip.

This pr depends on #933 as that PR changes the signature of the `createField` static method in
`HotSpotResolvedObjectTypeImpl` (which the test fix of JDK-8297590 corrects).

Testing: jvmci tests (with backport of JDK-8297590 applied). Existing and newly included tests pass.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8296967](https://bugs.openjdk.org/browse/JDK-8296967): [JVMCI] rationalize relationship between getCodeSize and getCode in ResolvedJavaMethod

### Reviewers
 * [Andrew Dinn](https://openjdk.org/census#adinn) (@adinn - **Reviewer**) ⚠️ Review applies to [271e5457](https://git.openjdk.org/jdk17u-dev/pull/934/files/271e545791c0c8ec25201435e2c6bb7e23a368c0)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/934/head:pull/934` \
`$ git checkout pull/934`

Update a local copy of the PR: \
`$ git checkout pull/934` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/934/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 934`

View PR using the GUI difftool: \
`$ git pr show -t 934`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/934.diff">https://git.openjdk.org/jdk17u-dev/pull/934.diff</a>

</details>

### CODE REVIEW

**Comment by jerboaa** [comment]
@adinn Could you help with a review of this patch too, please? Thank you!

**Review by adinn — APPROVED** [review]
This also looks good.

I agree that dropping equalsTest is correct for this backport. However, if at some point we decide we need to backport JDK-8296967 we will have to try to remember also to reinsert equalsTest.

**Comment by jerboaa** [comment]
Thanks for the review!

**Pull request closed without merging**
