### PR TITLE
8279068: IGV: Update to work with JDK 16 and 17

### PR DESCRIPTION
**Pull request by fitzsim**
I propose the following backport to `jdk17u-dev`:

```
8279068: IGV: Update to work with JDK 16 and 17

Reviewed-by: kvn, neliasso, chagedorn
Backport-of: 7bcca7692b62a37f70c757694f6acff0295371cc
```

This is a mostly-clean backport to 17.  I had to move and apply manually these two lines:

```
--- src/utils/IdealGraphVisualizer/pom.xml
+++ src/utils/IdealGraphVisualizer/pom.xml
@@ -110,11 +131,12 @@
         <module>View</module>
     </modules>
     <properties>
-        <netbeans.version>RELEASE123</netbeans.version>
+        <netbeans.version>RELEASE126</netbeans.version>
         <swinglayouts.version>1.0.2</swinglayouts.version>
         <nbmmvnplugin.version>4.6</nbmmvnplugin.version>
         <mvncompilerplugin.version>3.8.1</mvncompilerplugin.version>
         <mvnjarplugin.version>3.2.0</mvnjarplugin.version>
+        <mvnenforcerplugin.version>3.0.0</mvnenforcerplugin.version>
         <junit.version>4.13.2</junit.version>
         <batik.version>1.14</batik.version>
         <openpdf.version>1.3.26</openpdf.version>
```

With this backport `mvn install; sh igv.sh` works fine for me on `x86-64 Fedora 38`, `fastdebug` build, without needing to add JVM options to the `idealgraphviewer` wrapper script, which I needed to do  when testing #2487.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8279068](https://bugs.openjdk.org/browse/JDK-8279068) needs maintainer approval

### Issue
 * [JDK-8279068](https://bugs.openjdk.org/browse/JDK-8279068): IGV: Update to work with JDK 16 and 17 (**Enhancement** - P4 - Approved)

### Reviewers
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2488/head:pull/2488` \
`$ git checkout pull/2488`

Update a local copy of the PR: \
`$ git checkout pull/2488` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2488/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2488`

View PR using the GUI difftool: \
`$ git pr show -t 2488`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2488.diff">https://git.openjdk.org/jdk17u-dev/pull/2488.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2488#issuecomment-2125150373)

### CODE REVIEW

**Comment by fitzsim** [comment]
/approval request I tested this backport on `Windows` too (with #2487 applied), and `IdealGraphViewer` works.

**Review by gnu-andrew — APPROVED** [review]
Confirmed clean.

**Comment by fitzsim** [comment]
> Confirmed clean.

Thank you for reviewing.

**Pull request closed without merging**
