### PR TITLE
8327474: Review use of java.io.tmpdir in jdk tests

### PR DESCRIPTION
**Pull request by sendaoYan**
Hi all,

This pull request contains a backport of commit [af6c5854](https://github.com/openjdk/jdk21u-dev/commit/af6c5854235573a29b6b418e9f759e2564bca63a) from the [openjdk/jdk21u-dev](https://git.openjdk.org/jdk21u-dev) repository.

The commit being backported was authored by Goetz Lindenmaier on 22 Apr 2024 and had no reviewers.

The backport not clean because jdk17u-dev doesn't have `test/jdk/jdk/jfr/threading/TestManyVirtualThreads.java`, all other files are backported cleanly.
Existing tests should be reviewed to check the usage of java.io.tmpdir. Test fix only, the risk is low.

Additional testing:

- [x] full jtreg tests on linux x64
- [x] full jtreg tests in linux aarch64

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8327474](https://bugs.openjdk.org/browse/JDK-8327474) needs maintainer approval
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8327474](https://bugs.openjdk.org/browse/JDK-8327474): Review use of java.io.tmpdir in jdk tests (**Bug** - P4 - Approved)

### Reviewers
 * [Goetz Lindenmaier](https://openjdk.org/census#goetz) (@GoeLin - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2811/head:pull/2811` \
`$ git checkout pull/2811`

Update a local copy of the PR: \
`$ git checkout pull/2811` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2811/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2811`

View PR using the GUI difftool: \
`$ git pr show -t 2811`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2811.diff">https://git.openjdk.org/jdk17u-dev/pull/2811.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2811#issuecomment-2293785868)

### CODE REVIEW

**Comment by sendaoYan** [comment]
/approval request Existing tests should be reviewed to check the usage of java.io.tmpdir. Test fix only, the risk is low.

**Comment by sendaoYan** [comment]
Hi, can anyone take look tihs PR.

**Review by GoeLin — APPROVED** [review]
Clean besides omission of one file

**Comment by sendaoYan** [comment]
> Clean besides omission of one file

Thanks for the review.

/integrate

**Comment by sendaoYan** [comment]
Thanks for the sponsor.

**Pull request closed without merging**
