### PR TITLE
8285497: Add system property for Java SE specification maintenance version

### PR DESCRIPTION
**Pull request by justin-curtis-lu**
Please review this PR which is a backport of https://github.com/openjdk/jdk17u-ri/commit/c2c9e7fb8c857e40bc43b4053c2633825d4fb68e
This change adds the `"java.specification.maintenance.version"` system property with a value of 1.
Associated GHA run: https://github.com/justin-curtis-lu/jdk17u-dev/actions/runs/9553139534

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8330418](https://bugs.openjdk.org/browse/JDK-8330418) to be approved
- [x] [JDK-8285497](https://bugs.openjdk.org/browse/JDK-8285497) needs maintainer approval

### Issues
 * [JDK-8285497](https://bugs.openjdk.org/browse/JDK-8285497): Add system property for Java SE specification maintenance version (**Enhancement** - P4 - Approved)
 * [JDK-8330418](https://bugs.openjdk.org/browse/JDK-8330418): Add system property for Java SE specification maintenance version (**CSR**)

### Reviewers
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2598/head:pull/2598` \
`$ git checkout pull/2598`

Update a local copy of the PR: \
`$ git checkout pull/2598` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2598/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2598`

View PR using the GUI difftool: \
`$ git pr show -t 2598`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2598.diff">https://git.openjdk.org/jdk17u-dev/pull/2598.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2598#issuecomment-2174393513)

### CODE REVIEW

**Review by LanceAndersen — APPROVED** [review]

**Review by gnu-andrew — APPROVED** [review]
The copyright header changes are a bit odd, because `java/lang/System.java` is bumped to 2022 but `java/lang/VersionProps.java.template` is bumped to 2024. However, I think this is because the former matches the original 19u patch (as does `PolicyFile.java` which doesn't need bumping here as it's already 2023), while the `VersionProps.java.template` is a new change unique to 17 as it sets us to MR1.

So ok with me.

**Comment by gnu-andrew** [comment]
> @gnu-andrew 8285497: There is no maintainer approval request for this issue.

Ah, right.
@justin-curtis-lu this won't move forward unless you request approval.

**Comment by justin-curtis-lu** [comment]
@gnu-andrew, thanks for the approval! (I am waiting to request maintainer approval until closer to our target date of integration, which is still some time away. Hope that is OK)

**Comment by MBaesken** [comment]
Hi Justin, do you have an estimate when you want to request approval ?
Would next week be fine?

**Comment by justin-curtis-lu** [comment]
Hi @MBaesken,

I plan on requesting approval sometime later in next week.

**Comment by justin-curtis-lu** [comment]
/approval request Backporting the addition of the "java.specification.maintenance.version" system property with a value of 1. (This has already been integrated in jdk17u-ri for JSR392).

**Review by irisclark — APPROVED** [review]
Changes as expected for JSR 392 MR 1 support.

**Pull request closed without merging**
