### PR TITLE
8315362: NMT: summary diff reports threads count incorrectly

### PR DESCRIPTION
**Pull request by zer0chance**
---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8315362](https://bugs.openjdk.org/browse/JDK-8315362) needs maintainer approval

### Issue
 * [JDK-8315362](https://bugs.openjdk.org/browse/JDK-8315362): NMT: summary diff reports threads count incorrectly (**Bug** - P4 - Approved)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**) ⚠️ Review applies to [fbe0e219](https://git.openjdk.org/jdk17u-dev/pull/2084/files/fbe0e219e645a2f4dd5f6b5a4f2e37ca4ebaa884)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2084/head:pull/2084` \
`$ git checkout pull/2084`

Update a local copy of the PR: \
`$ git checkout pull/2084` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2084/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2084`

View PR using the GUI difftool: \
`$ git pr show -t 2084`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2084.diff">https://git.openjdk.org/jdk17u-dev/pull/2084.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2084#issuecomment-1870173301)

### CODE REVIEW

**Comment by zer0chance** [comment]
Adding comment to keep this PR alive. @GoeLin do I need to do anything else to get your approval on this?

**Comment by TheRealMDoerr** [comment]
This PR shouldn't differ from the 21u version: https://github.com/openjdk/jdk21u/commit/31c759dd7ef69449e225c3e656d8f522e1124852
I currently see the following diffs:
```diff
< +  _thread_count ++;
---
> +  _thread_count++;
```
```diff
< +        output.shouldContain("Baseline succeeded");
---
> +        output.shouldContain("Baseline taken");
```

**Comment by zer0chance** [comment]
> This PR shouldn't differ from the 21u version: [openjdk/jdk21u@31c759d](https://github.com/openjdk/jdk21u/commit/31c759dd7ef69449e225c3e656d8f522e1124852) I currently see the following diffs:
> 
> ```diff
> < +  _thread_count ++;
> ---
> > +  _thread_count++;
> ```
> 
> ```diff
> < +        output.shouldContain("Baseline succeeded");
> ---
> > +        output.shouldContain("Baseline taken");
> ```

For _thread_count is a good catch, but we need to modify the test like this because JDK-8289182 was not backported to the JDK 17 and `jcmd VM.native_memory baseline` outputs `Baseline succeeded` not `Baseline taken`

**Review by TheRealMDoerr — APPROVED** [review]
Ok. LGTM.

**Comment by TheRealMDoerr** [comment]
Should be adapted if https://github.com/openjdk/jdk17u-dev/pull/2415 gets approved and integrated.

**Comment by zer0chance** [comment]
Thank you @TheRealMDoerr! Can I please ask you to take a look to the follow up fix backport https://github.com/openjdk/jdk17u-dev/pull/2085?

**Comment by TheRealMDoerr** [comment]
https://github.com/openjdk/jdk17u-dev/pull/2085 is clean and trivial. It doesn't need a review. However, all backports need maintainer approvals (see https://wiki.openjdk.org/display/JDKUpdates/JDK+17u). We typically describe in the approval request the motivation for doing the backport, how risky it is and how we tested it. Having said this, please enable GitHub Actions to get automatic tests running on your PRs.
I have requested approval for https://github.com/openjdk/jdk17u-dev/pull/2415, so that one should get integrated first and this one become a clean backport of the JDK 21 version.

**Comment by TheRealMDoerr** [comment]
Both PRs got maintainer approval. Please change to "Baseline taken" once https://github.com/openjdk/jdk17u-dev/pull/2415 is integrated.

**Comment by zer0chance** [comment]
@TheRealMDoerr test is adjusted

**Comment by TheRealMDoerr** [comment]
Ok, you could have made it clean by naming it "Backport 31c759dd7ef69449e225c3e656d8f522e1124852" which makes it a backport of the JDK 21 version. But, let's ship it!
/sponsor

**Pull request closed without merging**
