### PR TITLE
8307134: Add GTS root CAs

### PR DESCRIPTION
**Pull request by jianglizhou**
Backport to JDK 17u for parity with 17.0.9-oracle.

Merged conflicts and regenerated 'CHECKSUM' in test/jdk/sun/security/lib/cacerts/VerifyCACerts.java.
Verified both test/jdk/security/infra/java/security/cert/CertPathValidator/certification/GoogleCA.java and test/jdk/sun/security/lib/cacerts/VerifyCACerts.java pass with a testing JDK 17u binary.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8307134](https://bugs.openjdk.org/browse/JDK-8307134): Add GTS root CAs

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [069c3662](https://git.openjdk.org/jdk17u-dev/pull/1335/files/069c366273df79dc61dbf8d57540798c1e6b7fa7)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1335/head:pull/1335` \
`$ git checkout pull/1335`

Update a local copy of the PR: \
`$ git checkout pull/1335` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1335/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1335`

View PR using the GUI difftool: \
`$ git pr show -t 1335`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1335.diff">https://git.openjdk.org/jdk17u-dev/pull/1335.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1335#issuecomment-1538874698)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by jianglizhou** [comment]
Thanks for the review.

**Review by gnu-andrew — COMMENTED** [review]
You should only need to update the checksum if JDK-8305975 & JDK-8304760 are applied first. It seems this change was instead altered to work around their absence, but the former is now in both 11u & 17u, and the latter is in 17u too.

**Comment by jianglizhou** [comment]
> You should only need to update the checksum if JDK-8305975 & JDK-8304760 are applied first. It seems this change was instead altered to work around their absence, but the former is now in both 11u & 17u, and the latter is in 17u too.

Yeah, thanks. Merged the PR and refreshed the CHECKSUM in VerifyCACerts.java.

**Pull request closed without merging**
