### PR TITLE
8305403: Shenandoah evacuation workers may deadlock

### PR DESCRIPTION
**Pull request by earthling-amzn**
This is a backport of https://github.com/openjdk/jdk/pull/13309. It was not clean, but the conflict was trivial to resolve.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305403](https://bugs.openjdk.org/browse/JDK-8305403): Shenandoah evacuation workers may deadlock

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to [a7b3a0be](https://git.openjdk.org/jdk17u-dev/pull/1242/files/a7b3a0be7487b449b622681e4244786e1abc720b)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1242/head:pull/1242` \
`$ git checkout pull/1242`

Update a local copy of the PR: \
`$ git checkout pull/1242` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1242/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1242`

View PR using the GUI difftool: \
`$ git pr show -t 1242`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1242.diff">https://git.openjdk.org/jdk17u-dev/pull/1242.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1242#issuecomment-1509366954)

### CODE REVIEW

**Comment by GoeLin** [comment]
Tests are failing. Review missing. Please only label if change is ready. 
Did you do any additional testing?  Say so in JBS issue.

**Comment by earthling-amzn** [comment]
The windows failures are likely due to https://bugs.openjdk.org/browse/JDK-8306543

**Review by shipilev — APPROVED** [review]
The backport looks okay, but we need to wait a bit for this patch to get enough testing in mainline.

**Comment by shipilev** [comment]
Please pull from current master to get Windows GHA fixed and running.

**Pull request closed without merging**
