### PR TITLE
8256844: Make NMT late-initializable

### PR DESCRIPTION
**Pull request by VladimirKempik**
Please review this backport to jdk17u-dev
Doesn't apply clean because of JDK-8280940 backport which introduced the same patch into test_os.cpp

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8256844](https://bugs.openjdk.org/browse/JDK-8256844): Make NMT late-initializable

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/496/head:pull/496` \
`$ git checkout pull/496`

Update a local copy of the PR: \
`$ git checkout pull/496` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/496/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 496`

View PR using the GUI difftool: \
`$ git pr show -t 496`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/496.diff">https://git.openjdk.org/jdk17u-dev/pull/496.diff</a>

</details>

### CODE REVIEW

**Comment by tstuefe** [comment]
I'm all for this and had planned to do this sometime this year, but please be aware that this is a bit larger and needs to be tested thoroughly. So far it has seen the light of customer machines only for JDK18, so probably not too much exposure there.

At the very least we should and will cook this patch for a week or two in our JDk17 CI. Would be nice if you could schedule some tests too.

Cheers, Thomas

**Comment by VladimirKempik** [comment]
> BTW getting NMT to run under IntelliJ was one of the reasons for this patch :)

That is my main objective, Since idea 2022.2 is migrating to jdk17.

**Review by tstuefe — APPROVED** [review]
Test changes are okay. 

I'd like to see some mass tests running though, for some days maybe. I'm worried about the changed pre-init allocation mechanics. This patch has been well tested in 18 and beyond, so I may just be paranoid. Just worry about aspects I did not think to test, like native integration.

One small concern I have is that with this patch, we stop recognizing the old `NMT_LEVEL_<pid>` variable. This needs a patch note somewhere (no clue where, @GoeLin ?).

**Comment by tstuefe** [comment]
Testing showed no problems for several days. Good from my end.

**Comment by VladimirKempik** [comment]
I'll wait a bit more for tests to complete in JB env.

**Comment by VladimirKempik** [comment]
Tests look good in JB infra too

**Pull request closed without merging**
