### PR TITLE
8280890: Cannot use '-Djava.system.class.loader' with class loader in signed JAR

### PR DESCRIPTION
**Pull request by veita**
Backport-of: a0f6f2409ea61ff9ed9dc2e2b46e309c751d456d

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8280890](https://bugs.openjdk.org/browse/JDK-8280890): Cannot use '-Djava.system.class.loader' with class loader in signed JAR

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/947/head:pull/947` \
`$ git checkout pull/947`

Update a local copy of the PR: \
`$ git checkout pull/947` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/947/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 947`

View PR using the GUI difftool: \
`$ git pr show -t 947`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/947.diff">https://git.openjdk.org/jdk17u-dev/pull/947.diff</a>

</details>

### CODE REVIEW

**Comment by veita** [comment]
OCA has been signed and submitted at 2022-12-02. Still under review.

**Comment by veita** [comment]
OCA /signed 2022-12-02

**Comment by jerboaa** [comment]
@veita Please change the PR title to `Backport a0f6f2409ea61ff9ed9dc2e2b46e309c751d456d`. That will help the bots recognize it as a backport and will subsequently change the PR title back to the original bug synopsis. It also seems the tests are missing.

**Comment by veita** [comment]
> It also seems the tests are missing.

https://bugs.openjdk.org/browse/JDK-8280890 seems to cover a slightly different issue than https://bugs.openjdk.org/browse/JDK-8297684. I don't know if the changes in `keytool` are applicable for Java 17. So to be as least invasive as possible I've only backported the parts relevant for the latter issue.

Regarding the test, I could copy the files that were added in 19 to the PR. However, I don't know if they actually test `keytool` or the algorithm constraints, or both.

One last question: Does there exist documentation about how to configure an IDE (preferably Eclipse) to compile the JDK. Currently I don't have a workspace that compiles `test/jdk` without errors. So making changes there is kind of blind flying.

**Comment by jerboaa** [comment]
@veita Shame this took so long. But this has been fixed with: https://github.com/openjdk/jdk17u/commit/0ab310eafb4b1225c7db19f7a3d1d4620ee5c7df (should be in 17.0.6) in January. Feel free to verify with a nightly build once available.

This PR should be closed.

**Comment by veita** [comment]
Great. Thank you!

**Comment by veita** [comment]
Verified. We could not reproduce the bug with the latest nightly build.

**Pull request closed without merging**
