### PR TITLE
8233725: ProcessTools.startProcess() has output issues when using an OutputAnalyzer at the same time

### PR DESCRIPTION
**Pull request by elifaslan1**
Clean backport to fix ProcessTools.startProcess() bug.

See original PR explanation [here](https://github.com/openjdk/jdk/pull/13594)

I need this backport to be merged to able to complete [this](https://github.com/openjdk/jdk17u-dev/pull/2339) backport request.

Additional testing: macos-x86_64-server-release tier2

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8233725](https://bugs.openjdk.org/browse/JDK-8233725) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8306946](https://bugs.openjdk.org/browse/JDK-8306946) needs maintainer approval
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8233725](https://bugs.openjdk.org/browse/JDK-8233725): ProcessTools.startProcess() has output issues when using an OutputAnalyzer at the same time (**Bug** - P4 - Approved)
 * [JDK-8306946](https://bugs.openjdk.org/browse/JDK-8306946): jdk/test/lib/process/ProcessToolsStartProcessTest.java fails with "wrong number of lines in OutputAnalyzer output" (**Bug** - P3 - Approved)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2456/head:pull/2456` \
`$ git checkout pull/2456`

Update a local copy of the PR: \
`$ git checkout pull/2456` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2456/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2456`

View PR using the GUI difftool: \
`$ git pr show -t 2456`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2456.diff">https://git.openjdk.org/jdk17u-dev/pull/2456.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2456#issuecomment-2103015788)

### CODE REVIEW

**Comment by elifaslan1** [comment]
/approval JDK-8233725 request “Clean backport. Fix ProcessTools.startProcess() regression. GHA tested and ran tier2 tests additionally. This backport is required for JDK-8325567 to be backported to 17 since this bugfix is missing.

**Comment by shipilev** [comment]
There is a recorded followup for this change: [JDK-8306946](https://bugs.openjdk.org/browse/JDK-8306946) -- do we need to add it here?

**Comment by elifaslan1** [comment]
Yes, Jspawnhelper test passes when I apply regarding commit. I ll add the issue here as well

**Comment by elifaslan1** [comment]
/approval JDK-8306946 request “Clean backport. This backport is to address jdk/test/lib/process ProcessToolsStartProcessTest.java fails with "wrong number of lines in OutputAnalyzer output. GHA tested and  JspawnhelperWarnings test passes with this change added.

**Review by shipilev — APPROVED** [review]

**Comment by TheRealMDoerr** [comment]
This backport causes test errors: https://bugs.openjdk.org/browse/JDK-8333698

**Pull request closed without merging**
