### PR TITLE
8299482: Remove metaprogramming/isIntegral.hpp

### PR DESCRIPTION
**Pull request by gdams**
prerequisite to bumping googletest to 1.13.0

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8299482](https://bugs.openjdk.org/browse/JDK-8299482) needs maintainer approval

### Issue
 * [JDK-8299482](https://bugs.openjdk.org/browse/JDK-8299482): Remove metaprogramming/isIntegral.hpp (**Enhancement** - P4 - Approved)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**) ⚠️ Review applies to [c1f89c4a](https://git.openjdk.org/jdk17u-dev/pull/2676/files/c1f89c4acaea1c577488709315d5453fe3be3dd1)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2676/head:pull/2676` \
`$ git checkout pull/2676`

Update a local copy of the PR: \
`$ git checkout pull/2676` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2676/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2676`

View PR using the GUI difftool: \
`$ git pr show -t 2676`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2676.diff">https://git.openjdk.org/jdk17u-dev/pull/2676.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2676#issuecomment-2210664333)

### CODE REVIEW

**Review by MBaesken — APPROVED** [review]

**Comment by gdams** [comment]
/approval request Applies cleanly other than the deleted file (src/hotspot/share/metaprogramming/isIntegral.hpp) containing some extra commits, Low risk, required as part of the macOS/Xcode upgrade

**Comment by jerboaa** [comment]
@gdams Please restart GHA testing on macos. It looks like the current run got cancelled due to no available executors.

**Comment by gdams** [comment]
/approval request Applies cleanly, Low risk, required as part of the macOS/Xcode upgrade

**Pull request closed without merging**
