### PR TITLE
8289798: Update to use jtreg 7

### PR DESCRIPTION
**Pull request by GoeLin**
I want to backport this on the path to jtreg 7.2.

I had to move the edit of lib-tests.m4 to toolchain.m4

All the others I resolved because we skipped the step to 6.1.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8289798](https://bugs.openjdk.org/browse/JDK-8289798): Update to use jtreg 7 (**Enhancement** - P3)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1595/head:pull/1595` \
`$ git checkout pull/1595`

Update a local copy of the PR: \
`$ git checkout pull/1595` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1595/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1595`

View PR using the GUI difftool: \
`$ git pr show -t 1595`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1595.diff">https://git.openjdk.org/jdk17u-dev/pull/1595.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1595#issuecomment-1640207753)

### CODE REVIEW

**Comment by GoeLin** [comment]
GHA: broken. something wrong with locale. need to fix.

**Review by phohensee — CHANGES_REQUESTED** [review]
jib-profiles.js line 209 looks like a typo. JTeport s/b JTreport.

**Comment by shipilev** [comment]
Hey @GoeLin, we need to get jtreg updates in 17u :) Have you got any luck with figuring out the locale problem? Do you have time to work on it? Would you like me to try this separately?

**Comment by gnu-andrew** [comment]
Failures are in this block of javadoc tests:

[jdk/javadoc/doclet/testSerialVersionUID/TestSerialVersionUID](https://github.com/GoeLin/jdk17u-dev/actions/runs/5587641173#user-content-jdk_javadoc_doclet_testserialversionuid_testserialversionuid)
    [jdk/javadoc/doclet/testTagMisuse/TestTagMisuse](https://github.com/GoeLin/jdk17u-dev/actions/runs/5587641173#user-content-jdk_javadoc_doclet_testtagmisuse_testtagmisuse)
    [jdk/javadoc/doclet/testThrows/TestThrows](https://github.com/GoeLin/jdk17u-dev/actions/runs/5587641173#user-content-jdk_javadoc_doclet_testthrows_testthrows)
    [jdk/javadoc/doclet/testThrowsHead/TestThrowsHead](https://github.com/GoeLin/jdk17u-dev/actions/runs/5587641173#user-content-jdk_javadoc_doclet_testthrowshead_testthrowshead)
    [jdk/javadoc/doclet/testUnnamedPackage/TestUnnamedPackage](https://github.com/GoeLin/jdk17u-dev/actions/runs/5587641173#user-content-jdk_javadoc_doclet_testunnamedpackage_testunnamedpackage)
    [jdk/javadoc/tool/nonConstExprs/Test](https://github.com/GoeLin/jdk17u-dev/actions/runs/5587641173#user-content-jdk_javadoc_tool_nonconstexprs_test)

Not sure this is worth blocking the whole update, especially now this is blocking a backport (#1670

**Comment by gnu-andrew** [comment]
javadoc seems to be scanning inside the testng provided by jtreg:

~~~
/home/runner/work/jdk17u-dev/jdk17u-dev/jtreg/installed/lib/testng-7.3.0.jar(/Version.java):12: error: unmappable character (0xC3) for encoding US-ASCII
        System.out.println("...\\\\n... TestNG " + getVersionString() + " by C??dric Beust (cedric@beust.com)\\\\n...\\\\n");
~~~

**Comment by lutkerd** [comment]
> Hey @GoeLin, we need to get jtreg updates in 17u :) Have you got any luck with figuring out the locale problem? Do you have time to work on it? Would you like me to try this separately?

I think backporting [8260265: UTF-8 by Default](https://github.com/openjdk/jdk/commit/7fc8540907e8e7483ad5729ea416167810aa8747) is the fix for the locale issues. If that is too much we would need to add `-encoding UTF-8` to the javadoc calls.

**Comment by gnu-andrew** [comment]
> > Hey @GoeLin, we need to get jtreg updates in 17u :) Have you got any luck with figuring out the locale problem? Do you have time to work on it? Would you like me to try this separately?
> 
> I think backporting [8260265: UTF-8 by Default](https://github.com/openjdk/jdk/commit/7fc8540907e8e7483ad5729ea416167810aa8747) is the fix for the locale issues. If that is too much we would need to add `-encoding UTF-8` to the javadoc calls.

That's a JEP implementation (https://bugs.openjdk.org/browse/JDK-8187041) so not suitable for backport. I guess `test/langtools/jdk/javadoc/lib/javadoc/tester/JavadocTester.java` would need to be altered, but it already seems to be setting `UTF-8` unless explicitly told not to:

~~~
        if (docencodingArg == null) {
            if (charsetArg == null) {
                cs = (encodingArg == null) ? "UTF-8" : encodingArg;
            } else {
                cs = charsetArg;
            }
        } else {
            cs = docencodingArg;
~~~

I guess we could try an explicit character set for these test cases. I'm unable to reproduce this locally, so it's hard to assess what's actually going on, and why it is even looking inside the testng JAR in the first place.

**Comment by lutkerd** [comment]
> I guess we could try an explicit character set for these test cases. I'm unable to reproduce this locally, so it's hard to assess what's actually going on, and why it is even looking inside the testng JAR in the first place.

https://github.com/openjdk/jdk17u-dev/pull/1672 sets the encoding and is working for me locally.

**Comment by shipilev** [comment]
This is superseded by https://github.com/openjdk/jdk17u-dev/pull/1712.

**Pull request closed without merging**
