### PR TITLE
8307348: Parallelize heap walk for ObjectCount(AfterGC) JFR event collection

### PR DESCRIPTION
**Pull request by shipilev**
Improves ObjectCount JFR events that take considerable time at GC pause. While the event is still heavy, the parallelization helps to avoid unnecessarily large stalls. 

The backport is not clean, because there are number of contextual differences: `WorkGang`, `WithUpdatedActiveWorkers` and other renames did not happen yet. I had to massage the patch to fit 17u better.

Additional testing:
 - [x] Linux x86_64 fastdebug `jdk/jfr serviceability/sa`
 - [x] Linux x86_64 fastdebug `tier1 tier2 tier3`
 - [x] Linux AArch64 fastdebug `tier1 tier2 tier3`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8307348](https://bugs.openjdk.org/browse/JDK-8307348): Parallelize heap walk for ObjectCount(AfterGC) JFR event collection (**Enhancement** - P4)

### Reviewers
 * [Oli Gillespie](https://openjdk.org/census#ogillespie) (@olivergillespie - no project role)
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1441/head:pull/1441` \
`$ git checkout pull/1441`

Update a local copy of the PR: \
`$ git checkout pull/1441` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1441/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1441`

View PR using the GUI difftool: \
`$ git pr show -t 1441`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1441.diff">https://git.openjdk.org/jdk17u-dev/pull/1441.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1441#issuecomment-1592735865)

### CODE REVIEW

**Comment by shipilev** [comment]
@olivergillespie, @hohensee, please look again after the rebase? Should not be different from last review.

**Review by olivergillespie — APPROVED** [review]

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by GoeLin** [comment]
Passes SAP nighlty testing.

**Comment by shipilev** [comment]
Re-checked the sanity test, 1G retained `Integer` objects, Mac M1:

```
# Before
[0.748s][debug][gc,phases  ] GC(4) Report Object Count 197.341ms
[5.511s][debug][gc,phases  ] GC(15) Report Object Count 962.337ms
[10.895s][debug][gc,phases  ] GC(20) Report Object Count 1448.222ms
[23.669s][debug][gc,phases  ] GC(26) Report Object Count 1110.162ms
[27.004s][debug][gc,phases  ] GC(27) Report Object Count 1173.298ms
[40.240s][debug][gc,phases  ] GC(33) Report Object Count 1122.373ms

# After
[0.190s][debug][gc,phases] GC(0) Report Object Count 1.054ms
[0.565s][debug][gc,phases  ] GC(5) Report Object Count 19.203ms
[1.230s][debug][gc,phases  ] GC(16) Report Object Count 82.339ms
[9.187s][debug][gc,phases  ] GC(23) Report Object Count 140.076ms
[11.521s][debug][gc,phases  ] GC(25) Report Object Count 160.064ms
[19.508s][debug][gc,phases  ] GC(30) Report Object Count 139.736ms
[21.547s][debug][gc,phases  ] GC(33) Report Object Count 174.721ms
```

**Comment by shipilev** [comment]
Testing is clean. Push approval is here. Performs as expected.

/integrate

**Pull request closed without merging**
