### PR TITLE
8289643: File descriptor leak with ProcessBuilder.startPipeline

### PR DESCRIPTION
**Pull request by rkmauryaa**
clean backport to fix file descriptor leak with ProcessBuilder.startPipeline. When using ProcessBuilder.startPipeline the pipes (or pipe if only 2 ProcessBuilder instance used) created are never closed.

```
with changes :-
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/jdk/java/lang/ProcessBuilder/PipelineLeaksFD.java
                                                         1     1     0     0   
==============================
TEST SUCCESS


without changes :-
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/jdk/java/lang/ProcessBuilder/PipelineLeaksFD.java
                                                         1     0     1     0 
==============================
TEST FAILURE

with expected output :-
test PipelineLeaksFD.checkForLeaks(java.util.ImmutableCollections$ListN@44d1a216): failure
java.lang.AssertionError: More or fewer pipes than expected
...
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8290885](https://bugs.openjdk.org/browse/JDK-8290885) needs maintainer approval
- [x] [JDK-8289643](https://bugs.openjdk.org/browse/JDK-8289643) needs maintainer approval

### Issues
 * [JDK-8289643](https://bugs.openjdk.org/browse/JDK-8289643): File descriptor leak with ProcessBuilder.startPipeline (**Bug** - P4 - Approved)
 * [JDK-8290885](https://bugs.openjdk.org/browse/JDK-8290885): java/lang/ProcessBuilder/PipelineLeaksFD.java fail: More or fewer pipes than expected (**Bug** - P4 - Approved)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2462/head:pull/2462` \
`$ git checkout pull/2462`

Update a local copy of the PR: \
`$ git checkout pull/2462` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2462/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2462`

View PR using the GUI difftool: \
`$ git pr show -t 2462`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2462.diff">https://git.openjdk.org/jdk17u-dev/pull/2462.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2462#issuecomment-2126872365)

### CODE REVIEW

**Comment by rkmauryaa** [comment]
/approval request Between the launching of each Process, the file descriptor for the output of the previous stage was being kept open, now we `close` that FD after it has been used as the input for the next Process. New regression test added as part of the backport fails without the fix, and passes with it (output is at the top of this thread in PR body).

**Comment by rkmauryaa** [comment]
unclean backport of commit 226b8e680a82096b3d268703872d30182c10e326 which fixes intermittent failures observed for the newly added test. Changes in `test/jdk/ProblemList-Xcomp.txt` were causing conflicts but they are not needed with this new backport as addition and removal of problem-list entry is a no-op change and file contents remains unchanged.

Ran test again :
```
with changes :-
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/jdk/java/lang/ProcessBuilder/PipelineLeaksFD.java
                                                         1     1     0     0   
==============================
TEST SUCCESS


without changes :-
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/jdk/java/lang/ProcessBuilder/PipelineLeaksFD.java
                                                         1     0     1     0 
==============================
TEST FAILURE

with expected output :-
test PipelineLeaksFD.checkForLeaks(java.util.ImmutableCollections$ListN@44d1a216): failure
java.lang.AssertionError: More or fewer pipes than expected
...
```

**Comment by shipilev** [comment]
You also need to say `/issue add JDK-8290885` to record this PR fixes that additional issue as well.

**Comment by shipilev** [comment]
...and now also `/approval 8290885 request <the fix request text goes here>` for approval for that one.

**Comment by rkmauryaa** [comment]
/approval 8290885 request Backported commit `226b8e680a82096b3d268703872d30182c10e326` to fix intermittent failures of the newly added test caused because pipelines did not explicitly use or close the stderr streams of each stream except the last and relied on GC cycles which eventually closes them when they are not referenced.

**Review by shipilev — APPROVED** [review]
Looks fine. Wait for maintainer approval, and then I can sponsor.

**Pull request closed without merging**
