### PR TITLE
8242181: [Linux] Show source information when printing native stack traces in hs_err files

### PR DESCRIPTION
**Pull request by ashu-mehra**
Mostly a clean backport other than copyright year changes.

Tested with tier1 and tier2.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [ ] [JDK-8242181](https://bugs.openjdk.org/browse/JDK-8242181) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8242181](https://bugs.openjdk.org/browse/JDK-8242181): [Linux] Show source information when printing native stack traces in hs_err files (**Enhancement** - P4 - Rejected)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2021/head:pull/2021` \
`$ git checkout pull/2021`

Update a local copy of the PR: \
`$ git checkout pull/2021` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2021/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2021`

View PR using the GUI difftool: \
`$ git pr show -t 2021`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2021.diff">https://git.openjdk.org/jdk17u-dev/pull/2021.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2021#issuecomment-1841883658)

### CODE REVIEW

**Review by phohensee — CHANGES_REQUESTED** [review]
The copyright dates should be the same as in the original commit, so please revert the change from 2022 to 2023. I'd expect the result to be a clean backport.

**Comment by ashu-mehra** [comment]
> The copyright dates should be the same as in the original commit, 

I didn't know copyright needs to be preserved. I have reverted those changes.

**Review by phohensee — APPROVED** [review]
And it's clean now. :)

**Review by phohensee — APPROVED** [review]

**Comment by ashu-mehra** [comment]
hmm the new test `runtime/ErrorHandling/TestDwarf.java` added by this patch is failing on linux-x86

```
[dwarf] ##### Find filename and line number for offset 0x00086071 in library /lib32/libc.so.6 #####
[dwarf] Failed to load DWARF file for library /lib32/libc.so.6 or find DWARF sections directly inside it.
#
# Compiler replay data is saved as:
# /home/runner/work/jdk17u-dev/jdk17u-dev/build/run-test-prebuilt/test-support/jtreg_test_hotspot_jtreg_tier1_runtime/scratch/0/replay_pid4875.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#

hs_err_file: hs_err_pid4875.log
STDERR:
java.lang.RuntimeException: Must find library in "C  [libc.so.6+0x86071]": expected true, was false
	at jdk.test.lib.Asserts.fail(Asserts.java:594)
	at jdk.test.lib.Asserts.assertTrue(Asserts.java:486)
	at TestDwarf.checkNoSourceLine(TestDwarf.java:181)
	at TestDwarf.runAndCheck(TestDwarf.java:153)
	at TestDwarf.test(TestDwarf.java:101)
	at TestDwarf.main(TestDwarf.java:91)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:[568](https://github.com/ashu-mehra/jdk17u-dev/actions/runs/7133685893/job/19427620333#step:9:569))
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

This is same as https://bugs.openjdk.org/browse/JDK-8293201 which would also need to be backported.

**Comment by phohensee** [comment]
Then it would be good if you could backport [JDK-8293201](https://bugs.openjdk.org/browse/JDK-8293201).

**Comment by ashu-mehra** [comment]
> Then it would be good if you could backport [JDK-8293201](https://bugs.openjdk.org/browse/JDK-8293201)

Yup, that's the plan. Along with this, there are other bugs associated with 8242181 which also need to be backported.

**Comment by ashu-mehra** [comment]
Closing this as it is not worth the risk considering the number of follow-up issues and testing required (see the[ JBS comment](https://bugs.openjdk.org/browse/JDK-8242181?focusedId=14634547&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14634547))

**Pull request closed without merging**
