### PR TITLE
8296812: sprintf is deprecated in Xcode 14

### PR DESCRIPTION
**Pull request by elifaslan1**
https://developer.apple.com/news/?id=y5mjxqmn

Starting November 1, 2023, the Apple notary service will no longer accept uploads from altool or Xcode 13 or earlier. 

This is not a clean backport and this pull request contains a backport of the closed bug [JDK-8296812](https://bugs.openjdk.org/browse/JDK-8296812) commit [f1522c648c2e](https://github.com/openjdk/jdk/commit/478ef389dc3767edfbe21d10a7f7f1522c648c2e).

Conflicts includes:

-  whitespace conflicts on src/hotspot/share/utilities/utf8.cpp

-  missing src/hotspot/share/jfr/support/jfrSymbolTable.cpp 

-  context difference on src/hotspot/cpu/aarch64/vm_version_aarch64.cpp

The sprintf is deprecated in Xcode 14 and the use of it causing building failure. The build could pass if warnings are disabled for codes that use sprintf method. For the long run, the sprintf could be replaced with snprintf. This patch is trying to check if snprintf could be used.

Testing:

GHA tested.
Successfull tier1,tier2,tier3 and jck tests for linux platforms.
Successfull tier1 and tier2 for windows.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] [JDK-8296812](https://bugs.openjdk.org/browse/JDK-8296812) needs maintainer approval

### Issue
 * [JDK-8296812](https://bugs.openjdk.org/browse/JDK-8296812): sprintf is deprecated in Xcode 14 (**Bug** - P3)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1930/head:pull/1930` \
`$ git checkout pull/1930`

Update a local copy of the PR: \
`$ git checkout pull/1930` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1930/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1930`

View PR using the GUI difftool: \
`$ git pr show -t 1930`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1930.diff">https://git.openjdk.org/jdk17u-dev/pull/1930.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1930#issuecomment-1783175603)

### CODE REVIEW

**Comment by elifaslan1** [comment]
https://developer.apple.com/news/?id=y5mjxqmn

Starting November 1, 2023, the Apple notary service will no longer accept uploads from altool or Xcode 13 or earlier.

**Comment by GoeLin** [comment]
Hi @elifaslan1, please first get a review before you label for approval. Also, be a bit more elaborate in the fix request message, see also the instructions in . All test after "request" will be copied into the JBS comment.https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix

**Comment by elifaslan1** [comment]
@shipilev could you please review this PR. TIA

**Comment by shipilev** [comment]
Sure, I will try to take a look at this.

**Comment by ysramakrishna** [comment]
I don't see the changes for the gtest covered in https://github.com/openjdk/jdk/pull/11793/files

There might be others. You could confirm by running a `find` and `grep` for `sprintf(` over the repo to ensure you got them all.

Note that https://bugs.openjdk.org/browse/JDK-8299635 has a couple of linked tickets in which further changes were made by @XueleiFan. Would be good for @XueleiFan to also do a review.

You could also do the build on osx, then run a symbol check over all of the `.so's` in the build image to ensure that there are no remaining references to the deprecated method.

**Review by ysramakrishna — COMMENTED** [review]
See previous comment in conversation.

**Comment by zzambers** [comment]
It would be nice to have this one finished, as macos-11 seems to [have been dropped in GHA](https://bugs.openjdk.org/browse/JDK-8318039?focusedId=14686025&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14686025). Sprintf fixes are required by [JDK-8318039](https://bugs.openjdk.org/browse/JDK-8318039) (GHA: Bump macOS and Xcode versions).

**Comment by jerboaa** [comment]
There is a new PR: https://github.com/openjdk/jdk17u-dev/pull/2662

**Pull request closed without merging**
