### PR TITLE
8287491: compiler/jvmci/errors/TestInvalidDebugInfo.java fails new assert:  assert((uint)t < T_CONFLICT + 1) failed: invalid type #

### PR DESCRIPTION
**Pull request by lutkerd**
Backporting followup fix to [JDK-8286562](https://bugs.openjdk.org/browse/JDK-8286562) GCC 12 reports some compiler warnings

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8287491](https://bugs.openjdk.org/browse/JDK-8287491): compiler/jvmci/errors/TestInvalidDebugInfo.java fails new assert:  assert((uint)t < T_CONFLICT + 1) failed: invalid type #

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/1090/head:pull/1090` \
`$ git checkout pull/1090`

Update a local copy of the PR: \
`$ git checkout pull/1090` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/1090/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1090`

View PR using the GUI difftool: \
`$ git pr show -t 1090`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1090.diff">https://git.openjdk.org/jdk17u-dev/pull/1090.diff</a>

</details>

### CODE REVIEW

**Comment by dougxc** [comment]
I would suggest also backporting https://bugs.openjdk.org/browse/JDK-8293691 to fix a problem introduced by JDK-8287491.

**Comment by lutkerd** [comment]
> I would suggest also backporting https://bugs.openjdk.org/browse/JDK-8293691 to fix a problem introduced by JDK-8287491.

Thanks, I wasn't sure if that was a required backport or a correctness fix.

**Review by phohensee — APPROVED** [review]
The only difference between the original commit and backport is that the original commit removes TestInvalidDebugInfo.java from the problem list, but the test isn't on the JDK 17 problem list.

Lgtm.

**Pull request closed without merging**
