### PR TITLE
8317372: Refactor some NumberFormat tests to use JUnit

### PR DESCRIPTION
**Pull request by luchenlin**
I backport this for parity with 17.0.13-oracle.
test/jdk/java/text/Format/NumberFormat/Bug4838107.java has changed by 8316696: Remove the testing base classes: IntlTest and CollatorTest
test/jdk/java/text/Format/NumberFormat/Bug8132125.java has changed by 8283698: Refactor Locale constructors used in src/test
test/jdk/java/text/Format/NumberFormat/CurrencyFormat.java has changed by 8283698: Refactor Locale constructors used in src/test and 8301991: Convert l10n properties resource bundles to UTF-8 native
test/jdk/java/text/Format/NumberFormat/TestPeruCurrencyFormat.java has changed by 8283698: Refactor Locale constructors used in src/test

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8317372](https://bugs.openjdk.org/browse/JDK-8317372) needs maintainer approval

### Issue
 * [JDK-8317372](https://bugs.openjdk.org/browse/JDK-8317372): Refactor some NumberFormat tests to use JUnit (**Sub-task** - P4 - Approved)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2628/head:pull/2628` \
`$ git checkout pull/2628`

Update a local copy of the PR: \
`$ git checkout pull/2628` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2628/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2628`

View PR using the GUI difftool: \
`$ git pr show -t 2628`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2628.diff">https://git.openjdk.org/jdk17u-dev/pull/2628.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2628#issuecomment-2186061179)

### CODE REVIEW

**Comment by TheRealMDoerr** [comment]
Please describe your changes.

**Comment by luchenlin** [comment]
> Please describe your changes.
Hi @TheRealMDoerr 
it's added, thanks.

**Review by TheRealMDoerr — COMMENTED** [review]
You forgot to mention the `@run junit/othervm` changes. But, ok. LGTM. I only found one minor nit.

**Review by TheRealMDoerr — APPROVED** [review]
Thanks!

**Pull request closed without merging**
