### PR TITLE
8278766: Enable OpenJDK build support for reproducible jars and jmods using --date

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
This PR is to enable usage of the --date option for OpenJDK build to enable reproducible build jars & jmods.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8278766](https://bugs.openjdk.java.net/browse/JDK-8278766): Enable OpenJDK build support for reproducible jars and jmods using --date

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17u-dev pull/246/head:pull/246` \
`$ git checkout pull/246`

Update a local copy of the PR: \
`$ git checkout pull/246` \
`$ git pull https://git.openjdk.java.net/jdk17u-dev pull/246/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 246`

View PR using the GUI difftool: \
`$ git pr show -t 246`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17u-dev/pull/246.diff">https://git.openjdk.java.net/jdk17u-dev/pull/246.diff</a>

</details>

### CODE REVIEW

**Comment by jerboaa** [comment]
Has a CSR for this been filed? I see https://bugs.openjdk.java.net/browse/JDK-8277755 was the original in HEAD. There should be an approved CSR targeting JDK 17 before integrating this.

**Comment by andrew-m-leonard** [comment]
> Has a CSR for this been filed? I see https://bugs.openjdk.java.net/browse/JDK-8277755 was the original in HEAD. There should be an approved CSR targeting JDK 17 before integrating this.

@jerboaa JDK-8277755 is a different issue, which is actually already in jdk17u (https://github.com/openjdk/jdk17u/commit/761e2989e459b9403a5ee3c5f3c776838637f8ac).
This PR is backport of https://github.com/openjdk/jdk/pull/6878 bug https://bugs.openjdk.java.net/browse/JDK-8278766.

**Comment by jerboaa** [comment]
> JDK-8277755 is a different issue, which is actually already in jdk17u ([openjdk/jdk17u@761e298](https://github.com/openjdk/jdk17u/commit/761e2989e459b9403a5ee3c5f3c776838637f8ac)). This PR is backport of [openjdk/jdk#6878](https://github.com/openjdk/jdk/pull/6878) bug https://bugs.openjdk.java.net/browse/JDK-8278766.

Ahh, ok then. Sorry for the noise.

**Comment by andrew-m-leonard** [comment]
Testing all good with various reproducible options --with-source-date, and with boot jdks with --date support and ones that don't.

**Comment by andrew-m-leonard** [comment]
thank you Martin  @TheRealMDoerr

**Pull request closed without merging**
