### PR TITLE
8282947: JFR: Dump on shutdown live-locks in some conditions

### PR DESCRIPTION
**Pull request by judovana**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8282947](https://bugs.openjdk.org/browse/JDK-8282947): JFR: Dump on shutdown live-locks in some conditions

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/555/head:pull/555` \
`$ git checkout pull/555`

Update a local copy of the PR: \
`$ git checkout pull/555` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/555/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 555`

View PR using the GUI difftool: \
`$ git pr show -t 555`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/555.diff">https://git.openjdk.org/jdk17u-dev/pull/555.diff</a>

</details>

### CODE REVIEW

**Comment by judovana** [comment]
ping please?

**Comment by RealCLanger** [comment]
> ping please?

The backport is clean and tests are green. Maintainers didn't become aware of it because no jdk17u-fix-request flag was set in JBS. As I saw you already added aFix Request comment, I have added both, jdk17u-fix-request and jdk17u-fix-yes. So you can consider it approved and this PR is ready to be integrated.

**Comment by judovana** [comment]
tyvm!

**Comment by judovana** [comment]
Looking for sponsor, if you would be so kind. TYVM!

**Comment by judovana** [comment]
TYVM!

**Pull request closed without merging**
