### PR TITLE
8297211: Expensive fillInStackTrace operation in HttpURLConnection.getOutputStream0 when no content-length in response

### PR DESCRIPTION
**Pull request by benty-amzn**
Backporting to 17 for improved performance.
Backport is clean.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297211](https://bugs.openjdk.org/browse/JDK-8297211): Expensive fillInStackTrace operation in HttpURLConnection.getOutputStream0 when no content-length in response

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/918/head:pull/918` \
`$ git checkout pull/918`

Update a local copy of the PR: \
`$ git checkout pull/918` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/918/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 918`

View PR using the GUI difftool: \
`$ git pr show -t 918`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/918.diff">https://git.openjdk.org/jdk17u-dev/pull/918.diff</a>

</details>

### CODE REVIEW

**Comment by RealCLanger** [comment]
@benty-amzn, could you please enable GHA testing?

**Comment by benty-amzn** [comment]
GHA tests are now enabled and passing

**Comment by benty-amzn** [comment]
Rebased on current master to try to get tests to run - they are enabled but didn't run for some reason

**Pull request closed without merging**
