### PR TITLE
8318696: Do not use LFS64 symbols on Linux

### PR DESCRIPTION
**Pull request by MBaesken**
Backport 8318696 from jdk21u-dev

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8318696](https://bugs.openjdk.org/browse/JDK-8318696) needs maintainer approval

### Issue
 * [JDK-8318696](https://bugs.openjdk.org/browse/JDK-8318696): Do not use LFS64 symbols on Linux (**Bug** - P4 - Approved)

### Reviewers
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2173/head:pull/2173` \
`$ git checkout pull/2173`

Update a local copy of the PR: \
`$ git checkout pull/2173` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2173/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2173`

View PR using the GUI difftool: \
`$ git pr show -t 2173`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2173.diff">https://git.openjdk.org/jdk17u-dev/pull/2173.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2173#issuecomment-1908200050)

### CODE REVIEW

**Comment by MBaesken** [comment]
had to add changes to os::available (os_linux.cpp)

**Comment by MBaesken** [comment]
There were some issues with COPYRIGHT headers, and also diffs in the stride.
Additionally , I addressed   `os::available`  (os_linux.cpp) where also some calls needed to be changed.

**Comment by gnu-andrew** [comment]
@MBaesken are you still wanting to push forward with this? If so, I can review. It would be nice to finally get this fixed in older releases, at least on the HotSpot side (the JDK patch [JDK-8324539](https://bugs.openjdk.org/browse/JDK-8324539) looks a bit more involved). We've hit issues with this recently on 8u which were hard to reproduce.

**Comment by MBaesken** [comment]
> @MBaesken are you still wanting to push forward with this?

Yeah let's do that for jdk17 at least.

**Review by gnu-andrew — COMMENTED** [review]
Thanks for re-opening this.

Copyright header adaptations look fine. `os::available` was removed by [JDK-8285307](https://bugs.openjdk.org/browse/JDK-8285307) in later JDKs, which is why it isn't in the original patch and needs to be fixed in the backport.

The only change I'm curious about is in `os::current_file_offset` & `os::seek_to_file_offset` as they retain `off64_t` casts. The 21u version uses `off_t`. Was this deliberate or just missed?

**Comment by gnu-andrew** [comment]
Also, I presume we'll also need [JDK-8324753](https://bugs.openjdk.org/browse/JDK-8324753) for AIX as a follow-up?

**Comment by MBaesken** [comment]
> Also, I presume we'll also need [JDK-8324753](https://bugs.openjdk.org/browse/JDK-8324753) for AIX as a follow-up?

Yes I think so .

**Comment by MBaesken** [comment]
>The only change I'm curious about is in os::current_file_offset & os::seek_to_file_offset as they retain off64_t casts. The 21u >version uses off_t. Was this deliberate or just missed?

Hi Andrew, I think we have to use `off_t` here. Thanks for looking into this.

**Review by gnu-andrew — APPROVED** [review]
Thanks. The revised version looks good. Please apply for approval with `/approval request <reason>`

**Comment by MBaesken** [comment]
Thanks for the review !

**Pull request closed without merging**
