### PR TITLE
8284578: Relax InterpreterCodelet stub alignment

### PR DESCRIPTION
**Pull request by dchuyko**
This change improves density of interpreter codelets. I have no intent to backport JDK-8281467 [1] (Allow larger OptoLoopAlignment and CodeEntryAlignment), entire JDK-8283298 [2] (productize CodeCacheSegmentSize) and its related change in stubRoutines.cpp JDK-8282355 [3].

However I suppose that Modification of MethodHandles::generate_adapters() from JDK-8283298 which makes blob size more accurate is related to this fix, so I included it here. JDK-8283298 modifications of TemplateInterpreter::initialize_stub() are overwritten by the changes from the original JDK-8284578 patch.

So this patch consists of
- Original JDK-8284578 altered to be applicable without JDK-8283298 and JDK-8264207 [4] (can be backported afterwards).
- MethodHandles::generate_adapters() and copyrights from JDK-8283298.

Testing: tier1, tier2 on x86 and aarch64 (release)

[0] https://bugs.openjdk.org/browse/JDK-8284578
[1] https://bugs.openjdk.org/browse/JDK-8281467
[2] https://bugs.openjdk.org/browse/JDK-8283298
[3] https://bugs.openjdk.org/browse/JDK-8282355
[4] https://bugs.openjdk.org/browse/JDK-8264207

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8284578](https://bugs.openjdk.org/browse/JDK-8284578): Relax InterpreterCodelet stub alignment

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [04b6b21a](https://git.openjdk.org/jdk17u-dev/pull/753/files/04b6b21afdd0e7cb2561a7509b8081cb1d795660)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/753/head:pull/753` \
`$ git checkout pull/753`

Update a local copy of the PR: \
`$ git checkout pull/753` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/753/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 753`

View PR using the GUI difftool: \
`$ git pr show -t 753`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/753.diff">https://git.openjdk.org/jdk17u-dev/pull/753.diff</a>

</details>

### CODE REVIEW

**Comment by phohensee** [comment]
Pre-submit test failure looks to be an infrastructure issue.

**Comment by phohensee** [comment]
You've included all but a trivial part of JDK-8283298. Why not backport that first?

**Comment by dchuyko** [comment]
> You've included all but a trivial part of JDK-8283298. Why not backport that first?

The main purpose declared there is making the flag product. If it's ok for 17 as well then no problem. There is also a follow-up for the test JDK-8283229 which is also simple.

**Comment by phohensee** [comment]
No CSR needed originally, and making it a product flag won't invalidate existing command lines that use it, so should be ok for 17.

**Comment by dchuyko** [comment]
As suggested, the JDK-8283298 is made in 17u first and this backport is re-implemented on top of it (https://github.com/openjdk/jdk17u-dev/commit/fe4819b5eb25e97b459aded9e1ab93586445b301)

**Review by phohensee — APPROVED** [review]
Lgtm.

**Review by phohensee — APPROVED** [review]
Thanks, Dima. Lgtm.

**Comment by dchuyko** [comment]
PPC was mentioned originally as the most impacted platform, however experiments on x86 and aarch64 stopped no performance improvement (interpreter, startup). So the change should be considered as an optional clean-up, closing for now.

**Pull request closed without merging**
