### PR TITLE
8301701: java/net/DatagramSocket/DatagramSocketMulticasting.java should be hardened

### PR DESCRIPTION
**Pull request by GoeLin**
I backport this for parity with 17.0.8-oracle.

I had to resolve the @run command.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8301701](https://bugs.openjdk.org/browse/JDK-8301701) needs maintainer approval

### Issue
 * [JDK-8301701](https://bugs.openjdk.org/browse/JDK-8301701): java/net/DatagramSocket/DatagramSocketMulticasting.java should be hardened (**Bug** - P4 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1433/head:pull/1433` \
`$ git checkout pull/1433`

Update a local copy of the PR: \
`$ git checkout pull/1433` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1433/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1433`

View PR using the GUI difftool: \
`$ git pr show -t 1433`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1433.diff">https://git.openjdk.org/jdk17u-dev/pull/1433.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1433#issuecomment-1589877706)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by GoeLin** [comment]
This requires jtreg 7, or I need to undo the junit assert calls.  Will wait for jtreg 7.

**Pull request closed without merging**
