### PR TITLE
8280705: Parallel: Full gc mark stack draining should prefer to make work available to other threads

### PR DESCRIPTION
**Pull request by shipilev**
Clean backport to match what G1 is also doing. The change was in mainline for more than a year without related issues.

Additional testing:
 - [x] Linux x86_64 fastdebug `tier1` with `-XX:+UseParallelGC`
 - [x] Linux x86_64 fastdebug `tier2` with `-XX:+UseParallelGC`
 - [x] Linux x86_64 fastdebug `tier3` with `-XX:+UseParallelGC`

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] [JDK-8280705](https://bugs.openjdk.org/browse/JDK-8280705) needs maintainer approval

### Issue
 * [JDK-8280705](https://bugs.openjdk.org/browse/JDK-8280705): Parallel: Full gc mark stack draining should prefer to make work available to other threads (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1521/head:pull/1521` \
`$ git checkout pull/1521`

Update a local copy of the PR: \
`$ git checkout pull/1521` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1521/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1521`

View PR using the GUI difftool: \
`$ git pr show -t 1521`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1521.diff">https://git.openjdk.org/jdk17u-dev/pull/1521.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1521#issuecomment-1614448476)

### CODE REVIEW

**Comment by shipilev** [comment]
Hm, this actually regresses Parallel Full GC performance on some workloads. For example, `dotty`:

```
% java -XX:+UseParallelGC -Xmx1g -Xms1g -Xlog:gc -jar ../renaissance-mit-0.14.2.jar dotty 2>&1 | grep "Pause Full"

# Baseline
...
[62.287s][info][gc] GC(76) Pause Full (System.gc()) 22M->22M(981M) 64.464ms
[63.693s][info][gc] GC(78) Pause Full (System.gc()) 22M->22M(981M) 62.254ms
[65.091s][info][gc] GC(80) Pause Full (System.gc()) 22M->22M(981M) 61.213ms
[66.492s][info][gc] GC(82) Pause Full (System.gc()) 22M->22M(981M) 62.152ms
[67.893s][info][gc] GC(84) Pause Full (System.gc()) 22M->22M(981M) 61.495ms
[69.292s][info][gc] GC(86) Pause Full (System.gc()) 22M->22M(981M) 62.536ms
[70.680s][info][gc] GC(88) Pause Full (System.gc()) 22M->22M(981M) 62.616ms
[72.078s][info][gc] GC(90) Pause Full (System.gc()) 22M->22M(981M) 62.685ms
[73.471s][info][gc] GC(92) Pause Full (System.gc()) 22M->22M(981M) 60.560ms

# 17u with this patch
[63.834s][info][gc] GC(78) Pause Full (System.gc()) 22M->22M(981M) 66.412ms
[65.235s][info][gc] GC(80) Pause Full (System.gc()) 22M->22M(981M) 70.616ms
[66.638s][info][gc] GC(82) Pause Full (System.gc()) 22M->22M(981M) 66.929ms
[68.043s][info][gc] GC(84) Pause Full (System.gc()) 22M->22M(981M) 66.627ms
[69.451s][info][gc] GC(86) Pause Full (System.gc()) 22M->22M(981M) 67.261ms
[70.858s][info][gc] GC(88) Pause Full (System.gc()) 22M->22M(981M) 71.890ms
[72.259s][info][gc] GC(90) Pause Full (System.gc()) 22M->22M(981M) 67.020ms
[73.656s][info][gc] GC(92) Pause Full (System.gc()) 22M->22M(981M) 67.471ms
[75.059s][info][gc] GC(94) Pause Full (System.gc()) 22M->22M(981M) 68.016ms
```

**Comment by shipilev** [comment]
Same with `naive-bayes`:

```
$ build/linux-x86_64-server-release/images/jdk/bin/java -XX:+UseParallelGC -Xmx4g -Xms4g -XX:+AlwaysPreTouch -Xlog:gc -jar ../renaissance-mit-0.14.2.jar naive-bayes 2>&1 | grep "Pause Full"

# Before
[24.500s][info][gc] GC(340) Pause Full (System.gc()) 1373M->1367M(4089M) 90.501ms
[25.173s][info][gc] GC(353) Pause Full (System.gc()) 1373M->1367M(4090M) 92.504ms
[25.844s][info][gc] GC(366) Pause Full (System.gc()) 1373M->1367M(4089M) 93.355ms
[26.518s][info][gc] GC(379) Pause Full (System.gc()) 1373M->1367M(4090M) 91.851ms
[27.215s][info][gc] GC(392) Pause Full (System.gc()) 1373M->1367M(4090M) 91.128ms
[27.900s][info][gc] GC(405) Pause Full (System.gc()) 1373M->1367M(4090M) 90.536ms
[28.570s][info][gc] GC(418) Pause Full (System.gc()) 1373M->1367M(4090M) 92.705ms
[29.247s][info][gc] GC(431) Pause Full (System.gc()) 1373M->1367M(4090M) 91.838ms
[29.926s][info][gc] GC(444) Pause Full (System.gc()) 1373M->1367M(4090M) 92.964ms
[30.599s][info][gc] GC(457) Pause Full (System.gc()) 1373M->1367M(4089M) 91.042ms

# After
[24.654s][info][gc] GC(338) Pause Full (System.gc()) 1373M->1367M(4090M) 105.490ms
[25.349s][info][gc] GC(351) Pause Full (System.gc()) 1373M->1367M(4090M) 106.263ms
[26.046s][info][gc] GC(364) Pause Full (System.gc()) 1373M->1367M(4090M) 106.324ms
[26.748s][info][gc] GC(377) Pause Full (System.gc()) 1373M->1367M(4090M) 106.146ms
[27.448s][info][gc] GC(390) Pause Full (System.gc()) 1373M->1367M(4090M) 108.895ms
[28.143s][info][gc] GC(403) Pause Full (System.gc()) 1373M->1367M(4090M) 107.850ms
[28.861s][info][gc] GC(416) Pause Full (System.gc()) 1373M->1367M(4090M) 106.542ms
[29.550s][info][gc] GC(429) Pause Full (System.gc()) 1373M->1367M(4090M) 109.635ms
[30.233s][info][gc] GC(442) Pause Full (System.gc()) 1373M->1367M(4090M) 107.652ms
[30.922s][info][gc] GC(455) Pause Full (System.gc()) 1374M->1367M(4090M) 108.397ms
```

**Comment by GoeLin** [comment]
Hi @shipilev, 
If you don't want to integrate this please remove the jdk17u-*-request labels.
If you want to integrate it, maybe you want to merge head to rerun the tests before integrating to account for the changes that were done in the meantime.

**Comment by shipilev** [comment]
Yeah, I do not want to integrate at this time. I think this is a performance regression. I kept this PR as the reminder to myself that I need to reproduce this in mainline. I'll remove the tags.

**Pull request closed without merging**
