### PR TITLE
8301998: Update HarfBuzz to 7.0.1

### PR DESCRIPTION
**Pull request by GoeLin**
I backport this for parity with 17.0.8-oracle.

I included 8304295: harfbuzz build fails with GCC 7 after JDK-8301998  right away to 
simplify backporting to 11. 
I had to resolve patching 8304295 as there are more warnings disabled in 17.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8301998](https://bugs.openjdk.org/browse/JDK-8301998): Update HarfBuzz to 7.0.1
 * [JDK-8304295](https://bugs.openjdk.org/browse/JDK-8304295): harfbuzz build fails with GCC 7 after JDK-8301998

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1264/head:pull/1264` \
`$ git checkout pull/1264`

Update a local copy of the PR: \
`$ git checkout pull/1264` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1264/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1264`

View PR using the GUI difftool: \
`$ git pr show -t 1264`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1264.diff">https://git.openjdk.org/jdk17u-dev/pull/1264.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1264#issuecomment-1513473518)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
The change to Awt2Dlibraries.gmk look good to me. The rest of the PR seems to be the Harfbuzz 7.0.1 source code, which I assume is correct.

**Comment by GoeLin** [comment]
Thanks for the review!

**Pull request closed without merging**
