### PR TITLE
8314476: TestJstatdPortAndServer.java failed with "java.rmi.NoSuchObjectException: no such object in table"

### PR DESCRIPTION
**Pull request by sendaoYan**
Hi all,

This pull request contains a backport of commit [1d025070](https://github.com/openjdk/jdk/commit/1d0250709a6ee97f5647edff589761bd9d0b7f4c) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Kevin Walls on 29 Aug 2023 and was reviewed by Mark Sheppard and Serguei Spitsyn.

The change has been verified on commit id `ab84520d73a63601d75e45895663d8216ca20962`, only change the testcase, the risk is low.

Additional testing:

- [x] sun/tools/jstatd/TestJstatdExternalRegistry.java
- [x] sun/tools/jstatd/TestJstatdPort.java
- [x] sun/tools/jstatd/TestJstatdPortAndServer.java
- [x] sun/tools/jstatd/TestJstatdRmiPort.java
- [x] sun/tools/jstatd/TestJstatdDefaults.java
- [x] sun/tools/jstatd/TestJstatdServer.java

Thanks!

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8314476](https://bugs.openjdk.org/browse/JDK-8314476) needs maintainer approval

### Issue
 * [JDK-8314476](https://bugs.openjdk.org/browse/JDK-8314476): TestJstatdPortAndServer.java failed with "java.rmi.NoSuchObjectException: no such object in table" (**Bug** - P4 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2547/head:pull/2547` \
`$ git checkout pull/2547`

Update a local copy of the PR: \
`$ git checkout pull/2547` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2547/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2547`

View PR using the GUI difftool: \
`$ git pr show -t 2547`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2547.diff">https://git.openjdk.org/jdk17u-dev/pull/2547.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2547#issuecomment-2153746599)

### CODE REVIEW

**Comment by sendaoYan** [comment]
Additional test on local:
```
yansendao@j66e07344:[jdk17u-dev]> git cherry-pick 1d0250709a6e
Auto-merging test/jdk/sun/tools/jstatd/JstatdTest.java
[master d9b79e11500] 8314476: TestJstatdPortAndServer.java failed with "java.rmi.NoSuchObjectException: no such object in table"
 Author: Kevin Walls <kevinw@openjdk.org>
 Date: Tue Aug 29 08:54:00 2023 +0000
 1 file changed, 10 insertions(+), 6 deletions(-)
yansendao@j66e07344:[jdk17u-dev]> j -conc:20 @t.txt
~/git/jdk17u-dev/build/linux-x86_64-server-release/images/jdk/bin/java
Directory "tmp" not found: creating
--------------------------------------------------
TEST: sun/tools/jstatd/TestJstatdExternalRegistry.java
TEST RESULT: Passed. Execution successful
--------------------------------------------------
TEST: sun/tools/jstatd/TestJstatdRmiPort.java
TEST RESULT: Passed. Execution successful
--------------------------------------------------
TEST: sun/tools/jstatd/TestJstatdDefaults.java
TEST RESULT: Passed. Execution successful
--------------------------------------------------
TEST: sun/tools/jstatd/TestJstatdServer.java
TEST RESULT: Passed. Execution successful
--------------------------------------------------
TEST: sun/tools/jstatd/TestJstatdPort.java
TEST RESULT: Passed. Execution successful
--------------------------------------------------
TEST: sun/tools/jstatd/TestJstatdPortAndServer.java
TEST RESULT: Passed. Execution successful
--------------------------------------------------
Test results: passed: 6
Results written to /home/yansendao/git/jdk17u-dev/tmp

real    0m46.465s
user    2m19.183s
sys     0m7.845s
```

**Comment by sendaoYan** [comment]
/approval request Clean backport to fix test failure. The change has been verified, only change the testcase, the risk is low.

**Comment by shipilev** [comment]
Hey @sendaoYan -- are you planning to integrate this one?

**Comment by sendaoYan** [comment]
> Hey @sendaoYan -- are you planning to integrate this one?

Yes, please.
/integrate

**Comment by sendaoYan** [comment]
> /sponsor

Thanks for the sponsor.

**Pull request closed without merging**
