### PR TITLE
8300590: [JVMCI] BytecodeFrame.equals is broken

### PR DESCRIPTION
**Pull request by rvansa**
Almost clean, added missing import in separate commit.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8300590](https://bugs.openjdk.org/browse/JDK-8300590): [JVMCI] BytecodeFrame.equals is broken

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/1144/head:pull/1144` \
`$ git checkout pull/1144`

Update a local copy of the PR: \
`$ git checkout pull/1144` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/1144/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1144`

View PR using the GUI difftool: \
`$ git pr show -t 1144`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1144.diff">https://git.openjdk.org/jdk17u-dev/pull/1144.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by rvansa** [comment]
I am not an Author yet and don't have access to JIRA; could I ask someone to comment on my behalf?
```
Fix request (17u):
I backport this as the issue appears in JDK 17, too.
Backport is clean except imports.
I can't fully asses the risk but since this is an internal class the scope should be limited.
```

**Comment by yan-too** [comment]
Added the fix request AND jdk17u-fix-request. Again, please do not issue "integrate" command until the maintainer's jdk17u-fix-yes answer.

**Pull request closed without merging**
