### PR TITLE
8316138: Add GlobalSign 2 TLS root certificates

### PR DESCRIPTION
**Pull request by Delawen**
Backport for https://bugs.openjdk.org/browse/JDK-8316138

Related to https://github.com/openjdk/jdk21u-dev/pull/581

Changes since the original commit: the checksum for the certificates and the folder where the certs are stored.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8316138](https://bugs.openjdk.org/browse/JDK-8316138) needs maintainer approval
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8316138](https://bugs.openjdk.org/browse/JDK-8316138): Add GlobalSign 2 TLS root certificates (**Enhancement** - P3 - Approved)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2479/head:pull/2479` \
`$ git checkout pull/2479`

Update a local copy of the PR: \
`$ git checkout pull/2479` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2479/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2479`

View PR using the GUI difftool: \
`$ git pr show -t 2479`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2479.diff">https://git.openjdk.org/jdk17u-dev/pull/2479.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2479#issuecomment-2117343761)

### CODE REVIEW

**Comment by Delawen** [comment]
@TheRealMDoerr redid #2478 because force pushing does not suit well with the jdk bot :) But here we are.

**Comment by Delawen** [comment]
/approval JDK-8316138 request Fix Request
This is a backport for https://bugs.openjdk.org/browse/JDK-8316138 It includes two new certificates for cacert. The original commit placed them in a different folder, which is not the right one for this JDK version. It also updates the test that checks certificates are in place, updating the checksum.

**Comment by Delawen** [comment]
```
$ make test TEST="test/jdk/sun/security/lib/cacerts/VerifyCACerts.java"
Building target 'test' in configuration 'linux-x86_64-server-release'
Creating jdk image
Creating CDS archive for jdk image
Creating CDS-NOCOOPS archive for jdk image
Test selection 'test/jdk/sun/security/lib/cacerts/VerifyCACerts.java', will run:
* jtreg:test/jdk/sun/security/lib/cacerts/VerifyCACerts.java

Running test 'jtreg:test/jdk/sun/security/lib/cacerts/VerifyCACerts.java'
Passed: sun/security/lib/cacerts/VerifyCACerts.java
Test results: passed: 1
Report written to /home/delawen/git/jdk17u-dev/build/linux-x86_64-server-release/test-results/jtreg_test_jdk_sun_security_lib_cacerts_VerifyCACerts_java/html/report.html
Results written to /home/delawen/git/jdk17u-dev/build/linux-x86_64-server-release/test-support/jtreg_test_jdk_sun_security_lib_cacerts_VerifyCACerts_java
Finished running test 'jtreg:test/jdk/sun/security/lib/cacerts/VerifyCACerts.java'
Test report is stored in build/linux-x86_64-server-release/test-results/jtreg_test_jdk_sun_security_lib_cacerts_VerifyCACerts_java

==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/jdk/sun/security/lib/cacerts/VerifyCACerts.java
                                                         1     1     0     0   
==============================
TEST SUCCESS

Finished building target 'test' in configuration 'linux-x86_64-server-release'
```

**Comment by Delawen** [comment]
@jerboaa Here is the backport of the certificates for JDK17

**Review by TheRealMDoerr — APPROVED** [review]
LGTM. Thanks for backporting it! We want to ship it with 17.0.12.

**Pull request closed without merging**
