### PR TITLE
8291760: PipelineLeaksFD.java still fails: More or fewer pipes than expected

### PR DESCRIPTION
**Pull request by sendaoYan**
Hi all,

This pull request contains a backport of commit [4e457acd](https://github.com/openjdk/jdk/commit/4e457acda09be57dbb49b5c89123bf79bf81f38c) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Roger Riggs on 26 Aug 2022 and was reviewed by Jaikiran Pai and Alan Bateman.

The backport not clean, because the file `test/jdk/ProblemList.txt` can't backport cleanly, and it doesn't need to backport. The file `test/jdk/java/lang/ProcessBuilder/PipelineLeaksFD.java` is backport cleanly.

The change has been verified, only change the testcase, no risk.

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8291760](https://bugs.openjdk.org/browse/JDK-8291760) needs maintainer approval

### Issue
 * [JDK-8291760](https://bugs.openjdk.org/browse/JDK-8291760): PipelineLeaksFD.java still fails: More or fewer pipes than expected (**Bug** - P4 - Approved)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2615/head:pull/2615` \
`$ git checkout pull/2615`

Update a local copy of the PR: \
`$ git checkout pull/2615` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2615/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2615`

View PR using the GUI difftool: \
`$ git pr show -t 2615`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2615.diff">https://git.openjdk.org/jdk17u-dev/pull/2615.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2615#issuecomment-2179639726)

### CODE REVIEW

**Comment by sendaoYan** [comment]
/approval request Partial backport of JDK-8291760 to fixed the intermittent fails, The change has been verified, only change the testcase, no risk.

**Comment by sendaoYan** [comment]
Thanks for the approved.

**Review by jerboaa — APPROVED** [review]
Only change to the JDK 21 version is the ProblemList.txt changes. OK for JDK 17u.

**Comment by sendaoYan** [comment]
Thanks for the review.
/integrate

**Comment by sendaoYan** [comment]
Thanks for the sponsor.

**Pull request closed without merging**
