### PR TITLE
8254711: Add java.security.Provider.getService JFR Event

### PR DESCRIPTION
**Pull request by GoeLin**
I backport this for parity with 17.0.8-oracle.

src/java.base/share/classes/java/security/Provider.java
I had to redo the change for getService().
I basically changed the control flow to only
return at the end and then added the Event
generation before the return.

src/jdk.jfr/share/classes/jdk/jfr/internal/instrument/JDKEvents.java
Resolved three hunks due to context.

test/lib/jdk/test/lib/jfr/EventNames.java
Resolved three hunks due to context.

I added JDK-8294673 JFR: Add SecurityProviderService#threshold to TestActiveSettingEvent.java. Else that test is failing.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8254711](https://bugs.openjdk.org/browse/JDK-8254711): Add java.security.Provider.getService JFR Event
 * [JDK-8294673](https://bugs.openjdk.org/browse/JDK-8294673): JFR: Add SecurityProviderService#threshold to TestActiveSettingEvent.java

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1260/head:pull/1260` \
`$ git checkout pull/1260`

Update a local copy of the PR: \
`$ git checkout pull/1260` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1260/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1260`

View PR using the GUI difftool: \
`$ git pr show -t 1260`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1260.diff">https://git.openjdk.org/jdk17u-dev/pull/1260.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1260#issuecomment-1513342827)

### CODE REVIEW

**Comment by GoeLin** [comment]
Pre-submit failures: 
2xwin:  Run Visual Studio Installer Error: Process completed with exit code 1.
2xlinux: Unable to connect to azure.archive.ubuntu.com
Infra issues, unrelated.

**Comment by MBaesken** [comment]
Hi Götz, regarding Provider.java, do we need the  legacyMap.remove  that can be found in head ?  I do not see it in your coding, but maybe it is not needed in 17 ?

**Review by MBaesken — APPROVED** [review]

**Pull request closed without merging**
