### PR TITLE
8319048: Monitor deflation unlink phase prolongs time to safepoint

### PR DESCRIPTION
**Pull request by shipilev**
Unclean backport to eliminate another safepoint hiccup caused by monitor deflation. The uncleanliness comes mostly from `NULL` vs `nullptr` differences in affected hunks. I chose to accept the new version that uses `nullptr` consistently, even though some `NULL`-s might have been left alone.

I was concerned that we might still have problems with interleaving with end-of-VM monitor deflation. This was one of the minor reasons to do [JDK-8319896](https://bugs.openjdk.org/browse/JDK-8319896), but I see that we only do that in `VMThread` when exiting, so we are not actually at risk here.

Additional testing:
  - [x] Linux x86_64 server fastdebug, `all` tests pass

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8319048](https://bugs.openjdk.org/browse/JDK-8319048) needs maintainer approval

### Issue
 * [JDK-8319048](https://bugs.openjdk.org/browse/JDK-8319048): Monitor deflation unlink phase prolongs time to safepoint (**Enhancement** - P4 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2309/head:pull/2309` \
`$ git checkout pull/2309`

Update a local copy of the PR: \
`$ git checkout pull/2309` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2309/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2309`

View PR using the GUI difftool: \
`$ git pr show -t 2309`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2309.diff">https://git.openjdk.org/jdk17u-dev/pull/2309.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2309#issuecomment-2013117276)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by shipilev** [comment]
/approval request Unclean backport to eliminate another safepoint hiccup caused by monitor deflation. The uncleanliness comes from the usual `NULL` vs `nullptr` differences. Otherwise applies cleanly. We are not at risk with interleaving with anything else in JDK 17: JDK-8273107 is not present, so we don't collide with VM_ThreadDump; final audit (removed in JDK 21+ with JDK-8319896) should not be risky. All tests pass.

**Comment by GoeLin** [comment]
Hi @shipilev, should we backport JDK-8325437 as folllow up?  Or won't this affect 17?

**Comment by shipilev** [comment]
> 8325437

I think this nominally affects JDK 17, but: a) that logging is already the issue in JDK 17; b) it only manifests when extended logging is requested. So we should consider as the follow-up low-priority backport.

**Comment by shipilev** [comment]
> I think this nominally affects JDK 17, but: a) that logging is already the issue in JDK 17; b) it only manifests when extended logging is requested. So we should consider as the follow-up low-priority backport.

I tried to reproduce extra logging after this PR had landed in jdk17u-dev, and I don't think it is a problem. It was a huge problem before [JDK-8319896](https://bugs.openjdk.org/browse/JDK-8319896) yanked deflation from the final audit, and which point logging became massive. In JDK 17u, we still do deflation at final audit, so this is a non-issue.

**Pull request closed without merging**
