### PR TITLE
8323086: Shenandoah: Heap could be corrupted by oom during evacuation

### PR DESCRIPTION
**Pull request by earthling-amzn**
---------
### Progress
- [x] [JDK-8323086](https://bugs.openjdk.org/browse/JDK-8323086) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8323086](https://bugs.openjdk.org/browse/JDK-8323086): Shenandoah: Heap could be corrupted by oom during evacuation (**Bug** - P3 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2114/head:pull/2114` \
`$ git checkout pull/2114`

Update a local copy of the PR: \
`$ git checkout pull/2114` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2114/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2114`

View PR using the GUI difftool: \
`$ git pr show -t 2114`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2114.diff">https://git.openjdk.org/jdk17u-dev/pull/2114.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2114#issuecomment-1881713495)

### CODE REVIEW

**Comment by GoeLin** [comment]
@earthling-amzn I removed the fix-request tag.
Please label again when we develop 17.0.12.
Also, please follow  https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix in your fix-request comment.

**Comment by shipilev** [comment]
I think the part of the missing background here (which would really be in fix-request) is that we have been running with this patch in GenShen for quite a while. So this is not really a new patch, it fixes an important corner case, and so I think it would be useful to have in current 17u (17.0.11). @GoeLin, can we still do it? @earthling-amzn should probably re-request with the much better fix-request.

**Comment by earthling-amzn** [comment]
/approval request Please accept my apologies for the previously terse approval request. We discovered this issue almost two years ago during development of the generational mode for Shenandoah (which, at the time was more prone to out of memory errors during evacuation). Originally, it wasn't clear to us that the bug affected the upstream branch. We've been running this code in various internal customer test environments for the past two years. Additionally, we have nightly automated tests that run the latest Dacapo, Heapothesys, Extremem, SpecJBB1015, SpecJVM2008, and Diluvian benchmarks in both the release configuration, and a fastdebug configuration with GC stress flags enabled.

**Pull request closed without merging**
