### PR TITLE
8299378: sprintf is deprecated in Xcode 14

### PR DESCRIPTION
**Pull request by gdams**
Backport applies cleanly except for the missing `test/hotspot/gtest/utilities/test_unsigned5.cpp` in JDK17u.

I had to manually add the `runtime/os.hpp` import which was added as part of https://github.com/openjdk/jdk/commit/df6cf1e41d0fc2dd5f5c094f66c7c8969cf5548d

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8299378](https://bugs.openjdk.org/browse/JDK-8299378) needs maintainer approval

### Issue
 * [JDK-8299378](https://bugs.openjdk.org/browse/JDK-8299378): sprintf is deprecated in Xcode 14 (**Enhancement** - P4 - Approved)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2661/head:pull/2661` \
`$ git checkout pull/2661`

Update a local copy of the PR: \
`$ git checkout pull/2661` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2661/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2661`

View PR using the GUI difftool: \
`$ git pr show -t 2661`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2661.diff">https://git.openjdk.org/jdk17u-dev/pull/2661.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2661#issuecomment-2208783463)

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
`test_unsigned5.cpp` got added with [JDK-8292758](https://bugs.openjdk.org/browse/JDK-8292758) only in JDK 20. OK.

**Review by jerboaa — CHANGES_REQUESTED** [review]
Looking at GHA, the builds fail, though. Please check.

**Review by jerboaa — APPROVED** [review]
LGTM.

**Comment by gdams** [comment]
/approval request This change applies cleanly other than a single file missing in JDK17u. I also added a single import command to avoid backporting a 180+ line commit. All tests pass. This is also crucial to allow us to upgrade the GH actions workflow to move away from the deprecated macos-11 VMs.

**Review by gnu-andrew — APPROVED** [review]
Backport looks good to me too. No issue with adding imports as needed rather than backporting where they were added in a later JDK version.

**Pull request closed without merging**
