### PR TITLE
8303942: os::write should write completely

### PR DESCRIPTION
**Pull request by elifaslan1**
Hi all,

This is not a clean backport and this pull request contains a backport of the closed bug [JDK-8273153](https://bugs.openjdk.org/browse/JDK-8273153) commit [ba5482d1a7a9](https://github.com/openjdk/jdk/commit/9732fbe428c3b6a5422cc94e7295ba5482d1a7a9).

Ran jtreg tier-1 locally 
GHA [macos-x64 / test (hs/tier1 serviceability)] fails however it is infrastructure issue and unrelated from the current change.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] [JDK-8303942](https://bugs.openjdk.org/browse/JDK-8303942) needs maintainer approval

### Issue
 * [JDK-8303942](https://bugs.openjdk.org/browse/JDK-8303942): os::write should write completely (**Bug** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1797/head:pull/1797` \
`$ git checkout pull/1797`

Update a local copy of the PR: \
`$ git checkout pull/1797` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1797/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1797`

View PR using the GUI difftool: \
`$ git pr show -t 1797`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1797.diff">https://git.openjdk.org/jdk17u-dev/pull/1797.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1797#issuecomment-1735974916)

### CODE REVIEW

**Comment by GoeLin** [comment]
Hi @elifaslan1,
please supply an elaborate Firx request message with your approval request. Also, there is a follow up failure you should address, probably in a dependent pull request. 
This is a huge change, why do we need it?
I remove the label for now.

**Comment by phohensee** [comment]
Hi, @elifaslan1. If you want to continue with this, I recommend splitting it into 3 backports, first [JDK-8273153](https://bugs.openjdk.org/browse/JDK-8273153), then [JDK-8303942](https://bugs.openjdk.org/browse/JDK-8303942), and finally [JDK-8316468](https://bugs.openjdk.org/browse/JDK-8316468). Much easier to review that way.

**Comment by elifaslan1** [comment]
First one is ready for approval: https://github.com/openjdk/jdk17u-dev/pull/2281 @phohensee

**Pull request closed without merging**
