### PR TITLE
8283870: jdeprscan --help causes an exception when the locale is ja, zh_CN or de

### PR DESCRIPTION
**Pull request by D-D-H**
This is a backport of JDK-8283870. It's not clean since there doesn't exist jdeprscan_de.properties in 17.

Some developers need to use this tool to help java 17 migration, so imo it's necessary to backport it.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8283870](https://bugs.openjdk.org/browse/JDK-8283870): jdeprscan --help causes an exception when the locale is ja, zh_CN or de

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/949/head:pull/949` \
`$ git checkout pull/949`

Update a local copy of the PR: \
`$ git checkout pull/949` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/949/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 949`

View PR using the GUI difftool: \
`$ git pr show -t 949`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/949.diff">https://git.openjdk.org/jdk17u-dev/pull/949.diff</a>

</details>

### CODE REVIEW

**Comment by GoeLin** [comment]
Hi @D-D-H
can you please enable the pre-submit tests!
Thanks.

**Comment by D-D-H** [comment]
Hi @GoeLin ,
Thanks for the reminder.
I have enabled the workflow, and it's running now.

**Pull request closed without merging**
