### PR TITLE
8225377: type annotations are not visible to javac plugins across compilation boundaries

### PR DESCRIPTION
**Pull request by cushon**
Hi,
 
This is a backport of [JDK-8225377: type annotations are not visible to javac plugins across compilation boundaries](https://bugs.openjdk.org/browse/JDK-8225377)

The patch did not apply cleanly, I resolved one merge conflict due to changes to the internal `TypeMetadata` API for JDK-8303820.

The modified test fails without the patch, and passes with it. The patch passes `langtools:tier1` tests.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8225377](https://bugs.openjdk.org/browse/JDK-8225377) needs maintainer approval

### Issue
 * [JDK-8225377](https://bugs.openjdk.org/browse/JDK-8225377): type annotations are not visible to javac plugins across compilation boundaries (**Bug** - P3 - Approved)

### Reviewers
 * [Vicente Romero](https://openjdk.org/census#vromero) (@vicente-romero-oracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1952/head:pull/1952` \
`$ git checkout pull/1952`

Update a local copy of the PR: \
`$ git checkout pull/1952` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1952/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1952`

View PR using the GUI difftool: \
`$ git pr show -t 1952`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1952.diff">https://git.openjdk.org/jdk17u-dev/pull/1952.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1952#issuecomment-1800839841)

### CODE REVIEW

**Review by vicente-romero-oracle — APPROVED** [review]
looks good

**Comment by cushon** [comment]
I'm holding off on merging this until the follow-up in #2005 is also ready to merge, it is waiting on maintainer approval

**Pull request closed without merging**
