### PR TITLE
8276766: Enable jar and jmod to produce deterministic timestamped content

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
This backport (along with others in-progress) enables reproducible building of jar's and jmod's with the addition of a new --date <source date> option. Enabling reproducible timestamped jar & jmod content.

jdk-17.0.3 CSR: https://bugs.openjdk.java.net/browse/JDK-8279926

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed
- [x] Change requires a CSR request to be approved

### Issues
 * [JDK-8276766](https://bugs.openjdk.java.net/browse/JDK-8276766): Enable jar and jmod to produce deterministic timestamped content
 * [JDK-8279453](https://bugs.openjdk.java.net/browse/JDK-8279453): Disable tools/jar/ReproducibleJar.java on 32-bit platforms
 * [JDK-8277755](https://bugs.openjdk.java.net/browse/JDK-8277755): Enable jar and jmod to produce deterministic timestamped content (**CSR**)

### Reviewers
 * [Lance Andersen](https://openjdk.java.net/census#lancea) (@LanceAndersen - **Reviewer**) ⚠️ Review applies to 5f5ac9a3588e46d71ef53b1cafdc90c9e9dae8fd
 * [Christoph Langer](https://openjdk.java.net/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17u-dev pull/82/head:pull/82` \
`$ git checkout pull/82`

Update a local copy of the PR: \
`$ git checkout pull/82` \
`$ git pull https://git.openjdk.java.net/jdk17u-dev pull/82/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 82`

View PR using the GUI difftool: \
`$ git pr show -t 82`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17u-dev/pull/82.diff">https://git.openjdk.java.net/jdk17u-dev/pull/82.diff</a>

</details>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
Also adds disablement of test/jdk/tools/jar/ReproducibleJar.java on 32bit platforms for https://bugs.openjdk.java.net/browse/JDK-8279453

**Comment by GoeLin** [comment]
Hi @andrew-m-leonard
next time, I would prefer two backports for seperate issues as JDK-8276766 and JDK-8279453.
You can use dependent Pull Request to stack changes if needed.
Add in the fix request comments that such changes need to be pushed at the same time.
I assume this would have saved you from looking for a reviewer. 
Please also elaborate why the change is not clean when you make the Pull Request. This simplifies the task of reviewing.
Please only add the jfk17u-fix-request label once the change is reviewed. 
Thanks,
  Goetz.

**Comment by andrew-m-leonard** [comment]
Hi Goetz,
Thanks for the tips,  i'll follow this advice for the next ones.
Cheers
Andrew

**Comment by andrew-m-leonard** [comment]
This PR had a merge conflict when applying the original patch, due to jdk PR: https://github.com/openjdk/jdk/commit/a81e4fc07b654a3cc954921981d9d3c0cfd8bcec
which is not required for this PR.
The setZipEntryTime() logic was applied to the jdk17u logic.

**Comment by andrew-m-leonard** [comment]
jdk-17u CSR for this has now been Approved: https://bugs.openjdk.java.net/browse/JDK-8279926

**Comment by andrew-m-leonard** [comment]
tier1 and tooling tests all pass.

**Review by LanceAndersen — APPROVED** [review]
Looks good to me

**Comment by andrew-m-leonard** [comment]
/integrate
i'm happy this is ready

**Comment by GoeLin** [comment]
Hi @andrew-m-leonard, backports are only ready if there is the jdk*u-fix-yes label on the bug. Please don't integrate before you see that label on the bug. Unfortunatley there is no automatic check for this.

**Comment by andrew-m-leonard** [comment]
Thanks @GoeLin, I did realize that, I got confused with the other bug that had been marked

**Comment by RealCLanger** [comment]
@andrew-m-leonard, can you please remove the Issues JDK-8279453 and JDK-8277755 from this PR via the "/issue remove" PR command?
JDK-8279453 is a follow up testfix and should be committed separately. It furthermore doesn't have the jdk17u-fix-request label/comment yet and hence hasn't been approved by a maintainer.
JDK-8277755 is the original CSR and won't be backported by the resulting commit from this PR.

**Comment by RealCLanger** [comment]
> @andrew-m-leonard, can you please remove the Issues JDK-8279453 and JDK-8277755 from this PR via the "/issue remove" PR command? JDK-8279453 is a follow up testfix and should be committed separately. It furthermore doesn't have the jdk17u-fix-request label/comment yet and hence hasn't been approved by a maintainer. JDK-8277755 is the original CSR and won't be backported by the resulting commit from this PR.

OK, maybe JDK-8279453 can be kept, but please add jdk17u-fix-request and according comment...

**Comment by andrew-m-leonard** [comment]
@RealCLanger I can't remove 8277755, as the Skara bot processor keeps adding it back in. It seems the Skara interface doesn't handle CSR's for backports, as it makes the assumption the corresponding CSR is the CSR for the bug determined from the PR summary prefix, which as we know must be the original bug, hence Skara chooses the original CSR and won't let you remove it....

**Comment by andrew-m-leonard** [comment]
I've added the jdk17u-fix-request to https://bugs.openjdk.java.net/browse/JDK-8279453 for completeness.

**Review by RealCLanger — APPROVED** [review]

**Comment by RealCLanger** [comment]
> @RealCLanger I can't remove 8277755, as the Skara bot processor keeps adding it back in. It seems the Skara interface doesn't handle CSR's for backports, as it makes the assumption the corresponding CSR is the CSR for the bug determined from the PR summary prefix, which as we know must be the original bug, hence Skara chooses the original CSR and won't let you remove it....

Ah, ok. Seems like a new feature of Skara to record the CSR issue. Didn't know that. So go for it.

/sponsor

**Pull request closed without merging**
