### PR TITLE
8281717: Cover logout method for several LoginModule

### PR DESCRIPTION
**Pull request by GoeLin**
I backport this for parity with 17.0.9-oracle.

I am including JDK-8284090 as without the test does not compile.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8281717](https://bugs.openjdk.org/browse/JDK-8281717): Cover logout method for several LoginModule (**Enhancement** - P3)
 * [JDK-8284090](https://bugs.openjdk.org/browse/JDK-8284090): com/sun/security/auth/module/AllPlatforms.java fails to compile (**Bug** - P4)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1606/head:pull/1606` \
`$ git checkout pull/1606`

Update a local copy of the PR: \
`$ git checkout pull/1606` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1606/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1606`

View PR using the GUI difftool: \
`$ git pr show -t 1606`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1606.diff">https://git.openjdk.org/jdk17u-dev/pull/1606.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1606#issuecomment-1643852133)

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
LGTM.

**Comment by GoeLin** [comment]
GHA failure: known riskv issue

**Pull request closed without merging**
