### PR TITLE
8289647: AssertionError during annotation processing of record related tests

### PR DESCRIPTION
**Pull request by AntonKozlov**
Please review a backport to fix a JCK failure. The fix was also backported to Oracle 17.0.7.

The fix is almost clean except affected bugs list in the test.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8289647](https://bugs.openjdk.org/browse/JDK-8289647): AssertionError during annotation processing of record related tests

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [73e5b076](https://git.openjdk.org/jdk17u-dev/pull/1181/files/73e5b0764634e9e12c647c6a4e009a5b26c91555)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/1181/head:pull/1181` \
`$ git checkout pull/1181`

Update a local copy of the PR: \
`$ git checkout pull/1181` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/1181/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1181`

View PR using the GUI difftool: \
`$ git pr show -t 1181`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1181.diff">https://git.openjdk.org/jdk17u-dev/pull/1181.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — CHANGES_REQUESTED** [review]
Looks good, except that 8282714 has not been backported, so should be left out of the bug list in RecordCompilationTests.java.

**Comment by AntonKozlov** [comment]
Thanks! 8282714 is removed  from the bug list.

**Review by phohensee — APPROVED** [review]
Looks good. :)

**Comment by GoeLin** [comment]
Hi @AntonKozlov, you can also trigger new Pre-submit tests by clicking on the branch of your PR, and in the branch click on "Sync fork".  This merges head into your branch. Obviously, head needs new changes to work.

**Pull request closed without merging**
