### PR TITLE
8309258: RISC-V: Add riscv_hwprobe syscall

### PR DESCRIPTION
**Pull request by robehn**
Hi, please consider.

```
RISC-V has many extensions and it's not feasible to set them correctly on the command line for users.
There is no instruction to get the cpu, such as cpuid on x86.
```

Still running tests, it will take a while.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8309258](https://bugs.openjdk.org/browse/JDK-8309258) needs maintainer approval
- [x] [JDK-8315206](https://bugs.openjdk.org/browse/JDK-8315206) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8316859](https://bugs.openjdk.org/browse/JDK-8316859) needs maintainer approval

### Issues
 * [JDK-8309258](https://bugs.openjdk.org/browse/JDK-8309258): RISC-V: Add riscv_hwprobe syscall (**Enhancement** - P4 - Approved)
 * [JDK-8315206](https://bugs.openjdk.org/browse/JDK-8315206): RISC-V: hwprobe query is_set return wrong value (**Bug** - P2 - Approved)
 * [JDK-8316859](https://bugs.openjdk.org/browse/JDK-8316859): RISC-V: Disable detection of V through HWCAP (**Task** - P4 - Approved)

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1942/head:pull/1942` \
`$ git checkout pull/1942`

Update a local copy of the PR: \
`$ git checkout pull/1942` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1942/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1942`

View PR using the GUI difftool: \
`$ git pr show -t 1942`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1942.diff">https://git.openjdk.org/jdk17u-dev/pull/1942.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1942#issuecomment-1790802488)

### CODE REVIEW

**Comment by robehn** [comment]
I did I 'accidentally' removed OS_HEADER_INLINE, fixing it back.

**Review by RealFYang — APPROVED** [review]
Looks good to me assuming that following two related fixes will also be backported:
```
8315206: RISC-V: hwprobe query is_set return wrong value
8316859: RISC-V: Disable detection of V through HWCAP
```

**Comment by robehn** [comment]
> Looks good to me assuming that following two related fixes will also be backported:
> 
> ```
> 8315206: RISC-V: hwprobe query is_set return wrong value
> 8316859: RISC-V: Disable detection of V through HWCAP
> ```

HI, thanks, yes, and "8315195: RISC-V: Update hwprobe query for new extensions"

**Comment by GoeLin** [comment]
Hi @robehn, could you please enable GHA actions on your repo? Thanks!

**Comment by robehn** [comment]
@GoeLin @RealFYang should I do all four in this PR, it may be easier ?

**Comment by RealFYang** [comment]
> @GoeLin @RealFYang should I do all four in this PR, it may be easier ?

Hi, I personally perfer the first three in one go as they are somehow directly related.
@GoeLin : I guess that's OK from a maintainer's perspective?

**Comment by GoeLin** [comment]
Hi @robehn, yes, you can push them on top in this branch. If so, please use the /issue command. But you can also do separate changes. I'd leave it to you and @RealFYang to decide, you are the riskv experts.

**Comment by robehn** [comment]
/approval request 8315206 Bug fix for hwprobe. Applied clean on the hwprobe add backport.
/approval request 8315206 Related bug fix, V should not be enabled by hwcap. Applied clean on the hwprobe add backport.

**Comment by robehn** [comment]
We do the three first here, and I'll do the fourth in a separate PR, as suggest by @RealFYang.

**Review by RealFYang — APPROVED** [review]

**Comment by robehn** [comment]
I found no issue in testing, I'm integrating and starting a PR for the last back port for this.

**Pull request closed without merging**
