### PR TITLE
8299972: Remove metaprogramming/removeReference.hpp

### PR DESCRIPTION
**Pull request by gdams**
prerequisite to bumping googletest to 1.13.0

Applies cleanly other than the deleted file (`src/hotspot/share/metaprogramming/removeReference.hpp`) containing some extra commits

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8299972](https://bugs.openjdk.org/browse/JDK-8299972) needs maintainer approval

### Issue
 * [JDK-8299972](https://bugs.openjdk.org/browse/JDK-8299972): Remove metaprogramming/removeReference.hpp (**Enhancement** - P4 - Approved)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2678/head:pull/2678` \
`$ git checkout pull/2678`

Update a local copy of the PR: \
`$ git checkout pull/2678` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2678/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2678`

View PR using the GUI difftool: \
`$ git pr show -t 2678`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2678.diff">https://git.openjdk.org/jdk17u-dev/pull/2678.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2678#issuecomment-2211138981)

### CODE REVIEW

**Comment by MBaesken** [comment]
So do we still need  metaprogramming/removeReference.hpp  ?
It looks a bit strange that the issue/PR is named 'Remove metaprogramming/removeReference.hpp' but the file stays ?

**Comment by gdams** [comment]
> So do we still need metaprogramming/removeReference.hpp ? It looks a bit strange that the issue/PR is named 'Remove metaprogramming/removeReference.hpp' but the file stays ?

Good spot, let me check it now

**Comment by gdams** [comment]
@MBaesken yeah sorry I messed that one up! Too many backport branches right now :D This might even be marked as clean now

**Review by MBaesken — APPROVED** [review]

**Comment by gdams** [comment]
/approval request Applies cleanly other than the deleted file (src/hotspot/share/metaprogramming/removeReference.hpp) containing some extra commits, Low risk, required as part of the macOS/Xcode upgrade

**Pull request closed without merging**
