### PR TITLE
8300806: Update googletest to v1.13.0

### PR DESCRIPTION
**Pull request by gdams**
Prerequisite to bumping to xcode 14+. This change applies cleanly other than the fact that the JTREG version is different in JDK17u

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8300806](https://bugs.openjdk.org/browse/JDK-8300806) needs maintainer approval

### Issue
 * [JDK-8300806](https://bugs.openjdk.org/browse/JDK-8300806): Update googletest to v1.13.0 (**Enhancement** - P4 - Approved)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2667/head:pull/2667` \
`$ git checkout pull/2667`

Update a local copy of the PR: \
`$ git checkout pull/2667` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2667/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2667`

View PR using the GUI difftool: \
`$ git pr show -t 2667`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2667.diff">https://git.openjdk.org/jdk17u-dev/pull/2667.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2667#issuecomment-2210518190)

### CODE REVIEW

**Comment by jerboaa** [comment]
Please be sure to run `make test TEST=gtest:all` on a fastdebug build with this.

**Comment by gdams** [comment]
> Please be sure to run `make test TEST=gtest:all` on a fastdebug build with this.

There's several PR's that I'm going to need to merge first here anyway. See https://github.com/openjdk/jdk17u-dev/pulls?q=is%3Apr+is%3Aopen+Remove+metaprogramming

**Comment by jerboaa** [comment]
It looks like there is more work to do:

* One more `sprintf` usage in `test/hotspot/jtreg/vmTestbase/nsk/jvmti/ThreadEnd/threadend001/threadend001.cpp` removed in JDK 20 with [JDK-8294486](https://bugs.openjdk.org/browse/JDK-8294486). We'll need a JDK 17-specific fix.
* Windows failures due to [JDK-8299971](https://bugs.openjdk.org/browse/JDK-8299971) still missing. That'll have to get backported too.

**Comment by gdams** [comment]
> It looks like there is more work to do:
> 
> * One more `sprintf` usage in `test/hotspot/jtreg/vmTestbase/nsk/jvmti/ThreadEnd/threadend001/threadend001.cpp` removed in JDK 20 with [JDK-8294486](https://bugs.openjdk.org/browse/JDK-8294486). We'll need a JDK 17-specific fix.
> * Windows failures due to [JDK-8299971](https://bugs.openjdk.org/browse/JDK-8299971) still missing. That'll have to get backported too.

yeah I'm working through those atm, I need to get the remaining PRs that are currently awaiting approval sorted first though

**Comment by gdams** [comment]
> * test/hotspot/jtreg/vmTestbase/nsk/jvmti/ThreadEnd/threadend001/threadend001.cpp

@jerboaa I've raised https://github.com/openjdk/jdk17u-dev/pull/2695 to cover the missing test fixes

**Comment by gdams** [comment]
@jerboaa CI hasn't completed yet but so far this is looking good 🎉

**Comment by jerboaa** [comment]
Please make sure all gtest runs continue to work. I'll be sure to review this.

**Comment by gdams** [comment]
> Please make sure all gtest runs continue to work. I'll be sure to review this.

yup I'm working on that now, will report back shortly

**Comment by gdams** [comment]
> Please make sure all gtest runs continue to work. I'll be sure to review this.

```
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   gtest:all/server                                    832   832     0     0   
==============================
TEST SUCCESS
```

All passed on my M1 mac

**Comment by gdams** [comment]
CI is finally green again 🎉

**Review by jerboaa — APPROVED** [review]
Looks OK to me. One minor nit. I've also ran `gtests:all` on Linux x86_64 and the results are a pass:

```
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   gtest:all/server                                    901   901     0     0   
==============================
TEST SUCCESS
```

**Comment by gdams** [comment]
/approval request Prerequisite to bumping to xcode 14+. This change applies cleanly other than the fact that the JTREG version is different in JDK17u. This is the final change to make CI green again. `gtests:all` has been run on macOS and Linux x86_64.

**Review by jerboaa — APPROVED** [review]

**Pull request closed without merging**
