### PR TITLE
8286740: JFR: Active Setting event emitted incorrectly

### PR DESCRIPTION
**Pull request by richardstartin**
jtreg_jfr passed [here](https://github.com/DataDog/openjdk-jdk17/actions/runs/7928014975)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8286740](https://bugs.openjdk.org/browse/JDK-8286740) needs maintainer approval

### Issue
 * [JDK-8286740](https://bugs.openjdk.org/browse/JDK-8286740): JFR: Active Setting event emitted incorrectly (**Bug** - P3 - Approved)

### Reviewers
 * [Jaroslav Bachorik](https://openjdk.org/census#jbachorik) (@jbachorik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2210/head:pull/2210` \
`$ git checkout pull/2210`

Update a local copy of the PR: \
`$ git checkout pull/2210` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2210/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2210`

View PR using the GUI difftool: \
`$ git pr show -t 2210`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2210.diff">https://git.openjdk.org/jdk17u-dev/pull/2210.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2210#issuecomment-1948069022)

### CODE REVIEW

**Review by jbachorik — APPROVED** [review]
I cross-checked the diff against the original fix and the only minor difference is `MetadataRepository.java` where `configuration.getEventControl()` was changed to `handler.getEventControl()`.

LGTM

**Comment by richardstartin** [comment]
Fix Request 17u
 
Backporting this patch prevents spurious durations from being reported on jdk.ActiveSettingEvents. This should be backported because the issue was introduced in JDK 14 with Event Streaming, and the original issue recommends backporting to JDK 17.

**Comment by GoeLin** [comment]
@richardstartin How did you test this?
I would like to delay this to the July update, can you please label again after 27.2.?

**Comment by richardstartin** [comment]
> @richardstartin How did you test this? I would like to delay this to the July update, can you please label again after 27.2.?

As mentioned above, we ran the linked JFR jtreg tests, which pass.

**Pull request closed without merging**
