### PR TITLE
8286490: JvmtiEventControllerPrivate::set_event_callbacks CLEARING_MASK computation is incorrect

### PR DESCRIPTION
**Pull request by wkia**
This is a backport of JDK-8286490: JvmtiEventControllerPrivate::set_event_callbacks CLEARING_MASK computation is incorrect.

Backporting this because this issue can be reproduced in JDK17 as well.

The backport isn't clean:
1. Resolved a conflict in `src/hotspot/share/prims/jvmtiEventController.cpp` with an empty line.
2. Removed files as VThreads are not implemented in jdk17:
      - `test/hotspot/jtreg/serviceability/jvmti/vthread/VThreadTest/libVThreadTest.cpp` 
      - `test/hotspot/jtreg/serviceability/jvmti/vthread/VThreadTest/VThreadTest.java`
3. Added new test:
      - `test/hotspot/jtreg/vmTestbase/nsk/jvmti/unit/extcallback/Test.java`
      - `test/hotspot/jtreg/vmTestbase/nsk/jvmti/unit/extcallback/libextcallback.c`
      - `test/hotspot/jtreg/vmTestbase/nsk/jvmti/unit/extcallback/loadClass/Test2.java`

Actually, backporting the fix only.
The new test fails without the fix, and successfully passes with the fix.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8286490](https://bugs.openjdk.org/browse/JDK-8286490) needs maintainer approval

### Issue
 * [JDK-8286490](https://bugs.openjdk.org/browse/JDK-8286490): JvmtiEventControllerPrivate::set_event_callbacks CLEARING_MASK computation is incorrect (**Bug** - P4 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2276/head:pull/2276` \
`$ git checkout pull/2276`

Update a local copy of the PR: \
`$ git checkout pull/2276` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2276/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2276`

View PR using the GUI difftool: \
`$ git pr show -t 2276`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2276.diff">https://git.openjdk.org/jdk17u-dev/pull/2276.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2276#issuecomment-1985133751)

### CODE REVIEW

**Comment by wkia** [comment]
GHA passed, but "linux-cross-compile / build (riscv64)" - seems like an infrastructure problem.

**Comment by wkia** [comment]
Up

**Comment by wkia** [comment]
Up

**Review by phohensee — APPROVED** [review]

**Comment by phohensee** [comment]
GHA failure is an infrastructure issue.

**Pull request closed without merging**
