### PR TITLE
8293550: Optionally add get-task-allow entitlement to macos binaries

### PR DESCRIPTION
**Pull request by benty-amzn**
Backporting for parity with Oracle JDK 17. Patch is clean after [JDK-8273497](https://bugs.openjdk.org/browse/JDK-8273497) (#914) and [JDK-8285093](https://bugs.openjdk.org/browse/JDK-8285093) (#915).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8293550](https://bugs.openjdk.org/browse/JDK-8293550): Optionally add get-task-allow entitlement to macos binaries

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/916/head:pull/916` \
`$ git checkout pull/916`

Update a local copy of the PR: \
`$ git checkout pull/916` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/916/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 916`

View PR using the GUI difftool: \
`$ git pr show -t 916`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/916.diff">https://git.openjdk.org/jdk17u-dev/pull/916.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — COMMENTED** [review]
Please enable pre-submit testing on your repo, see https://wiki.openjdk.org/display/SKARA/Testing.

**Review by phohensee — COMMENTED** [review]
Please enable pre-submit testing on your repo, see https://wiki.openjdk.org/display/SKARA/Testing.

**Review by phohensee — CHANGES_REQUESTED** [review]
This PR isn't clean even after https://github.com/openjdk/jdk17u-dev/pull/914 and https://github.com/openjdk/jdk17u-dev/pull/915. Perhaps it needs to be rebased.

**Comment by benty-amzn** [comment]
I'm not sure why those conflicts appeared, after pulling the current `master` and redoing the backport with `git backport --from https://github.com/openjdk/jdk f42caefe2e7658bfb5ab8ef938b134bdb6746ff1` it is clean again.

**Pull request closed without merging**
