### PR TITLE
8326446: The User and System of jdk.CPULoad on Apple M1 are inaccurate

### PR DESCRIPTION
**Pull request by yanglong1010**
Hi, all

Could I have a review of this backport.

This pull request contains a backport of commit [8dbd4b391f7deb1a46a5f07f0bc46f23d6715ddb](https://github.com/openjdk/jdk/commit/8dbd4b391f7deb1a46a5f07f0bc46f23d6715ddb) from the [openjdk/jdk](https://github.com/openjdk/jdk) repository.

Testing: I ran test/jdk/jdk/jfr/event/os/TestCPULoad.java and passed. All GHA tests are passed (except linux-cross-compile, build(riscv64), Create sysroot. It looks like there's an issue with the GHA's process).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8326446](https://bugs.openjdk.org/browse/JDK-8326446) needs maintainer approval

### Issue
 * [JDK-8326446](https://bugs.openjdk.org/browse/JDK-8326446): The User and System of jdk.CPULoad on Apple M1 are inaccurate (**Bug** - P3 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2277/head:pull/2277` \
`$ git checkout pull/2277`

Update a local copy of the PR: \
`$ git checkout pull/2277` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2277/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2277`

View PR using the GUI difftool: \
`$ git pr show -t 2277`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2277.diff">https://git.openjdk.org/jdk17u-dev/pull/2277.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2277#issuecomment-1985201575)

### CODE REVIEW

**Comment by yanglong1010** [comment]
Gentle ping. I would be very grateful if anyone could help with the review.

**Review by phohensee — APPROVED** [review]

**Comment by yanglong1010** [comment]
/approval 8326446 request The JFR's jdk.CPULoad event provides information about how much CPU is occupied by Java process, often used in performance analysis. But the User and System percentages of jdk.CPULoad event on Apple M1 are inaccurate (far below normal). I would like to backport this fix to jdk17u-dev.
Low risk: This patch only affects the User and System percentages of JFR's jdk.CPULoad event.
Testing: I ran test/jdk/jdk/jfr/event/os/TestCPULoad.java and passed. All GHA tests are passed (except linux-cross-compile, build(riscv64), Create sysroot. It looks like there's an issue with the GHA's process).

**Comment by GoeLin** [comment]
@yanglong1010, could you please first do the 22u backport? Thanks.

**Comment by yanglong1010** [comment]
Sure, I'll deal with it next week

**Comment by yanglong1010** [comment]
@GoeLin The 22u backport has been done.

**Comment by yanglong1010** [comment]
/approval 8326446 request The JFR's jdk.CPULoad event provides information about how much CPU is occupied by Java process, often used in performance analysis. But the User and System percentages of jdk.CPULoad event on Apple M1 are inaccurate (far below normal). I would like to backport this fix to jdk17u-dev.
Low risk: This patch only affects the User and System percentages of JFR's jdk.CPULoad event.
Testing: I ran test/jdk/jdk/jfr/event/os/TestCPULoad.java and passed. All GHA tests are passed (except linux-cross-compile, build(riscv64), Create sysroot. It looks like there's an issue with the GHA's process).

**Comment by yanglong1010** [comment]
Thank you all ~

**Pull request closed without merging**
