### PR TITLE
8289184: runtime/ClassUnload/DictionaryDependsTest.java failed with "Test failed: should be unloaded"

### PR DESCRIPTION
**Pull request by GoeLin**
I backport this to improve testing in 17.

test/hotspot/jtreg/runtime/logging/ClassLoadUnloadTest.java: trivial resolve.

This change makes test/hotspot/jtreg/runtime/logging/ClassLoadUnloadTest.java fail.
Therefore I include 8321299 which fixes this.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8289184](https://bugs.openjdk.org/browse/JDK-8289184) needs maintainer approval
- [x] Commit message must refer to an issue
- [x] [JDK-8321299](https://bugs.openjdk.org/browse/JDK-8321299) needs maintainer approval

### Issues
 * [JDK-8289184](https://bugs.openjdk.org/browse/JDK-8289184): runtime/ClassUnload/DictionaryDependsTest.java failed with "Test failed: should be unloaded" (**Bug** - P4 - Approved)
 * [JDK-8321299](https://bugs.openjdk.org/browse/JDK-8321299): runtime/logging/ClassLoadUnloadTest.java doesn't reliably trigger class unloading (**Bug** - P4 - Approved)

### Reviewers
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2937/head:pull/2937` \
`$ git checkout pull/2937`

Update a local copy of the PR: \
`$ git checkout pull/2937` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2937/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2937`

View PR using the GUI difftool: \
`$ git pr show -t 2937`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2937.diff">https://git.openjdk.org/jdk17u-dev/pull/2937.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2937#issuecomment-2393341632)

### CODE REVIEW

**Comment by GoeLin** [comment]
GAH failure: 
runtime/logging/ClassLoadUnloadTest.java fails. 
This change modifiers the way class unloading is triggered. It is now using Whitebox.fullGc().
This seems not to trigger unloading of the class in 17.  Hmm.

**Comment by GoeLin** [comment]
GHA now passing. JDK-8321299 helped.

**Review by RealLucy — APPROVED** [review]
Looks good.

**Pull request closed without merging**
