### PR TITLE
8319525: RISC-V: Rename *_riscv64.ad files to *_riscv.ad under riscv/gc

### PR DESCRIPTION
**Pull request by feilongjiang**
I would like to backport [JDK-8319525](https://bugs.openjdk.org/browse/JDK-8319525) to make possible future backports to those AD files smooth.
Applies not clean since 17u does not support generational-zgc yet.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8319525](https://bugs.openjdk.org/browse/JDK-8319525) needs maintainer approval

### Issue
 * [JDK-8319525](https://bugs.openjdk.org/browse/JDK-8319525): RISC-V: Rename *_riscv64.ad files to *_riscv.ad under riscv/gc (**Enhancement** - P4 - Approved)

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1954/head:pull/1954` \
`$ git checkout pull/1954`

Update a local copy of the PR: \
`$ git checkout pull/1954` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1954/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1954`

View PR using the GUI difftool: \
`$ git pr show -t 1954`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1954.diff">https://git.openjdk.org/jdk17u-dev/pull/1954.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1954#issuecomment-1801959321)

### CODE REVIEW

**Comment by feilongjiang** [comment]
/approval request Simple cleanup change renaming three riscv-specific AD files. Low risk.

**Review by RealFYang — APPROVED** [review]
LGTM.

**Comment by feilongjiang** [comment]
GHA build and  `hotspot:tier1` passed.

**Comment by feilongjiang** [comment]
Got fix-request-yes, so
/integrate

**Pull request closed without merging**
