### PR TITLE
8288445: AArch64: C2 compilation fails with guarantee(!true || (true && (shift != 0))) failed: impossible encoding

### PR DESCRIPTION
**Pull request by yftsai**
Backport b4490386fe348250e88347526172c1c27ef01eba

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8288445](https://bugs.openjdk.org/browse/JDK-8288445): AArch64: C2 compilation fails with guarantee(!true || (true && (shift != 0))) failed: impossible encoding

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/640/head:pull/640` \
`$ git checkout pull/640`

Update a local copy of the PR: \
`$ git checkout pull/640` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/640/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 640`

View PR using the GUI difftool: \
`$ git pr show -t 640`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/640.diff">https://git.openjdk.org/jdk17u-dev/pull/640.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
/clean

Not clean due to a single trivial context difference in aarch64_neon.ad.

**Comment by phohensee** [comment]
Tagged JBS issue.

**Comment by RealCLanger** [comment]
> /integrate

@yftsai please only integrate after receiving JBS approval.

I approved it now.

**Pull request closed without merging**
