### PR TITLE
8280863: Update build README to reflect that MSYS2 is supported

### PR DESCRIPTION
**Pull request by gdams**
Backport [JDK-8280863](https://bugs.openjdk.org/browse/JDK-8280863) as it's a non trivial change

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8280863](https://bugs.openjdk.org/browse/JDK-8280863): Update build README to reflect that MSYS2 is supported

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/540/head:pull/540` \
`$ git checkout pull/540`

Update a local copy of the PR: \
`$ git checkout pull/540` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/540/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 540`

View PR using the GUI difftool: \
`$ git pr show -t 540`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/540.diff">https://git.openjdk.org/jdk17u-dev/pull/540.diff</a>

</details>

### CODE REVIEW

**Comment by RealCLanger** [comment]
> Backport [JDK-8257679](https://bugs.openjdk.java.net/browse/JDK-8257679) as it's a non trivial change

Hm, I think this doesn't relate to this backport... Here you are backporting [JDK-8280863](https://bugs.openjdk.org/browse/JDK-8280863) which is rather trivial. 😉 
Other than that, looks good. Thanks for tackling the backports to enable the new GHA - it's on my list, too.

**Review by RealCLanger — APPROVED** [review]

**Comment by gdams** [comment]
> Hm, I think this doesn't relate to this backport... Here you are backporting [JDK-8280863](https://bugs.openjdk.org/browse/JDK-8280863) which is rather trivial. 😉
Other than that, looks good. Thanks for tackling the backports to enable the new GHA - it's on my list, too.

@RealCLanger my bad, too many backports recently 😂 I've got a branch with the actions changes too so I'll open that once these four have been merged:

- https://github.com/openjdk/jdk17u-dev/pull/540
- https://github.com/openjdk/jdk17u-dev/pull/541
- https://github.com/openjdk/jdk17u-dev/pull/542
- https://github.com/openjdk/jdk17u-dev/pull/543

Would you mind adding the fix request labels for these as I don't have author status yet

**Comment by RealCLanger** [comment]
> 
> * [8280863: Update build README to reflect that MSYS2 is supported #540](https://github.com/openjdk/jdk17u-dev/pull/540)
> * [8287724: Fix various issues with msys2 #541](https://github.com/openjdk/jdk17u-dev/pull/541)
> * [8287896: PropertiesTest.sh fail on msys2 #542](https://github.com/openjdk/jdk17u-dev/pull/542)
> * [8287895: Some langtools tests fail on msys2 #543](https://github.com/openjdk/jdk17u-dev/pull/543)
> 
> Would you mind adding the fix request labels for these as I don't have author status yet

I've added the JBS labels/requests on your behalf and approved them at once. You're good to go for integration.

**Pull request closed without merging**
