### PR TITLE
8335918: update for deprecated sprintf for jvmti

### PR DESCRIPTION
**Pull request by gdams**
The sprintf is deprecated in Xcode 14 because of security concerns. These occurrences of sprintf were removed in JDK20 as part of https://bugs.openjdk.org/browse/JDK-8294486.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8335918](https://bugs.openjdk.org/browse/JDK-8335918) needs maintainer approval

### Issue
 * [JDK-8335918](https://bugs.openjdk.org/browse/JDK-8335918): update for deprecated sprintf for jvmti (**Enhancement** - P4 - Approved)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**) ⚠️ Review applies to [06e492e2](https://git.openjdk.org/jdk17u-dev/pull/2695/files/06e492e239fa06b9f6552c785c67516c2f0b19ed)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2695/head:pull/2695` \
`$ git checkout pull/2695`

Update a local copy of the PR: \
`$ git checkout pull/2695` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2695/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2695`

View PR using the GUI difftool: \
`$ git pr show -t 2695`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2695.diff">https://git.openjdk.org/jdk17u-dev/pull/2695.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2695#issuecomment-2214867231)

### CODE REVIEW

**Comment by jerboaa** [comment]
GHA failures are caused by gtest 1.8. To be fixed with #2667 (gtest update).

**Comment by gdams** [comment]
> Looks OK to me. Did you run the tests?

yeah I ran them on my machine and they were okay :)

**Comment by gdams** [comment]
/approval request Low risk, all tests pass. This is also crucial to allow us to upgrade the GH actions workflow to move away from the deprecated macos-11 VMs.

**Pull request closed without merging**
