### PR TITLE
8278146: G1: Rework VM_G1Concurrent VMOp to clearly identify it as pause

### PR DESCRIPTION
**Pull request by shipilev**
Clean backport to improve detailed VM diagnostics.

@tschatzl, are you good with this in 17u?

Additional testing:
 - [x] Linux x86_64 fastdebug `tier1`
 - [x] Linux x86_64 fastdebug `tier2`
 - [x] Linux x86_64 fastdebug `tier3`

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8278146](https://bugs.openjdk.org/browse/JDK-8278146): G1: Rework VM_G1Concurrent VMOp to clearly identify it as pause

### Reviewers
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to [3c20e4b8](https://git.openjdk.org/jdk17u-dev/pull/910/files/3c20e4b8a4a24851af1f19ace56ae2bd52a3875f)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/910/head:pull/910` \
`$ git checkout pull/910`

Update a local copy of the PR: \
`$ git checkout pull/910` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/910/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 910`

View PR using the GUI difftool: \
`$ git pr show -t 910`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/910.diff">https://git.openjdk.org/jdk17u-dev/pull/910.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/910#issuecomment-1322197791)

### CODE REVIEW

**Comment by shipilev** [comment]
@tschatzl, want to ack this? :)

**Comment by shipilev** [comment]
@tschatzl, want to ack this one too?

**Comment by shipilev** [comment]
@tschatzl, want to take a look at this one too?

**Review by tschatzl — APPROVED** [review]
Lgtm.

**Comment by shipilev** [comment]
Testing is clean, push approval is there.

/integrate

**Pull request closed without merging**
