### PR TITLE
8277946: NMT: Remove VM.native_memory shutdown jcmd command option

### PR DESCRIPTION
**Pull request by tstuefe**
Hi all,

This is *not* a clean downport. The upstream variant in JDK 18 outright removes the NMT shutdown dcmd option. For JDK 17, I leave it in but deprecate it and stub it out. See associated CSR backport: https://bugs.openjdk.org/browse/JDK-8299848 

Original issue: https://bugs.openjdk.org/browse/JDK-8277946
Original CSR: https://bugs.openjdk.org/browse/JDK-8277947
Backport CSR: https://bugs.openjdk.org/browse/JDK-8299848
Backport Issue: https://bugs.openjdk.org/browse/JDK-8299846

```
Differences to original CSR:

The original CSR was about removing the sub-option. That was fine for a head release.

This CSR, aimed at a maintenance release, proposes to deprecate it instead:

    jcmd would still accept the "shutdown" sub option and return 0 as exit code.
    But jcmd should report "This option has been deprecated" instead of "NMT is shutting down"
```

    Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Change requires CSR request [JDK-8299848](https://bugs.openjdk.org/browse/JDK-8299848) to be approved
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8277946](https://bugs.openjdk.org/browse/JDK-8277946): NMT: Remove VM.native_memory shutdown jcmd command option
 * [JDK-8299848](https://bugs.openjdk.org/browse/JDK-8299848): NMT: Remove VM.native_memory shutdown jcmd command option (**CSR**)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/1112/head:pull/1112` \
`$ git checkout pull/1112`

Update a local copy of the PR: \
`$ git checkout pull/1112` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/1112/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1112`

View PR using the GUI difftool: \
`$ git pr show -t 1112`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1112.diff">https://git.openjdk.org/jdk17u-dev/pull/1112.diff</a>

</details>

### CODE REVIEW

**Comment by tstuefe** [comment]
Test errors unrelated.

**Comment by GoeLin** [comment]
Pre-submit tests are failing! Check!
Also, Backport JDK-8299846 must be "backport of" JDK-8277946", the Enhancement, and not 
"backport of" JDK-8277947 which is the CSR.  You can fix this by adding the correct link under More->Link
and deleting the old link.

**Comment by tstuefe** [comment]
> Pre-submit tests are failing! Check! Also, Backport JDK-8299846 must be "backport of" JDK-8277946", the Enhancement, and not "backport of" JDK-8277947 which is the CSR. You can fix this by adding the correct link under More->Link and deleting the old link.

Okay. I fought Skara all the way for this one. I fixed the issue. As before, the test errors on Windows x64 seem related to GHA infrastructure. Just to be sure I'll schedule tests for tonight at SAP.

**Comment by GoeLin** [comment]
Thanks. It's sufficient that you make clear you have checkted the tests and it is unrelated.  In the past, we submitted two!!! changes where the test that came with the change had Java 17 syntax!

**Review by MBaesken — APPROVED** [review]

**Comment by tstuefe** [comment]
Thanks @GoeLin and @MBaesken !

/integrate

**Pull request closed without merging**
