### PR TITLE
8287003: InputStreamReader::read() can return zero despite writing a char in the buffer

### PR DESCRIPTION
**Pull request by toddjonker**
Backports a fix for a potential data-loss defect from JDK19 to JDK17.

This change is not clean, but the conflict is minimal and localized to `StreamDecoder.java`.

Viewing this diff alongside the original fix [here](https://github.com/openjdk/jdk/commit/6520843f86f638fe4d1e5b3358fab5799daca654?diff=unified&w=0#diff-e720d7662e29697b70409dd2aae7864f4e89d4bec33aa8d2ffce83cab365115eR184-R227) and expanding context upward a bit should be illuminating.  The conflict is due to structural/indentation difference when the lock acquisition at L158 was hoisted into a separate method.  That happened [here](https://github.com/openjdk/jdk/commit/9583e3657e43cc1c6f2101a64534564db2a9bd84?diff=unified&w=1#diff-e720d7662e29697b70409dd2aae7864f4e89d4bec33aa8d2ffce83cab365115eL154-L190) (wherein this file has an ugly diff obscuring relatively simple changes).

Additional testing:
- [x] New regression test fails without the fix, passes with it
- [x] linux-x86_64-server-release: `JTREG_KEYWORDS="\!headful & \!external-dep & \!printer" make test` (tier1-3)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8287003](https://bugs.openjdk.org/browse/JDK-8287003) needs maintainer approval
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8287003](https://bugs.openjdk.org/browse/JDK-8287003): InputStreamReader::read() can return zero despite writing a char in the buffer (**Bug** - P4 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2726/head:pull/2726` \
`$ git checkout pull/2726`

Update a local copy of the PR: \
`$ git checkout pull/2726` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2726/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2726`

View PR using the GUI difftool: \
`$ git pr show -t 2726`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2726.diff">https://git.openjdk.org/jdk17u-dev/pull/2726.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2726#issuecomment-2278668752)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by toddjonker** [comment]
/approval request Backports to JDK17 a fix for a potential data-loss defect fixed in JDK19.

This change is not clean, but the conflict is minimal and localized to `StreamDecoder.java`; see PR for explanation of the structural conflict.

Passes headless tests tier 1-3.

**Pull request closed without merging**
