### PR TITLE
8276036: The value of full_count in the message of insufficient codecache is wrong

### PR DESCRIPTION
**Pull request by elifaslan1**
Clean backport to fix the value of full_count in the message of insufficient codecache.

GHA tested

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8276036](https://bugs.openjdk.org/browse/JDK-8276036) needs maintainer approval

### Issue
 * [JDK-8276036](https://bugs.openjdk.org/browse/JDK-8276036): The value of full_count in the message of insufficient codecache is wrong (**Bug** - P5 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1742/head:pull/1742` \
`$ git checkout pull/1742`

Update a local copy of the PR: \
`$ git checkout pull/1742` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1742/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1742`

View PR using the GUI difftool: \
`$ git pr show -t 1742`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1742.diff">https://git.openjdk.org/jdk17u-dev/pull/1742.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1742#issuecomment-1726289153)

### CODE REVIEW

**Comment by shipilev** [comment]
I think you need to rename this PR to "Backport 61cb4bc6b0252536364a86f38ff2e5c8c7ab610b" to get this properly hooked.

**Comment by elifaslan1** [comment]
/approval JDK-8276036 request “Clean backport. Fix a wrong value of full_count in the message of insufficient codecache Low risk. GHA tested”

**Pull request closed without merging**
