### PR TITLE
8304074: [JMX] Add an approximation of total bytes allocated on the Java heap by the JVM

### PR DESCRIPTION
**Pull request by phohensee**
I'd like to backport the definition and implementation of com.sun.management.ThreadMXBean.getTotalThreadAllocatedBytes to 17u. The backport CSR is [JDK-8320375](https://bugs.openjdk.org/browse/JDK-8320375). A follow-up bugfix backport of [JDK-8313081](https://bugs.openjdk.org/browse/JDK-8313081) will be done following this backport. The combined backports have been in production at Amazon for two months with no issues. The backport uses the reserved6 slot in jmm.h in order to preserve binary compatibility with 17u. Per current policy, there is no update to JMM_VERSION in jmm.h and the new method is marked
```
@since 17.0.11
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change requires CSR request [JDK-8320375](https://bugs.openjdk.org/browse/JDK-8320375) to be approved
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8304074](https://bugs.openjdk.org/browse/JDK-8304074) needs maintainer approval

### Issues
 * [JDK-8304074](https://bugs.openjdk.org/browse/JDK-8304074): [JMX] Add an approximation of total bytes allocated on the Java heap by the JVM (**Enhancement** - P4 - Approved)
 * [JDK-8320375](https://bugs.openjdk.org/browse/JDK-8320375): [JMX] Add an approximation of total bytes allocated on the Java heap by the JVM (**CSR**)

### Reviewers
 * [Volker Simonis](https://openjdk.org/census#simonis) (@simonis - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1971/head:pull/1971` \
`$ git checkout pull/1971`

Update a local copy of the PR: \
`$ git checkout pull/1971` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1971/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1971`

View PR using the GUI difftool: \
`$ git pr show -t 1971`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1971.diff">https://git.openjdk.org/jdk17u-dev/pull/1971.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1971#issuecomment-1817993215)

### CODE REVIEW

**Review by simonis — APPROVED** [review]
Looks good to me. Thanks for doing the downport.

**Comment by phohensee** [comment]
Thanks for the quick review of both this PR and the CSR. Now waiting on CSR approval.

**Comment by phohensee** [comment]
/approval request Almost clean backport of purely additive JMX feature (doesn't change existing code). In production at Amazon for over two months.

**Pull request closed without merging**
