### PR TITLE
8322883: [BACKOUT] 8225377: type annotations are not visible to javac plugins across compilation boundaries

### PR DESCRIPTION
**Pull request by GoeLin**
This is a backout needed as the change is too intrusive for a backport.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8322883](https://bugs.openjdk.org/browse/JDK-8322883) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8322883](https://bugs.openjdk.org/browse/JDK-8322883): [BACKOUT] 8225377: type annotations are not visible to javac plugins across compilation boundaries (**Bug** - P3 - Approved)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2102/head:pull/2102` \
`$ git checkout pull/2102`

Update a local copy of the PR: \
`$ git checkout pull/2102` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2102/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2102`

View PR using the GUI difftool: \
`$ git pr show -t 2102`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2102.diff">https://git.openjdk.org/jdk17u-dev/pull/2102.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2102#issuecomment-1877196857)

### CODE REVIEW

**Comment by GoeLin** [comment]
GHA failure: test job never ran. Restarting tests by merging head.

**Review by shipilev — COMMENTED** [review]
So this backs out these two?
 - https://github.com/openjdk/jdk17u-dev/commit/3a2bf8e570d5e329f22b4eaf5e90fef8cd14f8b2
 - https://github.com/openjdk/jdk17u-dev/commit/c44bd2bd09e43b719b87eb1f8e153560c5901a6b

For extra safety, I would have tried to just `git revert` both from jdk17u-dev. This would prove mechanically that the revert is clean. Not sure if that is how you did it.

**Comment by GoeLin** [comment]
Yes, it backs out the two changes. I patched the 21u change.  I first tried git revert, but later I figured I used the older change, which did not succeed.
The second change fixes within the newly added code.

**Review by shipilev — APPROVED** [review]
OK then!

Minor: I think the `@bug` line here is not restored to original:
https://github.com/openjdk/jdk17u-dev/commit/3a2bf8e570d5e329f22b4eaf5e90fef8cd14f8b2?diff=unified&w=0#diff-4dd7943869aeaa2236b89ff67fdedbf28bc58667354307dc7cb717c5f667c496L26-R26

**Comment by GoeLin** [comment]
Thanks for the review, I fixed the @bug.

**Pull request closed without merging**
