### PR TITLE
8282382: Report glibc malloc tunables in error reports

### PR DESCRIPTION
**Pull request by tstuefe**
Would like to backport to jdk17u. Helps with C-heap performance analysis. Low risk. Does not apply cleanly (copyright).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8282382](https://bugs.openjdk.java.net/browse/JDK-8282382): Report glibc malloc tunables in error reports

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17u-dev pull/329/head:pull/329` \
`$ git checkout pull/329`

Update a local copy of the PR: \
`$ git checkout pull/329` \
`$ git pull https://git.openjdk.java.net/jdk17u-dev pull/329/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 329`

View PR using the GUI difftool: \
`$ git pr show -t 329`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17u-dev/pull/329.diff">https://git.openjdk.java.net/jdk17u-dev/pull/329.diff</a>

</details>

### CODE REVIEW

**Comment by RealCLanger** [comment]
Hi @tstuefe,  If it's just about resolving the copyright, you can use the "/clean" command in this PR and it will be marked as ready. 😄

**Comment by tstuefe** [comment]
> Hi @tstuefe, If it's just about resolving the copyright, you can use the "/clean" command in this PR and it will be marked as ready. smile

Good point.

/clean

**Comment by tstuefe** [comment]
Marked as clean, since all it needed was a copyright change
/clean

**Pull request closed without merging**
