### PR TITLE
8278065: Refactor subclassAudits to use ClassValue

### PR DESCRIPTION
**Pull request by rkennke**
This backports the fix for JDK-8278065, which fixes a number of small issues with the preceding change for JDK-8277072.
The original change has baked for several weeks in jdk19 and applies with some fuzz, but no conflicts.

Testing:
 - [x] tier1
 - [x] tier2
 - [x] tier3

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8278065](https://bugs.openjdk.java.net/browse/JDK-8278065): Refactor subclassAudits to use ClassValue

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17u-dev pull/260/head:pull/260` \
`$ git checkout pull/260`

Update a local copy of the PR: \
`$ git checkout pull/260` \
`$ git pull https://git.openjdk.java.net/jdk17u-dev pull/260/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 260`

View PR using the GUI difftool: \
`$ git pr show -t 260`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17u-dev/pull/260.diff">https://git.openjdk.java.net/jdk17u-dev/pull/260.diff</a>

</details>

### CODE REVIEW

**Comment by TheRealMDoerr** [comment]
Unfortunately, following the instructions suggested by Skara messes up the PR. The diff contains both backports and the clean label is lost. I had the same problems when trying it. (What works is rebase and force-push which is not particularly nice, either.) I don't know what would happen when integrating it this way. Is the best way in this situation to just throw it away and redo it?

**Comment by rkennke** [comment]
> Unfortunately, following the instructions suggested by Skara messes up the PR. The diff contains both backports and the clean label is lost. I had the same problems when trying it. (What works is rebase and force-push which is not particularly nice, either.) I don't know what would happen when integrating it this way. Is the best way in this situation to just throw it away and redo it?

As far as I know, the recommended way is to manually merge from upstream/master, push it to the PR branch, wait until it is flagged with clean label again, and then go. That's what I would do, unless you object to this plan.

**Comment by TheRealMDoerr** [comment]
Oh, ok. That's fine. Thanks for the hint.

**Pull request closed without merging**
