### PR TITLE
8290711: assert(false) failed: infinite loop in PhaseIterGVN::optimize

### PR DESCRIPTION
**Pull request by GoeLin**
I had to resolve the first chunk in phaseX.cpp because 8289051: C2: Cleanup PhaseCCP::analyze()  is not in 17.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8290711](https://bugs.openjdk.org/browse/JDK-8290711): assert(false) failed: infinite loop in PhaseIterGVN::optimize

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/761/head:pull/761` \
`$ git checkout pull/761`

Update a local copy of the PR: \
`$ git checkout pull/761` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/761/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 761`

View PR using the GUI difftool: \
`$ git pr show -t 761`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/761.diff">https://git.openjdk.org/jdk17u-dev/pull/761.diff</a>

</details>

### CODE REVIEW

**Comment by TheRealMDoerr** [comment]
Fix looks good, but I think we should also have TestInfiniteIGVNAfterCCP.java.

**Comment by GoeLin** [comment]
Thanks, added the test!

**Review by TheRealMDoerr — APPROVED** [review]
LGTM. Thanks for backporting!

**Pull request closed without merging**
