### PR TITLE
8299677: Formatter.format might take a long time to format an integer or floating-point

### PR DESCRIPTION
**Pull request by phohensee**
Simple almost clean backport of a potential DOS attack vector fix. Copyright date conflict plus changed
```
Flags.contains(f, Flags.ZERO_PAD)
```
to
```
f.contains(Flags.ZERO_PAD)
```
Passes new and old Formatter tests.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8299677](https://bugs.openjdk.org/browse/JDK-8299677): Formatter.format might take a long time to format an integer or floating-point (**Bug** - P4)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1077/head:pull/1077` \
`$ git checkout pull/1077`

Update a local copy of the PR: \
`$ git checkout pull/1077` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1077/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1077`

View PR using the GUI difftool: \
`$ git pr show -t 1077`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1077.diff">https://git.openjdk.org/jdk17u-dev/pull/1077.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1077#issuecomment-1385763133)

### CODE REVIEW

**Comment by RealCLanger** [comment]
The test seems to fail in GHA...

**Review by TheRealMDoerr — APPROVED** [review]
LGTM.

**Comment by phohensee** [comment]
keep open.

**Comment by shipilev** [comment]
Just pushed jtreg 7.3.1 update to 17u-dev. Try to merge from master and see if test works now, @phohensee.

**Comment by TheRealMDoerr** [comment]
The merge has messed up this PR. Can it be repaired or should we use a new one?

**Review by TheRealMDoerr — APPROVED** [review]

**Comment by phohensee** [comment]
Indeed it does. :) Thanks for the review!

**Comment by phohensee** [comment]
Martin, may I ask for a review of https://github.com/openjdk/jdk11u-dev/pull/1667 as well? It's a clean backport from this one.

**Comment by phohensee** [comment]
/integrate

Approved.

**Pull request closed without merging**
