### PR TITLE
8296545: C2 Blackholes should allow load optimizations

### PR DESCRIPTION
**Pull request by shipilev**
Unclean backport to improve Blackhole performance and match it to released JDK 20.
The backport is unclean because there are two little conflicts:
  1. The context conflict in `MemBarNode::make`, where the `MemBarStoreStore` was moved to another place. I resolved the conflict by hand: accepted only the `Blackhole` case removal.
  2. IR Framework needs `MUL_I` constant for test to work.

Additional testing:
  - [x] macos-aarch64-server-fastdebug, `compiler/irTests/blackhole` (includes new test)
  - [x] Eyeballing perfasm outputs with/without this patch

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8296545](https://bugs.openjdk.org/browse/JDK-8296545): C2 Blackholes should allow load optimizations

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1273/head:pull/1273` \
`$ git checkout pull/1273`

Update a local copy of the PR: \
`$ git checkout pull/1273` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1273/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1273`

View PR using the GUI difftool: \
`$ git pr show -t 1273`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1273.diff">https://git.openjdk.org/jdk17u-dev/pull/1273.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1273#issuecomment-1514761116)

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
LGTM.

**Comment by GoeLin** [comment]
What is wrong with the Pre-submit tests?

**Comment by shipilev** [comment]
> What is wrong with the Pre-submit tests?

Missing https://github.com/openjdk/jdk17u-dev/commit/ebde2fb7d155938e295ecaeb006412f9e49e9d01, apparently. Remerged from master.

**Comment by shipilev** [comment]
There was a little conflict in `memnode.cpp` due to https://github.com/openjdk/jdk17u-dev/commit/e6e6bedf7b7898a88dedce79600a473832871e9c coming in first, I pulled and remerged.  This basically eliminates this part of the original difference: "The context conflict in MemBarNode::make, where the MemBarStoreStore was moved to another place. I resolved the conflict by hand: accepted only the Blackhole case removal."

**Comment by shipilev** [comment]
@TheRealMDoerr, @GoeLin, if you can ack again, please?

**Review by TheRealMDoerr — APPROVED** [review]
Still good.

**Comment by shipilev** [comment]
Thank you! Testing is still good. GHAs are green. Push approval is there.

/integrate

**Pull request closed without merging**
