### PR TITLE
8313816: Accessing jmethodID might lead to spurious crashes

### PR DESCRIPTION
**Pull request by jbachorik**
Reviewed-by: coleenp

A minor update required for the backport - the original changeset is using `nullptr` while the JDK 17 version is using `NULL`

Attaching the conflicting file for posterity.

[instanceKlass.cpp](https://github.com/openjdk/jdk17u-dev/files/13504341/InstanceKlass_conflict.txt)

Additionally,  I had to bring in a few test support classes as well - https://github.com/openjdk/jdk17u-dev/pull/2001/commits/d59ac82d5b4d3cace38e38cb7747642aaee98ba4

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8313816](https://bugs.openjdk.org/browse/JDK-8313816) needs maintainer approval
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8313816](https://bugs.openjdk.org/browse/JDK-8313816): Accessing jmethodID might lead to spurious crashes (**Bug** - P3 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2001/head:pull/2001` \
`$ git checkout pull/2001`

Update a local copy of the PR: \
`$ git checkout pull/2001` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2001/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2001`

View PR using the GUI difftool: \
`$ git pr show -t 2001`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2001.diff">https://git.openjdk.org/jdk17u-dev/pull/2001.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2001#issuecomment-1836262602)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
Looks fine, though it appears that JDK 17 uses nullptr.

**Review by phohensee — COMMENTED** [review]
Looks like a clean backport from the 17u PR, except for replacing nullptr with NULL as you note, and the unused declaration of metaspaceSharedRegionAlignment in WhiteBox.java. The latter doesn't seem have a definition in 11u: if so, please remove it.

**Comment by jbachorik** [comment]
@phohensee I think your last comment was supposed to go to https://github.com/openjdk/jdk11u-dev/pull/2321 

I checked for the addition of `metaspaceSharedRegionAlignment` in this PR and the method is already there, so I think you were really talking about the 11u backport PR.

**Comment by jbachorik** [comment]
/approval request Please, approve this backport of a fix improving stability of stack sampling profilers. The changed code is relevant only to retransformed method and the change itself is very simple - just nulling out any dangling pointers.

**Comment by GoeLin** [comment]
@jbachorik, removing the fix-request label. Feel free to label again if backported to 21.

**Comment by jbachorik** [comment]
@GoeLin Do I understand it correctly that the backports now to be serialized? Eg. I need to do 21 backport first, then 17 and then 11, and I can not do all of them at once even though they would be independent?

**Pull request closed without merging**
