### PR TITLE
8318608: Enable parallelism in vmTestbase/nsk/stress/threads tests

### PR DESCRIPTION
**Pull request by elifaslan1**
Clean backport of Enable parallelism in vmTestbase/nsk/stress/threads tests 

GHA Tested

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8318608](https://bugs.openjdk.org/browse/JDK-8318608) needs maintainer approval

### Issue
 * [JDK-8318608](https://bugs.openjdk.org/browse/JDK-8318608): Enable parallelism in vmTestbase/nsk/stress/threads tests (**Enhancement** - P4 - Approved)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2108/head:pull/2108` \
`$ git checkout pull/2108`

Update a local copy of the PR: \
`$ git checkout pull/2108` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2108/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2108`

View PR using the GUI difftool: \
`$ git pr show -t 2108`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2108.diff">https://git.openjdk.org/jdk17u-dev/pull/2108.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2108#issuecomment-1879492996)

### CODE REVIEW

**Comment by elifaslan1** [comment]
/approval request Enables parallelism in vmTestbase/nsk/stress/threads tests. Clean backport. Tests pass.

**Comment by GoeLin** [comment]
Hi @elifaslan1, why did you  close this instead of integrating it?

**Comment by elifaslan1** [comment]
I was cleaning up my old branches and it must have been deleted accidentally.

**Review by shipilev — APPROVED** [review]

**Pull request closed without merging**
