### PR TITLE
8159927: Add a test to verify JMOD files created in the images do not have debug symbols

### PR DESCRIPTION
**Pull request by SoniaZaldana**
Hi all, 

This PR contains a backport of [6c0bebccb0092d9726eb89a054e023e92edf7ca6](https://github.com/openjdk/jdk/commit/6c0bebccb0092d9726eb89a054e023e92edf7ca6). 

Patch is not clean. Test won't build in 17 because it can't find ```import jdk.internal.util.OperatingSystem```. 

This class was introduced in 21 as part of [JDK-8303485](https://bugs.openjdk.org/browse/JDK-8303485). 

I've worked around that by removing the dependency to that utility function and checking the operating system with ```System.getProperty("os.name")```. 

Testing: 
- [x] Added test case passes 

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8159927](https://bugs.openjdk.org/browse/JDK-8159927) needs maintainer approval

### Issue
 * [JDK-8159927](https://bugs.openjdk.org/browse/JDK-8159927): Add a test to verify JMOD files created in the images do not have debug symbols (**Enhancement** - P4 - Approved)

### Reviewers
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2305/head:pull/2305` \
`$ git checkout pull/2305`

Update a local copy of the PR: \
`$ git checkout pull/2305` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2305/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2305`

View PR using the GUI difftool: \
`$ git pr show -t 2305`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2305.diff">https://git.openjdk.org/jdk17u-dev/pull/2305.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2305#issuecomment-2007548138)

### CODE REVIEW

**Comment by SoniaZaldana** [comment]
GHA Failures:

- Unrelated RISC-V failure.
- Unrelated test failures: ```java/lang/String/StringRepeat.java``` in ```jdk/tier1 part1```. I'm seeing these failures intermittently across all PRs.

**Comment by GoeLin** [comment]
Hi @SoniaZaldana, did you see the comment in the JBS issue?

**Comment by SoniaZaldana** [comment]
Hi @GoeLin, I saw it. I added follow up PRs for both 17u and 21u. Thanks :)

**Comment by amosshi** [comment]
SAP nightlies passed on `2024-04-17,19,20`

**Comment by amosshi** [comment]
Hi @SoniaZaldana
- Would you please re-trigger the `OpenJDK GHA Sanity Checks` since now we see some errors - although it looks to me not caused by current PR
- I tried to re-trigger it well I don't have the permission to re-trigger.

**Review by RealLucy — APPROVED** [review]
LGTM.

**Comment by amosshi** [comment]
/approval request "Backporting for parity with 17.0.12-oracle. Un-Clean backport. SAP nightlies passed on 2024-04-17,19,20”

**Pull request closed without merging**
