### PR TITLE
8328638: Fallback option for POST-only OCSP requests

### PR DESCRIPTION
**Pull request by shipilev**
Improves JDK OCSP compatibility with some real world OCSP responders. Starts to be a problem since JDK 17 introduced GET OCSP requests. The default behavior is not changed.

The backports are almost clean, I just had to add the import for `Locale` and `Debug` in one of the files. `Locale` is added in mainline by [JDK-8312443](https://bugs.openjdk.org/browse/JDK-8312443), which I do not want to backport at the moment, as it changes existing security code. `Debug` is added by [JDK-8179502](https://bugs.openjdk.org/browse/JDK-8179502), which is also not amenable for easy backporting.

Additional testing:
 - [x] `jdk_security` pass, includes new test cases

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8328810](https://bugs.openjdk.org/browse/JDK-8328810) to be approved
- [x] [JDK-8328638](https://bugs.openjdk.org/browse/JDK-8328638) needs maintainer approval
- [x] [JDK-8329213](https://bugs.openjdk.org/browse/JDK-8329213) needs maintainer approval

### Issues
 * [JDK-8328638](https://bugs.openjdk.org/browse/JDK-8328638): Fallback option for POST-only OCSP requests (**Enhancement** - P4 - Approved)
 * [JDK-8329213](https://bugs.openjdk.org/browse/JDK-8329213): Better validation for com.sun.security.ocsp.useget option (**Enhancement** - P4 - Approved)
 * [JDK-8328810](https://bugs.openjdk.org/browse/JDK-8328810): Fallback option for POST-only OCSP requests (**CSR**)

### Reviewers
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2338/head:pull/2338` \
`$ git checkout pull/2338`

Update a local copy of the PR: \
`$ git checkout pull/2338` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2338/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2338`

View PR using the GUI difftool: \
`$ git pr show -t 2338`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2338.diff">https://git.openjdk.org/jdk17u-dev/pull/2338.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2338#issuecomment-2031668437)

### CODE REVIEW

**Review by mrserb — APPROVED** [review]

**Comment by shipilev** [comment]
/approval 8328638 request Improves JDK OCSP compatibility with some real world OCSP responders. Starts to be a problem since JDK 17 introduced GET OCSP requests. Risk is medium-low, as default behavior is not changed, and the code is simple. Passes full jdk_security tests, eyeballed logs show the expected behavior.

/approval 8329213 request Option checking followup for JDK-8328638. Risk is low, simple refactoring. Passes full jdk_security tests, eyeballed logs show the expected behavior.

**Comment by shipilev** [comment]
@jerboaa, @RealCLanger -- what do you think about this one? Would be nice to unblock JDK 17 for folks.

**Comment by RealCLanger** [comment]
Makes sense.

/approve

**Pull request closed without merging**
