### PR TITLE
8277654: Shenandoah: Don't produce new memory state in C2 LRB runtime call

### PR DESCRIPTION
**Pull request by earthling-amzn**
Testing:

- [x] hotspot_gc_shenandoah
- [x] dacapo
- [x] extremem
- [x] specjbb2015
- [x] hyperalloc

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8277654](https://bugs.openjdk.org/browse/JDK-8277654): Shenandoah: Don't produce new memory state in C2 LRB runtime call (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1448/head:pull/1448` \
`$ git checkout pull/1448`

Update a local copy of the PR: \
`$ git checkout pull/1448` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1448/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1448`

View PR using the GUI difftool: \
`$ git pr show -t 1448`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1448.diff">https://git.openjdk.org/jdk17u-dev/pull/1448.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1448#issuecomment-1593603812)

### CODE REVIEW

**Comment by shipilev** [comment]
I think it needs JDK-8287227 as the follow-up too, see linked issues in the JIRA.

**Comment by earthling-amzn** [comment]
Should JDK-8287227 come in a separate PR? or should I cherry-pick that change into this PR?

**Comment by shipilev** [comment]
> Should JDK-8287227 come in a separate PR? or should I cherry-pick that change into this PR?

What you did is right: a dependent PR. Get the push approval for both PRs, and then integrate them one by one.

**Pull request closed without merging**
