### PR TITLE
8269821: Remove is-queue-active check in inner loop of write_ref_array_pre_work

### PR DESCRIPTION
**Pull request by shipilev**
Clean backport to improve G1 performance and provide grounds for next backports.

@tschatzl, do you want to ack this?

Additional testing:
 - [x] Linux x86_64 fastdebug `tier1`
 - [x] Linux x86_64 fastdebug `tier2`

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8269821](https://bugs.openjdk.org/browse/JDK-8269821): Remove is-queue-active check in inner loop of write_ref_array_pre_work

### Reviewers
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**) ⚠️ Review applies to [e2ae6b26](https://git.openjdk.org/jdk17u-dev/pull/905/files/e2ae6b26ef633531b79a8155a432c5bb7b3a9fc0)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/905/head:pull/905` \
`$ git checkout pull/905`

Update a local copy of the PR: \
`$ git checkout pull/905` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/905/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 905`

View PR using the GUI difftool: \
`$ git pr show -t 905`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/905.diff">https://git.openjdk.org/jdk17u-dev/pull/905.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/905#issuecomment-1321792970)

### CODE REVIEW

**Comment by shipilev** [comment]
@tschatzl, want to ack this too? :)

**Review by tschatzl — APPROVED** [review]
Lgtm.

Sorry, I did not see the ping the first time.

**Comment by shipilev** [comment]
Thank you! I am going to rebase it, retest it, and then integrate.

**Comment by shipilev** [comment]
Testing is green, GHA is green, I am integrating.

/integrate

**Pull request closed without merging**
