### PR TITLE
8290417: CDS cannot archive lamda proxy with useImplMethodHandle

### PR DESCRIPTION
**Pull request by jankratochvil**
This bug has been faced by a customer and this backport does work for them.
I am not yet an Author - I do not have JBS account.
I have run the testsuite on Linux x86_64 and there is no change of the results. Two new testcases are added and they are both Passing. The testcases are still Passing after backporting them to 17u-dev.
```
+Passed: runtime/cds/appcds/LambdaWithUseImplMethodHandle.java
+Passed: runtime/cds/appcds/dynamicArchive/DynamicLambdaWithUseImplMethodHandle.java
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8290417](https://bugs.openjdk.org/browse/JDK-8290417): CDS cannot archive lamda proxy with useImplMethodHandle

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/575/head:pull/575` \
`$ git checkout pull/575`

Update a local copy of the PR: \
`$ git checkout pull/575` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/575/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 575`

View PR using the GUI difftool: \
`$ git pr show -t 575`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/575.diff">https://git.openjdk.org/jdk17u-dev/pull/575.diff</a>

</details>

### CODE REVIEW

**Comment by jankratochvil** [comment]
The failed macos-x64 / build is unrelated, going to notify @gdams.

**Comment by gdams** [comment]
> The failed macos-x64 / build is unrelated, going to notify @gdams.

@jankratochvil That's a weird error, looks like `wget` had a moment of craziness. Can you try restarting the failed build?

**Comment by jankratochvil** [comment]
All the pre-submit checks have passed now (incl. macos-x64 after its restart).

**Pull request closed without merging**
