### PR TITLE
8295724: VirtualMachineError: Out of space in CodeCache for method handle intrinsic

### PR DESCRIPTION
**Pull request by TheRealMDoerr**
Mostly clean backport of [JDK-8295724](https://bugs.openjdk.org/browse/JDK-8295724). Manual integration was needed because of unrelated changes in the surrounding code. There's only one significant difference:
The hunk from gcBehaviours.cpp needs to get integrated into `nmethod::is_unloading()` because the usage of `IsUnloadingBehaviour::current()` is there before [JDK-8290025](https://bugs.openjdk.org/browse/JDK-8290025).
Includes trivial fix for [JDK-8298947](https://bugs.openjdk.org/browse/JDK-8298947)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8295724](https://bugs.openjdk.org/browse/JDK-8295724): VirtualMachineError: Out of space in CodeCache for method handle intrinsic
 * [JDK-8298947](https://bugs.openjdk.org/browse/JDK-8298947): compiler/codecache/MHIntrinsicAllocFailureTest.java fails intermittently

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**) ⚠️ Review applies to [8f833de1](https://git.openjdk.org/jdk17u-dev/pull/951/files/8f833de11ca8e6fd0e5ed4bfbb118af951c1c40b)
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/951/head:pull/951` \
`$ git checkout pull/951`

Update a local copy of the PR: \
`$ git checkout pull/951` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/951/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 951`

View PR using the GUI difftool: \
`$ git pr show -t 951`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/951.diff">https://git.openjdk.org/jdk17u-dev/pull/951.diff</a>

</details>

### CODE REVIEW

**Comment by mathjeff** [comment]
Thanks!

**Review by vnkozlov — COMMENTED** [review]
I start testing.

**Review by vnkozlov — APPROVED** [review]
My testing of jdk17u with these changes passed.

**Comment by TheRealMDoerr** [comment]
Thanks a lot for testing!

**Review by MBaesken — APPROVED** [review]

**Comment by TheRealMDoerr** [comment]
Thanks for the reviews!

**Comment by kenyee** [comment]
Which version of JDK17 did this make it into?

We still see it w/ 17.0.7

**Comment by TheRealMDoerr** [comment]
It was released with 17.0.7. Note that it only helps when -XX:+SegmentedCodeCache is enabled. And it still doesn't make the problem impossible when an insane amount of method handle intrinsics gets allocated. There are other solutions under discussion, but not yet implemented (https://bugs.openjdk.org/browse/JDK-8296336).
Also note that the backport contains a bug which is fixed for 17.0.8: https://bugs.openjdk.org/browse/JDK-8305088

**Pull request closed without merging**
