### PR TITLE
8282094: [REDO] Parallel: Refactor PSCardTable::scavenge_contents_parallel

### PR DESCRIPTION
**Pull request by reinrich**
This backport is a dependency for the backport of https://bugs.openjdk.org/browse/JDK-8310031
Applies cleanly. Only a trivial renaming is required.
Risk is medium. We've done the downstream backport already many weeks ago.

I've tested on x86_64:
jdk:tier1       TEST_VM_OPTS="-XX:+UseParallelGC"
langtools:tier1 TEST_VM_OPTS="-XX:+UseParallelGC"

Local CI Testing:
The fix passed our CI testing (e.g. 2024-02-24): JTReg tests: tier1-4 of hotspot and jdk. All of Langtools and jaxp. JCK, SPECjvm2008, SPECjbb2015, Renaissance Suite, and SAP specific tests (also with ParallelGC).
Testing was done with fastdebug builds on the main platforms and also on Linux/PPC64le.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8282094](https://bugs.openjdk.org/browse/JDK-8282094) needs maintainer approval

### Issue
 * [JDK-8282094](https://bugs.openjdk.org/browse/JDK-8282094): [REDO] Parallel: Refactor PSCardTable::scavenge_contents_parallel (**Enhancement** - P4 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [c64debe9](https://git.openjdk.org/jdk17u-dev/pull/2228/files/c64debe959535a9ece5f068e32d2dbb8c65586c7)
 * [Zhengyu Gu](https://openjdk.org/census#zgu) (@zhengyu123 - **Reviewer**) ⚠️ Review applies to [c64debe9](https://git.openjdk.org/jdk17u-dev/pull/2228/files/c64debe959535a9ece5f068e32d2dbb8c65586c7)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2228/head:pull/2228` \
`$ git checkout pull/2228`

Update a local copy of the PR: \
`$ git checkout pull/2228` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2228/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2228`

View PR using the GUI difftool: \
`$ git pr show -t 2228`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2228.diff">https://git.openjdk.org/jdk17u-dev/pull/2228.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2228#issuecomment-1962298278)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Review by zhengyu123 — APPROVED** [review]
LGTM

**Comment by reinrich** [comment]
So I'm trying to merge master after integration of the dependent PR #2227. Why do I get conflicts?? The backport applied cleanly on #2227

**Comment by GoeLin** [comment]
Hi,
this is because you merge two changes, the one that sits under this one and the copy of it that was pushed to jdk17u-dev. They are identical, but Github does not grok this. This is very annoying.  I have seen errors before in the parts merged automatically.

**Comment by reinrich** [comment]
Test failure is unrelated (https://bugs.openjdk.org/browse/JDK-8326960)

**Pull request closed without merging**
