### PR TITLE
8325194: GHA: Add macOS M1 testing

### PR DESCRIPTION
**Pull request by gdams**
Now that macOS M1 executors are [available in GitHub actions](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/) it makes sense to move the build to run on M1 (rather than cross-compiled) and also enable testing on the platform.

Applies cleanly other than the following:

- `.github/actions/get-jtreg/action.yml` I also integrated https://github.com/openjdk/jdk/commit/3c91b59ef9c992718d73f2fc9fa50ad2ead78208 as it caused a regression in tip
- `make/conf/github-actions.conf` having the obvious difference in version numbers for the boot JDK (I also took the liberty of reordering them to be consistent with tip)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8325194](https://bugs.openjdk.org/browse/JDK-8325194) needs maintainer approval
- [x] Commit message must refer to an issue
- [x] [JDK-8325444](https://bugs.openjdk.org/browse/JDK-8325444) needs maintainer approval
- [x] [JDK-8309934](https://bugs.openjdk.org/browse/JDK-8309934) needs maintainer approval

### Issues
 * [JDK-8325194](https://bugs.openjdk.org/browse/JDK-8325194): GHA: Add macOS M1 testing (**Enhancement** - P4 - Approved)
 * [JDK-8325444](https://bugs.openjdk.org/browse/JDK-8325444): GHA: JDK-8325194 causes a regression (**Bug** - P3 - Approved)
 * [JDK-8309934](https://bugs.openjdk.org/browse/JDK-8309934): Update GitHub Actions to use JDK 17 for building jtreg (**Bug** - P4 - Approved)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2697/head:pull/2697` \
`$ git checkout pull/2697`

Update a local copy of the PR: \
`$ git checkout pull/2697` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2697/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2697`

View PR using the GUI difftool: \
`$ git pr show -t 2697`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2697.diff">https://git.openjdk.org/jdk17u-dev/pull/2697.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2697#issuecomment-2217240802)

### CODE REVIEW

**Review by MBaesken — APPROVED** [review]

**Comment by gdams** [comment]
/approval request backport applies cleanly (except for obvious boot JDK URL changes), affects CI only

**Pull request closed without merging**
