### PR TITLE
8293107: GHA: Bump to Ubuntu 22.04

### PR DESCRIPTION
**Pull request by shipilev**
This is a series of commits that bring 17u GHA close to mainline. The root change is Ubuntu 22.04 bump, but that one could not be tested alone, because GHA would be broken due to missing compilers, dependencies, etc. Therefore, I opted to do a bulk PR that contains a series of inter-dependent changes. This PR should bring 17u GHA to the good state, atomically.

The included changes are in separate commits, if you want to review them separately. But it would be easier to see the changes against JDK 22 GHA. There are differences against JDK 22 GHA, but those look minor, not breaking/fixing current GHA, and we can backport separately once we get JDK 17u GHA in shape.

Additional testing:
 - [x] GHA
 - [x] Eyeballing the difference between patched JDK 17u and JDK 22 GHA: [jdk17-jdk22-gha-diff.txt](https://github.com/openjdk/jdk17u-dev/files/12261456/jdk17-jdk22-gha-diff.txt)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8293107](https://bugs.openjdk.org/browse/JDK-8293107): GHA: Bump to Ubuntu 22.04 (**Enhancement** - P4)
 * [JDK-8293098](https://bugs.openjdk.org/browse/JDK-8293098): GHA: Harmonize GCC version handling for host and cross builds (**Enhancement** - P4)
 * [JDK-8293361](https://bugs.openjdk.org/browse/JDK-8293361): GHA: dump config.log in case of configure failure (**Bug** - P4)
 * [JDK-8295213](https://bugs.openjdk.org/browse/JDK-8295213): Run GHA manually with user-specified make and configure arguments (**Enhancement** - P4)
 * [JDK-8313428](https://bugs.openjdk.org/browse/JDK-8313428): GHA: Bump GCC versions for July 2023 updates (**Enhancement** - P4)
 * [JDK-8313707](https://bugs.openjdk.org/browse/JDK-8313707): GHA: Bootstrap sysroots with --variant=minbase (**Enhancement** - P4)

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1640/head:pull/1640` \
`$ git checkout pull/1640`

Update a local copy of the PR: \
`$ git checkout pull/1640` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1640/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1640`

View PR using the GUI difftool: \
`$ git pr show -t 1640`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1640.diff">https://git.openjdk.org/jdk17u-dev/pull/1640.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1640#issuecomment-1667322781)

### CODE REVIEW

**Comment by shipilev** [comment]
@RealCLanger, @TheRealMDoerr -- this approach makes sense to you? If so, I'll mark this PR ready for review. It would add the PR links to all affected issues, which I don't want to do unless we are going forward with this PR.

**Comment by RealCLanger** [comment]
> @RealCLanger, @TheRealMDoerr -- this approach makes sense to you? If so, I'll mark this PR ready for review. It would add the PR links to all affected issues, which I don't want to do unless we are going forward with this PR.

Yep, that makes sense. Thanks for the work, happy to review it.

**Review by RealCLanger — APPROVED** [review]
Looks good to me. Thanks for bringing GHA in 17u up to date.

**Comment by shipilev** [comment]
Thanks! I added 17u fix requests on all issues.

**Comment by GoeLin** [comment]
Please see my comment in [JDK-8293107](https://bugs.openjdk.org/browse/JDK-8293107)

**Comment by shipilev** [comment]
The discussion seem to be resolved. The recent GHA run is clean.

/integrate

**Pull request closed without merging**
