### PR TITLE
8293345: SunPKCS11 provider checks on PKCS11 Mechanism are problematic

### PR DESCRIPTION
**Pull request by GoeLin**
I backport this for parity with 17.0.15-oracle.

Config.java:
Resolve and adapt because of unsupported switch syntax.

SunPKCS11.java: I had to resolve becuase
"8301553: Support Password-Based Cryptography in SunPKCS11"
is not in 17. Context code has different control flow. 
Patched code is unchanged.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8293345](https://bugs.openjdk.org/browse/JDK-8293345) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8343498](https://bugs.openjdk.org/browse/JDK-8343498) to be approved

### Issues
 * [JDK-8293345](https://bugs.openjdk.org/browse/JDK-8293345): SunPKCS11 provider checks on PKCS11 Mechanism are problematic (**Enhancement** - P3 - Approved)
 * [JDK-8343498](https://bugs.openjdk.org/browse/JDK-8343498): SunPKCS11 provider checks on PKCS11 Mechanism are problematic (**CSR**)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)
 * [Martin Balao](https://openjdk.org/census#mbalao) (@martinuy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/3092/head:pull/3092` \
`$ git checkout pull/3092`

Update a local copy of the PR: \
`$ git checkout pull/3092` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/3092/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3092`

View PR using the GUI difftool: \
`$ git pr show -t 3092`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/3092.diff">https://git.openjdk.org/jdk17u-dev/pull/3092.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/3092#issuecomment-2517316173)
</details>

### CODE REVIEW

**Comment by GoeLin** [comment]
Hi @martinuy 
could you have a look at this change?
Thanks!

**Review by MBaesken — APPROVED** [review]

**Review by martinuy — APPROVED** [review]
Thanks for this contribution. Looks good to me.

**Comment by GoeLin** [comment]
Thanks for the reviews!

**Pull request closed without merging**
