### PR TITLE
8278163: --with-cacerts-src variable resolved after GenerateCacerts recipe setup

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
This PR backports the fix for resolving the --with-cacerts-src variable correctly as part of https://bugs.openjdk.java.net/browse/JDK-8278080.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8278163](https://bugs.openjdk.java.net/browse/JDK-8278163): --with-cacerts-src variable resolved after GenerateCacerts recipe setup

### Reviewers
 * [Severin Gehwolf](https://openjdk.java.net/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17u-dev pull/170/head:pull/170` \
`$ git checkout pull/170`

Update a local copy of the PR: \
`$ git checkout pull/170` \
`$ git pull https://git.openjdk.java.net/jdk17u-dev pull/170/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 170`

View PR using the GUI difftool: \
`$ git pr show -t 170`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17u-dev/pull/170.diff">https://git.openjdk.java.net/jdk17u-dev/pull/170.diff</a>

</details>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
This is the PR to backport https://bugs.openjdk.java.net/browse/JDK-8278163 to resolve the issue for the already merged dependent PR for https://bugs.openjdk.java.net/browse/JDK-8278080.

**Comment by andrew-m-leonard** [comment]
I've patched this PR to correctly mirror the head stream fix: https://github.com/openjdk/jdk/pull/6680/files
which Skara incorrectly created due to the dependent PR code change not being in master when the PR was created.

**Comment by andrew-m-leonard** [comment]
Can I get a review of this backport please?
The only reason it's not clean is because the Skara backport was created incorrectly as the dependent code which this fixes was not merged at that time (https://bugs.openjdk.java.net/browse/JDK-8278080), and thus the backport did not apply the 3 lines deletion part of the original upstream fix because those lines did not exist at that time.

**Review by jerboaa — CHANGES_REQUESTED** [review]
The reason this is not clean is the copyright change. The original change didn't include it: https://github.com/openjdk/jdk/commit/45da3aea22fd85f214e661b2c98631cb91ddb55d

Remove it and it'll show up as clean :)

**Comment by andrew-m-leonard** [comment]
Ah! nice one Severin, i'll change that.
Thanks
Andrew

**Review by jerboaa — APPROVED** [review]
You don't need the review, but it looks good to me anyway :)

**Comment by andrew-m-leonard** [comment]
Thank you @jerboaa

**Pull request closed without merging**
