### PR TITLE
8298649: JFR: RemoteRecordingStream support for checkpoint event sizes beyond u4

### PR DESCRIPTION
**Pull request by kvergizova**
I'd like to backport JDK-8298649 as a follow up fix for JDK-8298129 which is already approved for 17u.
The third hunk doesn't apply cleanly (JDK-8286396 is not in 17u), reapplied manually.
Tested with tier1 and jdk/jfr tests.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8298649](https://bugs.openjdk.org/browse/JDK-8298649): JFR: RemoteRecordingStream support for checkpoint event sizes beyond u4

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/1121/head:pull/1121` \
`$ git checkout pull/1121`

Update a local copy of the PR: \
`$ git checkout pull/1121` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/1121/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1121`

View PR using the GUI difftool: \
`$ git pr show -t 1121`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1121.diff">https://git.openjdk.org/jdk17u-dev/pull/1121.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by kvergizova** [comment]
Pre-submit failures are unrelated.

**Comment by kvergizova** [comment]
@phohensee, thanks for the reviews.
Could you please approve this PR once again?
Your previous approval was dismissed during main PR integration (https://github.com/openjdk/jdk17u-dev/pull/1102).

**Review by phohensee — APPROVED** [review]

**Pull request closed without merging**
