### PR TITLE
8321408: Add Certainly roots R1 and E1

### PR DESCRIPTION
**Pull request by shipilev**
Unclean backport to roll in two more root certificates and better parity.

I had to move the certificates in their proper places in 17u and regenerate the cacert checksum. (I am actually surprised we have to do this, but that must be because keystore type changed with [JDK-8275252](https://bugs.openjdk.org/browse/JDK-8275252))

Additional testing:
 - [x] `jdk/security/infra sun/security/lib/cacerts` tests pass with new certificates

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8321408](https://bugs.openjdk.org/browse/JDK-8321408) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8321408](https://bugs.openjdk.org/browse/JDK-8321408): Add Certainly roots R1 and E1 (**Enhancement** - P3 - Approved)

### Reviewers
 * [Goetz Lindenmaier](https://openjdk.org/census#goetz) (@GoeLin - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2217/head:pull/2217` \
`$ git checkout pull/2217`

Update a local copy of the PR: \
`$ git checkout pull/2217` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2217/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2217`

View PR using the GUI difftool: \
`$ git pr show -t 2217`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2217.diff">https://git.openjdk.org/jdk17u-dev/pull/2217.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2217#issuecomment-1957329878)

### CODE REVIEW

**Comment by shipilev** [comment]
/approval request Unclean backport to roll in two more root certificates and better parity. Relevant tests pass.

**Review by GoeLin — APPROVED** [review]
LGTM.
Yes, updating the hash is  a nuisance.

**Comment by shipilev** [comment]
/approval request Unclean backport to roll in two more root certificates and better parity. Relevant tests pass.

**Pull request closed without merging**
