### PR TITLE
8335912: Add an operation mode to the jar command when extracting to not overwriting existing files

### PR DESCRIPTION
**Pull request by alexeybakhtin**
Almost clean backport from JDK21u patch
The only manual merge is for jar.properties because of JDK-8302819 not backported to JDK17

JTREG tests passed

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8344651](https://bugs.openjdk.org/browse/JDK-8344651) to be approved
- [x] [JDK-8335912](https://bugs.openjdk.org/browse/JDK-8335912) needs maintainer approval

### Issues
 * [JDK-8335912](https://bugs.openjdk.org/browse/JDK-8335912): Add an operation mode to the jar command when extracting to not overwriting existing files (**Enhancement** - P5 - Approved)
 * [JDK-8344651](https://bugs.openjdk.org/browse/JDK-8344651): Add an operation mode to the jar command when extracting to not overwriting existing files (**CSR**)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)
 * [Martin Balao](https://openjdk.org/census#mbalao) (@martinuy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/3075/head:pull/3075` \
`$ git checkout pull/3075`

Update a local copy of the PR: \
`$ git checkout pull/3075` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/3075/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3075`

View PR using the GUI difftool: \
`$ git pr show -t 3075`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/3075.diff">https://git.openjdk.org/jdk17u-dev/pull/3075.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/3075#issuecomment-2499147924)
</details>

### CODE REVIEW

**Review by MBaesken — APPROVED** [review]
test/jdk/tools/jar/MultipleManifestTest.java seems to have some issue with the file ending ? but this is also present in 21u-dev so probably okay.

**Comment by GoeLin** [comment]
GHA test failure: well known wget issue, unrelated.

**Review by martinuy — APPROVED** [review]
Thanks for this contribution. Looks good to me.

**Comment by alexeybakhtin** [comment]
Thank you for review

**Pull request closed without merging**
