### PR TITLE
8266242: java/awt/GraphicsDevice/CheckDisplayModes.java failing on macOS 11 ARM

### PR DESCRIPTION
**Pull request by amosshi**
Backport of [JDK-8266242](https://bugs.openjdk.org/browse/JDK-8266242)
- `src/java.desktop/macosx/native/libawt_lwawt/awt/CGraphicsDevice.m` - clean backport
- `test/jdk/ProblemList.txt` - this file has been ignored because the line does not exist

Testing
- Local: Test passed
  - `CheckDisplayModes.java`: Test results: passed: 1

```
MacBook Pro
16-inch, 2021
Chip Apple M1 Max
Memory: 32 GB
MacOS: 14.3.1 (23D60)
```

- Pipeline: All checks have passed
- Testing Machine: SAP nightlies passed on `2024-03-01,02,03`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8266242](https://bugs.openjdk.org/browse/JDK-8266242) needs maintainer approval
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8266242](https://bugs.openjdk.org/browse/JDK-8266242): java/awt/GraphicsDevice/CheckDisplayModes.java failing on macOS 11 ARM (**Bug** - P4 - Approved)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2245/head:pull/2245` \
`$ git checkout pull/2245`

Update a local copy of the PR: \
`$ git checkout pull/2245` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2245/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2245`

View PR using the GUI difftool: \
`$ git pr show -t 2245`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2245.diff">https://git.openjdk.org/jdk17u-dev/pull/2245.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2245#issuecomment-1967624424)

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
LGTM.

**Comment by amosshi** [comment]
/approval request “Backporting for parity with jdk 17.0.12-oracle. Un-Clean backport, well changes on file CGraphicsDevice.m are clean. JDK code change, not only test case. SAP nightlies passed on 2024-03-01,02,03”

**Pull request closed without merging**
