### PR TITLE
8293000: Review running times of jshell regression tests

### PR DESCRIPTION
**Pull request by asotona**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8293000](https://bugs.openjdk.org/browse/JDK-8293000): Review running times of jshell regression tests

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/1119/head:pull/1119` \
`$ git checkout pull/1119`

Update a local copy of the PR: \
`$ git checkout pull/1119` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/1119/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1119`

View PR using the GUI difftool: \
`$ git pr show -t 1119`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1119.diff">https://git.openjdk.org/jdk17u-dev/pull/1119.diff</a>

</details>

### CODE REVIEW

**Comment by GoeLin** [comment]
@asotona, why are the Pre-submit tests failing?

**Comment by asotona** [comment]
@GoeLin
There is something wrong with the windows tests setup and it seems to be unrelated to this backport, see:
```
error: Target option 1.1 is no longer supported. Use 1.6 or later.
```

**Comment by RealCLanger** [comment]
> @GoeLin There is something wrong with the windows tests setup and it seems to be unrelated to this backport, see:
> 
> ```
> error: Target option 1.1 is no longer supported. Use 1.6 or later.
> ```

Yeah, that was the meanwhile solved jtreg issue. I can sponsor this PR.

/sponsor

**Pull request closed without merging**
