### PR TITLE
8337966: (fs) Files.readAttributes fails with Operation not permitted on older docker releases

### PR DESCRIPTION
**Pull request by alexeybakhtin**
Almost clean backport from JDK21

The only difference is an additional EPERM check in the stat1 method. This method was removed in JDK21 as part of JDK-8283335

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8337966](https://bugs.openjdk.org/browse/JDK-8337966) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8337966](https://bugs.openjdk.org/browse/JDK-8337966): (fs) Files.readAttributes fails with Operation not permitted on older docker releases (**Bug** - P4 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2883/head:pull/2883` \
`$ git checkout pull/2883`

Update a local copy of the PR: \
`$ git checkout pull/2883` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2883/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2883`

View PR using the GUI difftool: \
`$ git pr show -t 2883`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2883.diff">https://git.openjdk.org/jdk17u-dev/pull/2883.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2883#issuecomment-2353473159)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by akhilesh-delphix** [comment]
Hi @alexeybakhtin 
I hope this PR will also fix issue `java.nio.file.FileSystemException: app.jar: Function not implemented`  
Observed while running **`java -jar -Xdiag app.jar`**
JAVA
```
openjdk version "17.0.12" 2024-07-16
```

Here is complete stacktrace 


```
java.nio.file.FileSystemException: app.jar: Function not implemented
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
        at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1432)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:717)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:251)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:180)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:317)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:256)
        at java.base/sun.launcher.LauncherHelper.getMainClassFromJar(LauncherHelper.java:561)
        at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:787)
        at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:695)
```

**Comment by jerboaa** [comment]
> java.nio.file.FileSystemException: app.jar: Function not implemented

This looks like a different issue.

**Comment by alexeybakhtin** [comment]
> java.nio.file.FileSystemException: app.jar: Function not implemented

It looks like a similar issue, but the state syscall returns `ENOSYS` error code instead of `EPERM`. So, this PR does not fix your issue.
Could you please describe your environment? Maybe will need a followup to handle `ENOSYS` as well.

**Comment by akhilesh-delphix** [comment]
hi @alexeybakhtin 

I have a alpine:3.19.0 based docker image which is getting deployed as Pod in K8s deployment. It deploys well for all customers except this one where we are facing the above issue:

**Container runtime** 

`containerd://1.7.20-k3s1`

**kubectl version**

`Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.0", GitCommit:"1b4df30b3cdfeaba6024e81e559a6cd09a089d65", GitTreeState:"clean", BuildDate:"2023-04-11T17:10:18Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"windows/amd64"}

Kustomize Version: v5.0.1

Server Version: version.Info{Major:"1", Minor:"30", GitVersion:"v1.30.4+rke2r1", GitCommit:"a51b3b711150f57ffc1f526a640ec058514ed596", GitTreeState:"clean", BuildDate:"2024-08-15T06:00:17Z", GoVersion:"go1.22.5 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}

WARNING: version difference between client (1.27) and server (1.30) exceeds the supported minor version skew of +/-1`

Java Version

`openjdk version "17.0.12" 2024-07-16
`

Please let me know if you require more details.

**Comment by akhilesh-delphix** [comment]
hi @alexeybakhtin, 

Pls let me know if you need further details on this. 

Additionally , is it possible for you confirm that the issue faced by me (`java.nio.file.FileSystemException: app.jar: Function not implemented`) is a JDK issue (possibly regression of https://bugs.openjdk.org/browse/JDK-8316304). It will help us communicate with our stakeholders

**Comment by alexeybakhtin** [comment]
> hi @alexeybakhtin,
> 
> Pls let me know if you need further details on this.
> 
> Additionally , is it possible for you confirm that the issue faced by me (`java.nio.file.FileSystemException: app.jar: Function not implemented`) is a JDK issue (possibly regression of https://bugs.openjdk.org/browse/JDK-8316304). It will help us communicate with our stakeholders

Yes, As soon as I can see, it is a regression of JDK-8316304.
There is a possible workaround for docker containers: add statx to the seccomp filter and run the docker container with update seccomp filter `--security-opt seccomp=<path to seccomp.json>`

**Comment by jerboaa** [comment]
`Function not implemented` suggests `ENOSYS`, which can have other causes too.

**Comment by akhilesh-delphix** [comment]
hi @alexeybakhtin do we have any plans to address this issue ( `Function not implemented`) with JDK17?

**Pull request closed without merging**
