### PR TITLE
8313394: Array Elements in OldObjectSample event has the incorrect description

### PR DESCRIPTION
**Pull request by tkiriyama**
Hi all,

I want to backport JDK-8313394 for jdk11u.
This is clean backport.

Would you review and sponsor this fix, please?

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8313394](https://bugs.openjdk.org/browse/JDK-8313394) needs maintainer approval

### Issue
 * [JDK-8313394](https://bugs.openjdk.org/browse/JDK-8313394): Array Elements in OldObjectSample event has the incorrect description (**Bug** - P4 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1899/head:pull/1899` \
`$ git checkout pull/1899`

Update a local copy of the PR: \
`$ git checkout pull/1899` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1899/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1899`

View PR using the GUI difftool: \
`$ git pr show -t 1899`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1899.diff">https://git.openjdk.org/jdk17u-dev/pull/1899.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1899#issuecomment-1774934709)

### CODE REVIEW

**Review by phohensee — CHANGES_REQUESTED** [review]
The original commit didn't include a copyright date update, so please reverse that. Otherwise, lgtm.

**Comment by tkiriyama** [comment]
Thanks! I don't know the rules of the backport, so please tell me it. For backports, does the author not have to update the copyright date to the commit date?

**Comment by phohensee** [comment]
No. The copyright date is updated only if the original commit (the one being backported) has a copyright date update that's later than the existing one (the one in the backport target file). If the original commit has no copyright date update, the backport should not.

**Comment by tkiriyama** [comment]
Thank you for your comment. Please let me ask one more question. As you mentioned, in general, modifications should be as same as possible to the original. My concern here is the mismatch between the copyright year and the recent  modification year. 
I mean, if copyright year remains intact in this PR, one might think that patches introduced in the latest jdk after 2022 were not backported. However, this is not correct because the original patch was applied in 2023.

I haven' found a case where only the  backported patch changes the copyright year, so it seems appropriate not to change the copyright year in this case. However, given the above concerns, I'm not sure why this is desirable.
It would be helpful if you could tell me the meaning of the copyright year for the  backported patches  in detail if you know about it.

**Comment by phohensee** [comment]
My understanding is that the reason for updating the copyright year in a backport only if the copyright year was updated in the original commit is to maximize clean backports and make it easier to do subsequent backports (there's a lower probability of a copyright date conflict).

@RealCLanger, I can't found the policy on the updates wiki, could you add or point to it please?

**Comment by RealCLanger** [comment]
> My understanding is that the reason for updating the copyright year in a backport only if the copyright year was updated in the original commit is to maximize clean backports and make it easier to do subsequent backports (there's a lower probability of a copyright date conflict).
> 
> @RealCLanger, I can't find the policy on the updates wiki, could you add or point to it please?

the guidelines can be found here: https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix

Don't know if it mentions the policy wrt the copyright years. However, they need not be updated if the change itself didn't modify them. This keeps more backports clean.

For this one, it should be backported to JDK 21u first.

**Review by phohensee — APPROVED** [review]

**Comment by tkiriyama** [comment]
/approval request This is clean backport. It fixes only the description attribute of JFR event and the risk is low. Re-submit testing using is passed.

**Comment by tkiriyama** [comment]
@GoeLin 
This fix has been backported to 21.
I create the approval request again.

**Comment by tkiriyama** [comment]
/approval request This is clean backport. It fixes only the description attribute of JFR event and the risk is low. Re-submit testing using is passed.

**Pull request closed without merging**
