### PR TITLE
8273454: C2: Transform (-a)*(-b) into a*b

### PR DESCRIPTION
**Pull request by GoeLin**
I backport this for parity with 17.0.11-oracle.

This contains follow up fix 8274060: C2: Incorrect computation after JDK-8273454 and a part of JDK-8274130) C2: MulNode::Ideal chained transformations may act on wrong nodes which is already backported, but omitted the part to be applied to this patch.
This is also the reason why a clean backport failed.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8273454](https://bugs.openjdk.org/browse/JDK-8273454) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8274060](https://bugs.openjdk.org/browse/JDK-8274060) needs maintainer approval
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8273454](https://bugs.openjdk.org/browse/JDK-8273454): C2: Transform (-a)*(-b) into a*b (**Enhancement** - P4 - Approved)
 * [JDK-8274060](https://bugs.openjdk.org/browse/JDK-8274060): C2: Incorrect computation after JDK-8273454 (**Bug** - P1 - Approved)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2035/head:pull/2035` \
`$ git checkout pull/2035`

Update a local copy of the PR: \
`$ git checkout pull/2035` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2035/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2035`

View PR using the GUI difftool: \
`$ git pr show -t 2035`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2035.diff">https://git.openjdk.org/jdk17u-dev/pull/2035.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2035#issuecomment-1850187706)

### CODE REVIEW

**Review by shipilev — CHANGES_REQUESTED** [review]
I never thought we would backport this. But now that we do, this hunk is missing:
https://github.com/openjdk/jdk/commit/756d22c3563ac92e74bb68d5eecb86d4fbab2c6b#diff-b1bd52f0743843e15452764f48ff43c15dd3192a28bfb684b34149f0e964996eR83-R84

When we backported [JDK-8274130](https://bugs.openjdk.org/browse/JDK-8274130), we skipped that hunk.

**Comment by GoeLin** [comment]
Thanks for catching this! I thought I had added that part :/

**Review by shipilev — APPROVED** [review]
Yeah, this looks right.

**Pull request closed without merging**
