### PR TITLE
8298381: Improve handling of session tickets for multiple SSLContexts

### PR DESCRIPTION
**Pull request by schlosna**
I would like to propose a backport of [JDK-8298381](https://bugs.openjdk.org/browse/JDK-8298381) commit https://github.com/openjdk/jdk/commit/debe5879aa7118a114ff6fcf8d15951757ae70a8 that landed in JDK 21 to jdk17u. This change significantly improves TLS handshaking latency and throughput for services that utilize multiple `SSLContext`. As an example, Apache Kafka running on JDK 17 with significant numbers of clients may see over 40% of CPU utilization due to `SessionTicketExtension$KeyState.cleanup(HandshakeContext)`.

@simonis or others, would you be willing to sponsor this change to JDK 17u and create a corresponding JIRA ticket?

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8298381](https://bugs.openjdk.org/browse/JDK-8298381) needs maintainer approval

### Issue
 * [JDK-8298381](https://bugs.openjdk.org/browse/JDK-8298381): Improve handling of session tickets for multiple SSLContexts (**Bug** - P3 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2750/head:pull/2750` \
`$ git checkout pull/2750`

Update a local copy of the PR: \
`$ git checkout pull/2750` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2750/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2750`

View PR using the GUI difftool: \
`$ git pr show -t 2750`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2750.diff">https://git.openjdk.org/jdk17u-dev/pull/2750.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2750#issuecomment-2256577087)

### CODE REVIEW

**Comment by schlosna** [comment]
As an example, Apache Kafka running on JDK 17 with significant numbers of clients may see over 40% of CPU utilization due to `SessionTicketExtension$KeyState.cleanup(HandshakeContext)` as seen in JFR snippets from an example environment. Upgrading to JDK 21 does resolve this as expected; however, there are some systems that may not be able to immediately upgrade to JDK 21 or later that would benefit from this change.

image
image

```
The most sampled method was void sun.security.ssl.SessionTicketExtension$KeyState.cleanup(HandshakeContext), with 4.33 % of the maximum possible samples for 7/27/2024, 3:19:48.000 PM – 3:20:18 PM, and 46.9 % of the actual samples.
The methods that used the most CPU are:
sun.security.ssl.SessionTicketExtension$KeyState.cleanup(HandshakeContext) (46.9 % of samples) 7/27/2024, 3:19:48.000 PM – 3:20:18 PM

The most common stack trace was:
  at void sun.security.ssl.SessionTicketExtension$KeyState.cleanup(sun.security.ssl.HandshakeContext)
  at sun.security.ssl.SessionTicketExtension$StatelessKey sun.security.ssl.SessionTicketExtension$KeyState.nextKey(sun.security.ssl.HandshakeContext)
  at sun.security.ssl.SessionTicketExtension$StatelessKey sun.security.ssl.SessionTicketExtension$KeyState.getCurrentKey(sun.security.ssl.HandshakeContext)
  at byte[] sun.security.ssl.SessionTicketExtension$SessionTicketSpec.encrypt(sun.security.ssl.HandshakeContext, sun.security.ssl.SSLSessionImpl)
  at byte[] sun.security.ssl.NewSessionTicket$T12NewSessionTicketProducer.produce(sun.security.ssl.ConnectionContext, sun.security.ssl.SSLHandshake$HandshakeMessage)
  at byte[] sun.security.ssl.Finished$T12FinishedProducer.onProduceFinished(sun.security.ssl.ServerHandshakeContext, sun.security.ssl.SSLHandshake$HandshakeMessage)
  at byte[] sun.security.ssl.Finished$T12FinishedProducer.produce(sun.security.ssl.ConnectionContext, sun.security.ssl.SSLHandshake$HandshakeMessage)
  at byte[] sun.security.ssl.SSLHandshake.produce(sun.security.ssl.ConnectionContext, sun.security.ssl.SSLHandshake$HandshakeMessage)
  at void sun.security.ssl.Finished$T12FinishedConsumer.onConsumeFinished(sun.security.ssl.ServerHandshakeContext, java.nio.ByteBuffer)
  at void sun.security.ssl.Finished$T12FinishedConsumer.consume(sun.security.ssl.ConnectionContext, java.nio.ByteBuffer)
  at void sun.security.ssl.SSLHandshake.consume(sun.security.ssl.ConnectionContext, java.nio.ByteBuffer)
  at void sun.security.ssl.HandshakeContext.dispatch(byte, java.nio.ByteBuffer)
  at void sun.security.ssl.HandshakeContext.dispatch(byte, sun.security.ssl.Plaintext)
  at void sun.security.ssl.TransportContext.dispatch(sun.security.ssl.Plaintext)
  at sun.security.ssl.Plaintext sun.security.ssl.SSLTransport.decode(sun.security.ssl.TransportContext, java.nio.ByteBuffer[], int, int, java.nio.ByteBuffer[], int, int)
  at sun.security.ssl.Plaintext sun.security.ssl.SSLEngineImpl.decode(java.nio.ByteBuffer[], int, int, java.nio.ByteBuffer[], int, int)
  at javax.net.ssl.SSLEngineResult sun.security.ssl.SSLEngineImpl.readRecord(java.nio.ByteBuffer[], int, int, java.nio.ByteBuffer[], int, int)
  at javax.net.ssl.SSLEngineResult sun.security.ssl.SSLEngineImpl.unwrap(java.nio.ByteBuffer[], int, int, java.nio.ByteBuffer[], int, int)
  at javax.net.ssl.SSLEngineResult sun.security.ssl.SSLEngineImpl.unwrap(java.nio.ByteBuffer, java.nio.ByteBuffer[], int, int)
  at javax.net.ssl.SSLEngineResult javax.net.ssl.SSLEngine.unwrap(java.nio.ByteBuffer, java.nio.ByteBuffer)
  at javax.net.ssl.SSLEngineResult org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(boolean, boolean)
  at void org.apache.kafka.common.network.SslTransportLayer.doHandshake()
  at void org.apache.kafka.common.network.SslTransportLayer.handshake()
  at void org.apache.kafka.common.network.KafkaChannel.prepare()
  at void org.apache.kafka.common.network.Selector.pollSelectionKeys(java.util.Set, boolean, long)
  at void org.apache.kafka.common.network.Selector.poll(long)
  at void kafka.network.Processor.poll()
  at void kafka.network.Processor.run()
  at void java.lang.Thread.run()
```

**Review by phohensee — APPROVED** [review]
Lgtm. I can sponsor, Volker is on vacation. No need to create a backport JBS issue, the bot will do that when it pushes the backport.

**Comment by schlosna** [comment]
/approval request Proposing backport [JDK-8298381](https://bugs.openjdk.org/browse/JDK-8298381) commit https://github.com/openjdk/jdk/commit/debe5879aa7118a114ff6fcf8d15951757ae70a8 that landed in JDK 21 to jdk17u. This change significantly improves TLS handshaking latency and throughput for services that utilize multiple `SSLContext`. As an example, Apache Kafka running on JDK 17 with significant numbers of clients may see over 40% of CPU utilization due to `SessionTicketExtension$KeyState.cleanup(HandshakeContext)`.

**Comment by schlosna** [comment]
Excellent, thanks @phohensee and have a great vacation Volker. 

Please let me know if there's anything else I can do to help move this along.

**Comment by phohensee** [comment]
Please replace the PR title with "Backport debe5879aa7118a114ff6fcf8d15951757ae70a8" and let the bot do its thing.

**Pull request closed without merging**
