### PR TITLE
8274471: Add support for RSASSA-PSS in OCSP Response

### PR DESCRIPTION
**Pull request by apavlyutkin**
This one is submitted in place of https://github.com/openjdk/jdk17u/pull/248 that was too late to jdk17u

I'd like to backport JDK-8274471 to jdk17u-dev

The patch fixes internal error upon verification of OCSP Response signed with RSASSA-PSS

The original patch applied with minor changes to src/java.base/share/classes/sun/security/provider/certpath/OCSP.java

- resolved baseline conflict: the original patch was done on top of JDK-8272120: Avoid looking for standard encodings in "java." modules and cannot be applied cleanly although it deletes the changes done against JDK-8272120 (see lines 249-241)
- imported few required packages

Verified (20.04 LTS/amd64) with attached [Test8274471.java.zip](https://github.com/openjdk/jdk17u/files/7514663/Test8274471.java.zip). Regression: jdk_security

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8274471](https://bugs.openjdk.java.net/browse/JDK-8274471): Add support for RSASSA-PSS in OCSP Response

### Reviewers
 * [Martin Doerr](https://openjdk.java.net/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [Goetz Lindenmaier](https://openjdk.java.net/census#goetz) (@GoeLin - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17u-dev pull/36/head:pull/36` \
`$ git checkout pull/36`

Update a local copy of the PR: \
`$ git checkout pull/36` \
`$ git pull https://git.openjdk.java.net/jdk17u-dev pull/36/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 36`

View PR using the GUI difftool: \
`$ git pr show -t 36`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17u-dev/pull/36.diff">https://git.openjdk.java.net/jdk17u-dev/pull/36.diff</a>

</details>

### CODE REVIEW

**Comment by apavlyutkin** [comment]
Guys, could somebody review that?

**Comment by apavlyutkin** [comment]
@TheRealMDoerr, could you checked this one. This is just a copy of https://github.com/openjdk/jdk17u/pull/248 that was reviewed by you but missed 17.0.2

**Review by TheRealMDoerr — APPROVED** [review]
Still good. Thanks for the new PR.

**Comment by alexeybakhtin** [comment]
Minor comments of the OCSP changes:
The original patch removes unused imports. These unused imports were caused by JDK-8232066: “Remove outdated code/methods from PKIX implementation”
JDK-8232066 does not affect the functionality of this enhancement and can be skipped

So, looks good to me (not a reviewer)

**Comment by gnu-andrew** [comment]
Part of JDK-8272120 is still being dragged in with the use of `UTF_8` in `OSCP.java`.  We can retain that as `"UTF-8"` and avoid adding the import that is not present in the original patch.

**Comment by apavlyutkin** [comment]
> Part of JDK-8272120 is still being dragged in with the use of `UTF_8` in `OSCP.java`. We can retain that as `"UTF-8"` and avoid adding the import that is not present in the original patch.

Ok, removed. BTW how about jdk11u-dev? As I understand being just an enhancement JDK-8272120 does not have a chance to be bockported to jdk11, but using "UTF-8" is still an overhead.

**Review by TheRealMDoerr — APPROVED** [review]
Thanks for the update! Good. I think it makes sense to accept it in 11u, too, after it is carefully reviewed and tested.

**Comment by apavlyutkin** [comment]
> Thanks for the update! Good. I think it makes sense to accept it in 11u, too, after it is carefully reviewed and tested.

Thank you. I've already completed backports to 11 (very dirty) & 8 (just a bit unclean). They are postponed

@GoeLin how can I get "ready" label back? Thank you

**Review by GoeLin — APPROVED** [review]
Formal requirements are all met now.
LGTM

**Comment by GoeLin** [comment]
Please enable github actions, also in the other repos where you might backport to.

**Pull request closed without merging**
