### PR TITLE
8296275: Write a test to verify setAccelerator  method of JMenuItem

### PR DESCRIPTION
**Pull request by SoniaZaldana**
Hi all,

This pull request contains a backport of commit [b005013a](https://github.com/openjdk/jdk/commit/b005013a0015656b7f6ccc26f8a13c44d61f77b9) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Naveen Narayanan on 21 Dec 2022 and was reviewed by Manukumar V S and Alexey Ivanov.

Thanks!

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8296275](https://bugs.openjdk.org/browse/JDK-8296275) needs maintainer approval

### Issue
 * [JDK-8296275](https://bugs.openjdk.org/browse/JDK-8296275): Write a test to verify setAccelerator  method of JMenuItem (**Enhancement** - P4 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1825/head:pull/1825` \
`$ git checkout pull/1825`

Update a local copy of the PR: \
`$ git checkout pull/1825` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1825/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1825`

View PR using the GUI difftool: \
`$ git pr show -t 1825`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1825.diff">https://git.openjdk.org/jdk17u-dev/pull/1825.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1825#issuecomment-1745854483)

### CODE REVIEW

**Comment by SoniaZaldana** [comment]
/approval request "Backporting this for parity with 17.0.7-oracle. Low risk as it only adds an additional test case. Patch applies cleanly to 17u."

**Comment by GoeLin** [comment]
Hi @SoniaZaldana, 
this was here twice, please close it.

**Pull request closed without merging**
