### PR TITLE
8300926: Several startup regressions  ~6-70% in 21-b6 all platforms

### PR DESCRIPTION
**Pull request by apavlyutkin**
Hi, here is backport of [JDK-8300926](https://bugs.openjdk.org/browse/JDK-8300926). The patch splits deoptimization routine into two separate phases: the first implies only marking methods to be deoptimized, and the second is proper deoptimization. Only the first one is run under taken Compile_lock. Without the patch the lock stays taken during whole deoptimization routine and that prevents compilations from other threads.

Original patch is applied with the following changes:

- changes to `void LambdaFormInvokers::regenerate_class(char* class_name, ClassFileStream& st, TRAPS)` applied to `void LambdaFormInvokers::reload_class(char* name, ClassFileStream& st, TRAPS)`
- `SystemDictionary::add_to_hierarchy(JavaThread* current, InstanceKlass* k)`
changed to `SystemDictionary::add_to_hierarchy(Thread* current, InstanceKlass* k)`,
cuz in 17 it's also called from
`SystemDictionaryShared::add_unregistered_class(Thread* current, InstanceKlass* k)`
- `SystemDictionary::add_to_hierarchy(JavaThread* current, InstanceKlass* k)` does not lock/unlock k->init_monitor()
- changes to `void CodeCache::make_marked_nmethods_deoptimized()` skipped
- removal of absent `void CodeCache::make_nmethod_deoptimized(CompiledMethod* nm)` ignored
- substitution of `CompiledMethod::MarkForDeoptimizationStatus` with `DeoptimizationStatus` and related changes are skipped because in 17 `_mark_for_deoptimization_status` always accessed under CompiledMethod_lock;
- changes to `void DependencyContext::mark_dependent_nmethods(DeoptimizationScope* deopt_scope, DepChange& changes)` applied with respect to the difference in baselines
- `void DependencyContext::remove_and_mark_for_deoptimization_all_dependents(DeoptimizationScope* deopt_scope)` completely ported with respect to baseline
- changes to nmethod related to Virtual Threads were skipped
- changes to `void InstanceKlass::initialize_impl(TRAPS)` applied to `bool InstanceKlass::link_class_impl(TRAPS)`

Regression: hotspot_all (amd64/20.04LTS) - no new failures +  `runtime/cds/appcds/dynamicArchive/LambdaProxyDuringShutdown.java` previously failing now passes

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8300926](https://bugs.openjdk.org/browse/JDK-8300926): Several startup regressions  ~6-70% in 21-b6 all platforms (**Bug** - P2)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1243/head:pull/1243` \
`$ git checkout pull/1243`

Update a local copy of the PR: \
`$ git checkout pull/1243` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1243/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1243`

View PR using the GUI difftool: \
`$ git pr show -t 1243`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1243.diff">https://git.openjdk.org/jdk17u-dev/pull/1243.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1243#issuecomment-1510146653)

### CODE REVIEW

**Comment by apavlyutkin** [comment]
@robehn @dholmes-ora could you look at this. Thank you

**Comment by apavlyutkin** [comment]
ping

**Review by phohensee — COMMENTED** [review]
I'm not an expert in this area, but have a few comments.

Why not lock/unlock k->init_monitor in systemdictionary.cpp? UseVtableBasedCHA exists in 17u.

In codeCache.cpp, the ResourceMark at line 1185 is kept in the PR, but removed in the original commit.

Perhaps run tests with -XX:+DeoptimizeALot?

Looks like [JDK-8299074](https://bugs.openjdk.org/browse/JDK-8299074) is included.

**Comment by apavlyutkin** [comment]
Please don't close this, bot.

**Comment by apavlyutkin** [comment]
@apavlyutkin adding new mail address

**Pull request closed without merging**
