### PR TITLE
8314495: Update to use jtreg 7.3.1

### PR DESCRIPTION
**Pull request by shipilev**
Atomically brings jtreg 7.3.1 (current at mainline) to 17u. Depending on new jtreg allows to cleanly backport tests from mainline without rewriting them for older jtreg.

Thankfully, @GoeLin backported all the actual test changes that are needed for this to work.

The uncleanliness comes mostly from the gtest "version" variable conflicts. Otherwise the whole stack applies cleanly.

Additional testing:
 - [x] GHA
 - [x] Linux AArch64 `tier1 tier2 tier3 tier4`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8314495](https://bugs.openjdk.org/browse/JDK-8314495): Update to use jtreg 7.3.1 (**Enhancement** - P3)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1712/head:pull/1712` \
`$ git checkout pull/1712`

Update a local copy of the PR: \
`$ git checkout pull/1712` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1712/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1712`

View PR using the GUI difftool: \
`$ git pr show -t 1712`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1712.diff">https://git.openjdk.org/jdk17u-dev/pull/1712.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1712#issuecomment-1701081766)

### CODE REVIEW

**Comment by shipilev** [comment]
I don't really see the point of adding all the relevant "jtreg update" issues to this PR, but I can if anyone has a strong opinion about it. @GoeLin, @RealCLanger?

**Review by TheRealMDoerr — APPROVED** [review]
This makes sense!

**Comment by RealCLanger** [comment]
> I don't really see the point of adding all the relevant "jtreg update" issues to this PR, but I can if anyone has a strong opinion about it. @GoeLin, @RealCLanger?

No strong opinion, it's fine.

**Review by RealCLanger — APPROVED** [review]

**Comment by shipilev** [comment]
Before I integrate, can I ask @TheRealMDoerr @RealCLanger or @GoeLin to run this through their nightly testing too? Don't want to break stuff if we can avoid it.

**Comment by TheRealMDoerr** [comment]
We already use the new jtreg version for our nightly tests. I've put your PR into our queue.

**Comment by shipilev** [comment]
> We already use the new jtreg version for our nightly tests. I've put your PR into our queue.

Ah, that would be enough then. I wanted to check if any test does not work with new jtreg, e.g. due to missing testbug backport. If your nightly already passes with 7.3.1, then we are already good.

**Comment by TheRealMDoerr** [comment]
Test results look good. Your PR is appreciated! But, testing it does not harm. I'll keep it in the queue.

**Comment by RealCLanger** [comment]
> > We already use the new jtreg version for our nightly tests. I've put your PR into our queue.
> 
> Ah, that would be enough then. I wanted to check if any test does not work with new jtreg, e.g. due to missing testbug backport. If your nightly already passes with 7.3.1, then we are already good.

Yes, we had already switched our testing of JDK 17 and later to 7.3.1 when we saw your PR (Thanks @ArnoZeller). Looks all fine, this PR is good to go from our end.

**Comment by shipilev** [comment]
All right then! Here goes.

/integrate

**Pull request closed without merging**
