### PR TITLE
8337684: [17/11u] Revert JDK-8163921 backport

### PR DESCRIPTION
**Pull request by shipilev**
See the issue for more discussion and rationale. This is the actual code change, should we decide to go forward.

This is a `git revert` of https://github.com/openjdk/jdk17u-dev/commit/b37df147b011b23b6c7474d726710e1478af7607.

Additional testing:
 - [x] Linux AArch64 server fastdebug, `jdk_net`
 - [x] Linux AArch64 server fastdebug, `all`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] [JDK-8337684](https://bugs.openjdk.org/browse/JDK-8337684) needs maintainer approval

### Issue
 * [JDK-8337684](https://bugs.openjdk.org/browse/JDK-8337684): [17/11u] Revert JDK-8163921 backport (**Bug** - P4 - Requested)

### Reviewers
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2775/head:pull/2775` \
`$ git checkout pull/2775`

Update a local copy of the PR: \
`$ git checkout pull/2775` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2775/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2775`

View PR using the GUI difftool: \
`$ git pr show -t 2775`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2775.diff">https://git.openjdk.org/jdk17u-dev/pull/2775.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2775#issuecomment-2264924812)

### CODE REVIEW

**Review by mrserb — APPROVED** [review]

**Comment by jerboaa** [comment]
I'm OK with this change. Do you plan on doing a more targeted fix for https://bugs.openjdk.org/browse/JDK-8163921 (e.g. by fixing the syntax error in the default accept header only)?

**Comment by shipilev** [comment]
> I'm OK with this change. Do you plan on doing a more targeted fix for https://bugs.openjdk.org/browse/JDK-8163921 (e.g. by fixing the syntax error in the default accept header only)?

Not at this time. The far-reaching unintended consequences of the original fix tells me this is a fiddly piece of code, so we are a bit averse trying to do more things than necessary here. I think we just let JDK 11 and 17 be as they are, even though it leaves HTTP client de-jure non-compliant to RFC. Let applications first encounter any default policy change in JDK 21.

**Comment by jerboaa** [comment]
@GoeLin What's your take on this? If we revert, we should probably get it in soon.

**Comment by shipilev** [comment]
> @GoeLin What's your take on this? If we revert, we should probably get it in soon.

Also interested in this answer :) We missed the normal cutoff for October releases, but I can resubmit this PR as 17u-critical.

**Comment by GoeLin** [comment]
Has anybody else seen this, besides Amazon in its internal systems?  
I'm not so sure this is of relevance for everybody.

**Comment by GoeLin** [comment]
Hi @shipilev 
What do you think about this? https://github.com/openjdk/jdk17u-dev/pull/2843

**Comment by shipilev** [comment]
Closing in favor of https://github.com/openjdk/jdk17u-dev/pull/2843

**Pull request closed without merging**
