### PR TITLE
8307128: Open source some drag and drop tests 4

### PR DESCRIPTION
**Pull request by Rudometov**
Backport https://github.com/openjdk/jdk/commit/98294242a94c611e2a713c2d520e59dd873ae4a0
https://bugs.openjdk.org/browse/JDK-8307128 Open source some drag and drop tests 4

Not clean as required quick fix for @requires
Without this fix mac reported error Error. Parse Exception: Invalid tag: requires(os

Clean backport (https://github.com/openjdk/jdk17u-dev/commit/f2ee1fd0afe4b5f7982a4997e9765c5505461028) + fix for requires in MozillaDnDTest (https://github.com/openjdk/jdk17u-dev/commit/6b0e89a68b858fb9d3d842d3d5aefa66ad4638cb), new tests, low risk
Checked on macOS x64, linux x64

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8307128](https://bugs.openjdk.org/browse/JDK-8307128): Open source some drag and drop tests 4
 * [JDK-8307799](https://bugs.openjdk.org/browse/JDK-8307799): Newly added java/awt/dnd/MozillaDnDTest.java has invalid jtreg `@requires` clause

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1360/head:pull/1360` \
`$ git checkout pull/1360`

Update a local copy of the PR: \
`$ git checkout pull/1360` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1360/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1360`

View PR using the GUI difftool: \
`$ git pr show -t 1360`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1360.diff">https://git.openjdk.org/jdk17u-dev/pull/1360.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1360#issuecomment-1552222081)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by GoeLin** [comment]
Hi @Rudometov, I think the fix for the requires comes in related issue JDK-8307799.
Please add that with the / issue command to this PR, and mention that you include that
in the JBS issue.
You should always check all relates-to issues of a change you backport before you label it with fix-request! Often they are needed, too.

**Comment by Rudometov** [comment]
Thank you. I overlooked that one, will pay more attention in the future.

**Comment by GoeLin** [comment]
Thanks for backporting all the tests. It's good to have them in 17, too!

**Pull request closed without merging**
