### PR TITLE
8310072: JComboBox/DisabledComboBoxFontTestAuto: Enabled and disabled ComboBox does not match in these LAFs: GTK+

### PR DESCRIPTION
**Pull request by tkiriyama**
Hi all,
This pull request is the backport of JDK-8310072.
It is clean and change only DisabledComboBoxFontTestAuto.java. This change resolves a test failure added by the JDK-7093691.
JDK-7093691will be backported in #3008.

Testing:
javax/swing/JComboBox on Windows and Linux

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8310072](https://bugs.openjdk.org/browse/JDK-8310072) needs maintainer approval

### Issue
 * [JDK-8310072](https://bugs.openjdk.org/browse/JDK-8310072): JComboBox/DisabledComboBoxFontTestAuto: Enabled and disabled ComboBox does not match in these LAFs: GTK+ (**Bug** - P4 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/3009/head:pull/3009` \
`$ git checkout pull/3009`

Update a local copy of the PR: \
`$ git checkout pull/3009` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/3009/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3009`

View PR using the GUI difftool: \
`$ git pr show -t 3009`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/3009.diff">https://git.openjdk.org/jdk17u-dev/pull/3009.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/3009#issuecomment-2441329438)

### CODE REVIEW

**Comment by GoeLin** [comment]
@tkiriyama, please merge head in the hope this gets clean.

**Comment by tkiriyama** [comment]
@GoeLin Thanks to your help, it went well.

**Comment by GoeLin** [comment]
@tkiriyama good, now you can request approval.

**Pull request closed without merging**
