### PR TITLE
8313815: The exception messages printed by jcmd ManagementAgent.start are corrupted on Japanese Windows

### PR DESCRIPTION
**Pull request by yukikimmura**
I would like to fix this issue 
because users can not read the exception message of jcmd ManagementAgent on localized Windows platform and can not understand what happened.
Testing:
  all serviceability area tests jdk_svc, and a specific test to verify the fix.

Could anyone review the fix please?

Thanks,
Kimura Yukihiro

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8313815](https://bugs.openjdk.org/browse/JDK-8313815): The exception messages printed by jcmd ManagementAgent.start are corrupted on Japanese Windows (**Bug** - P4)

### Reviewers
 * [Kevin Walls](https://openjdk.org/census#kevinw) (@kevinjwalls - Committer)
 * [Chris Plummer](https://openjdk.org/census#cjplummer) (@plummercj - Committer)
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1641/head:pull/1641` \
`$ git checkout pull/1641`

Update a local copy of the PR: \
`$ git checkout pull/1641` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1641/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1641`

View PR using the GUI difftool: \
`$ git pr show -t 1641`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1641.diff">https://git.openjdk.org/jdk17u-dev/pull/1641.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1641#issuecomment-1667033671)

### CODE REVIEW

**Comment by plummercj** [comment]
We have the following in agent.properties:

    agent.err.invalid.state            = Invalid agent state: {0}

and it is used by:

     public static final String INVALID_STATE =
        "agent.err.invalid.state";
    throw new RuntimeException(getText(INVALID_STATE, "Agent already started"));

Shouldn't "Agent already started" also be text that we should localize in the properties files? If we did, I think this issue would go away. Since the above is the only reference to INVALID_STATE, we could just instead have:

    agent.err.invalid.state            = Invalid agent state: Agent already started

**Comment by yukikimmura** [comment]
Hello Chris,
Thank you for your review.
I'll consider it.

Thanks,
Kimura Yukihiro

**Comment by plummercj** [comment]
If you are going to go with the localization of "Agent already started" approach, it should probably be done in 22 and then backported. If you want to just go with your current fix, that's ok to.

**Comment by yukikimmura** [comment]
Hello Chris,
Thank you for your comments.

I think your suggestion is to set a localized exception message or the English message to the RuntimeException.
I'm sorry if I misunderstood.

I prefer to modify jcmd (HotSpotVirtualMachine.java) for two reasons.
First, ManagementAgent.start can specify jmxremote.host, so the encoding may be different from the host running jcmd.
Second, I think setting a localized message to a RuntimeException is not desirable.
It would be nice to change the message to English on the localized environment, but from JDK18, the localized message is output correctly. 

I believe it's not necessary to fix JDK22 as this issue doesn't occur owing to JEP 400.

Thanks,
Kimura Yukihiro

**Comment by yukikimmura** [comment]
Hello Chris,
Thank you for your review.

I would like to go with the current fix, as I replied to your comment.
I received a comment from you that this fix is OK, but please let me know if you have any concerns.
It would be great if you could approve it.
It is my understanding that a pull request must be approved by at least two reviewer in order to be accepted.

Thanks,
Kimura Yukihiro

**Review by plummercj — APPROVED** [review]

**Comment by yukikimmura** [comment]
Hello everyone,
Thank you for your help with this issue.
I tested all serviceability area tests.
And I tested a specific test to verify the fix, which I run the test on:
  English Windows
  Japanese Windows
  RHEL LANG/LC_ALL=
  RHEL LANG/LC_ALL=C
  RHEL LANG/LC_ALL=en_US.UTF-8
  RHEL LNAG/LC_ALL=ja_JP.UTF-8

Is there anything left for me to do to get the fix integrated?
I would like to fix this problem because it is very inconvenient for customers to not be able to read error messages in the Japanese Windows environment.

**Comment by kevinjwalls** [comment]
Yes that sounds good.  I think you can /integrate and we can /sponsor if that is needed.

**Comment by yukikimmura** [comment]
/integrate

Thank you for your quick reply.
Could you please sponsor the fix?

**Comment by yukikimmura** [comment]
I'm very sorry, I typed integrate before being marked as ready for integration.
The jdk17-fix-yes has not be set on JBS yet.

**Comment by kevinjwalls** [comment]
Yes of course.  On the jbs entry, I think that should have been a jdk17u-fix-request label, so I updated it.

**Review by phohensee — APPROVED** [review]

**Pull request closed without merging**
