### PR TITLE
8298472: AArch64: Detect Ampere-1 and Ampere-1A CPUs and set default options

### PR DESCRIPTION
**Pull request by cnqpzhang**
Backport of CPU detection function for Ampere-1 and Ampere-1A, and performance enhancement with turning on UseSIMDForMemoryOps option for these two CPUs by default. Verified OpenJDK bundled JMH test cases, `make run-test TEST="micro:java.lang.ArrayCopy*"` , SIMD vs NoSIMD ratios are mostly positive as expected, aligned with that on jdk mainline. Low risk to other functions/systems due to the CPU detection logic.

Not a clean backport, manually resolved below conflicts, **no function change**:
1. Copyright years are `1997, 2021` in 17u-dev instead of the expected `1997, 2022` in two files
2. `@@ -132,7 +132,7 @@ void VM_Version::initialize()` should be 131 for 17u-dev
3. `@@ -144,6 +144,13 @@ void VM_Version::initialize() ` should be 143 for 17u-dev
4. The `enum Feature_Flag` in 17u-dev has been updated in jdk mainline to: declaring the macro `#define CPU_FEATURE_FLAGS` firstly then wrapping it inside the enum. So the line numbers are not aligned during doing `git apply`

FYI, a try-out: manually fixing these conflicts according to `git apply -v` in the patch file can make it applied cleanly. 

Additional tests done:
1. Linux aarch64 release tier1 on Ampere-1 system, without explicitly specifying UseSIMDForMemoryOps 
6. OpenJDK GHA Sanity Checks on forked repo: https://github.com/cnqpzhang/jdk17u-dev/actions/runs/3919027362

Backport-of: 706845743699efb01994e2d12c65023a3e972b77
Signed-off-by: Patrick Zhang <patrick@os.amperecomputing.com>

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8298472](https://bugs.openjdk.org/browse/JDK-8298472): AArch64: Detect Ampere-1 and Ampere-1A CPUs and set default options

### Reviewers
 * [Andrew Haley](https://openjdk.org/census#aph) (@theRealAph - **Reviewer**)
 * [Goetz Lindenmaier](https://openjdk.org/census#goetz) - **Reviewer** ⚠️ Added manually

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev pull/1067/head:pull/1067` \
`$ git checkout pull/1067`

Update a local copy of the PR: \
`$ git checkout pull/1067` \
`$ git pull https://git.openjdk.org/jdk17u-dev pull/1067/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1067`

View PR using the GUI difftool: \
`$ git pr show -t 1067`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1067.diff">https://git.openjdk.org/jdk17u-dev/pull/1067.diff</a>

</details>

### CODE REVIEW

**Comment by GoeLin** [comment]
Hi @cnqpzhang 
This is obviously not a clean backport. I get 3!!!! conflicts when I patch the change to 17.
Please correct your description above and describe what you resolved. Then get a review.
After all this, you can tag the change again.
Thansk.

**Comment by cnqpzhang** [comment]
> Hi @cnqpzhang This is obviously not a clean backport. I get 3!!!! conflicts when I patch the change to 17. Please correct your description above and describe what you resolved. Then get a review. After all this, you can tag the change again. Thansk.

Thanks for your comments  @GoeLin , I just now updated the description, and listed all the conflicts I resolved. I thought "Clean" meant "no function dependency on other commits", and now got what it really indicated, after reading the wiki page https://wiki.openjdk.org/display/SKARA/Backports. 

Thanks. Please help review this.

**Comment by cnqpzhang** [comment]
Hi, @GoeLin, I found the "jdk17u-fix-request" label at https://bugs.openjdk.org/browse/JDK-8298472 got removed once again without comments, while I think I had already updated the description accordingly, about merging conflicts resolved there. May I know what other information is needed to support this backport request? Thanks.

**Comment by cnqpzhang** [comment]
Resolved a simple merge conflict vs current tip of 17u-dev master, Copyright notices related.

**Comment by GoeLin** [comment]
Hi, please see
https://mail.openjdk.org/pipermail/jdk-updates-dev/2023-January/020064.html
https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix

**Comment by cnqpzhang** [comment]
> Hi, please see https://mail.openjdk.org/pipermail/jdk-updates-dev/2023-January/020064.html https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix

Thanks. I updated the "Fix Request (17u)" comment accordingly in [JDK-8298472](https://bugs.openjdk.org/browse/JDK-8298472).

**Comment by cnqpzhang** [comment]
Rebased this once again in order to resolve the windows-x64 pre-submit testing failures caused by a JTReg script issue and fixed by a recent [patch ](https://github.com/openjdk/jtreg/commit/dffb1eeafe74a09a07db758f289e07ffa92d8b53)at [jtreg-6.1+3](https://github.com/openjdk/jtreg/commits/jtreg-6.1+3).

Right now all tests passed.  

@GoeLin Could you please help review this patch? If it requires a particular review from aach64-port, please let me know and I could ask for someone's favor there. Thanks

Let me re-summarize the information of this PR (this is aligned the description in JBS):
1. This backport is to simply enable UseSIMDForMemoryOps aarch64 option for Ampere-1 and Ampere-1A CPUs
2. The risk is low, since the option is very mature and has been there for long. The CPU detection limits the change on specific CPUs only.
3. Patch does NOT apply cleanly due to Copyright years and some line numbers mismatching, pretty trivial updates can resolve the conflict.
4. No obvious JBS dependency so far, as functions related have been in 17u-dev for some time.
5. Ran JDK bundled JMH micro benchmarks, tier1 and commercial benchmarks, results are good.

**Comment by cnqpzhang** [comment]
Hi @therealaph, Sorry for messaging you directly. This backport PR probably requires a review from both jdk-updates and aarch64-port perspective. Could you please help? Thanks.

**Review by theRealAph — APPROVED** [review]

**Comment by cnqpzhang** [comment]
A gentle ping...

This PR has been approved for ~5 days, could anyone please help sponsor and push it into jdk17u-dev? Many thanks.

**Comment by cnqpzhang** [comment]
Ping once again..

Any jdk-updates committer please help sponsor and push this PR, thanks.

**Comment by GoeLin** [comment]
I sponsored this after running it succesfully through our nightly tests.
I did not review it, though.

**Pull request closed without merging**
