### PR TITLE
8324646: Avoid Class.forName in SecureRandom constructor

### PR DESCRIPTION
**Pull request by olivergillespie**
Improve performance of SecureRandom constructor by backporting (both clean) two changes:

1. [JDK-8280970](https://bugs.openjdk.org/browse/JDK-8280970) removes some unused code in Provider.java. This is not really functionally needed, but it changes the same areas of code and makes the actual performance fix apply cleanly.
2. [JDK-8324646](https://bugs.openjdk.org/browse/JDK-8324646) is the actual performance fix - avoiding Class.forName calls in every construction.

Note - because of the unused code still present in JDK17, there is actually an alternative fix which makes use of it, which is very simple:

```
diff --git a/src/java.base/share/classes/java/security/Provider.java b/src/java.base/share/classes/java/security/Provider.java
index af8ebeeda57..28bf642d0c8 100644
--- a/src/java.base/share/classes/java/security/Provider.java
+++ b/src/java.base/share/classes/java/security/Provider.java
@@ -1851,7 +1851,7 @@ public abstract class Provider extends Properties {
                         null : constructorParameter.getClass();
                 } else {
                     ctrParamClz = cap.constructorParameterClassName == null?
-                        null : Class.forName(cap.constructorParameterClassName);
+                        null : cap.getConstructorParameterClass(); // actually make use of the cached class!
                     if (constructorParameter != null) {
                         if (ctrParamClz == null) {
                             throw new InvalidParameterException
```

This has the same performance benefits as making the two backports. But, it means 17 will be diverged from later versions, and I think the backported fix is cleaner overall.

Benchmark results (`make test TEST=micro:org.openjdk.bench.java.security.SecureRandomBench`):

```
Before: 2614 ± 127  ns/op
 After: 2150 ± 116  ns/op
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8324646](https://bugs.openjdk.org/browse/JDK-8324646) needs maintainer approval
- [x] [JDK-8280970](https://bugs.openjdk.org/browse/JDK-8280970) needs maintainer approval

### Issues
 * [JDK-8324646](https://bugs.openjdk.org/browse/JDK-8324646): Avoid Class.forName in SecureRandom constructor (**Enhancement** - P4 - Approved)
 * [JDK-8280970](https://bugs.openjdk.org/browse/JDK-8280970): Cleanup dead code in java.security.Provider (**Enhancement** - P5 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2310/head:pull/2310` \
`$ git checkout pull/2310`

Update a local copy of the PR: \
`$ git checkout pull/2310` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2310/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2310`

View PR using the GUI difftool: \
`$ git pr show -t 2310`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2310.diff">https://git.openjdk.org/jdk17u-dev/pull/2310.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2310#issuecomment-2007901043)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Review by shipilev — APPROVED** [review]

**Comment by olivergillespie** [comment]
Waiting for next release to ask approval, since this is similar in nature to https://bugs.openjdk.org/browse/JDK-8324648.

**Comment by olivergillespie** [comment]
/approval 8280970 request Trivial dead code cleanup as a pre-requisite for JDK-8324646. Applies cleanly, no/low risk since it's dead code.

/approval 8324646 request Performance improvement in `SecureRandom.<init>`, which I have seen on the hot path in real applications. Clean backport, low risk in my opinion (simple change to skip Class.forName by using the class literal directly). It has been in tip for several months. Confirmed the benchmark results match tip.

**Comment by olivergillespie** [comment]
Thanks, I wasn't sure which would be easier to review overall, but noted for next time!

**Pull request closed without merging**
