### PR TITLE
8285727: [11u, 17u] Unify fix for JDK-8284920 with version from head

### PR DESCRIPTION
**Pull request by RealCLanger**
The upstream patch for JDK-8284920 differs from the version in jdk17u-dev.
The change in head seems a bit more elegant. Also, the upstream change has a test.
So we should update jdk17u with the version from head.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 reviews required, with at least 1 reviewer)

### Issue
 * [JDK-8285727](https://bugs.openjdk.java.net/browse/JDK-8285727): [11u, 17u] Unify fix for JDK-8284920 with version from head

### Reviewers
 * [Martin Doerr](https://openjdk.java.net/census#mdoerr) (@TheRealMDoerr - **Reviewer**) ⚠️ Review applies to [44cc3be5](https://git.openjdk.java.net/jdk17u-dev/pull/373/files/44cc3be5f648b8dd0292c6dff64d091be4e0258b)
 * [Anton Kozlov](https://openjdk.java.net/census#akozlov) (@AntonKozlov - no project role) ⚠️ Review applies to [44cc3be5](https://git.openjdk.java.net/jdk17u-dev/pull/373/files/44cc3be5f648b8dd0292c6dff64d091be4e0258b)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17u-dev pull/373/head:pull/373` \
`$ git checkout pull/373`

Update a local copy of the PR: \
`$ git checkout pull/373` \
`$ git pull https://git.openjdk.java.net/jdk17u-dev pull/373/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 373`

View PR using the GUI difftool: \
`$ git pr show -t 373`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17u-dev/pull/373.diff">https://git.openjdk.java.net/jdk17u-dev/pull/373.diff</a>

</details>

### CODE REVIEW

**Comment by TheRealMDoerr** [comment]
@AntonKozlov Are you ok with using Oracle's fix instead? LGTM.

**Comment by AntonKozlov** [comment]
Speaking from them code itself, without considering maintainability and possible future merges from the head.

So DOT returns. I think this creates an opportunity for a mistake. IMHO, it's even will be worse, it's will be possible to write `tokenIs(Token.DOT)` instead of `tokenIs(Token.DOT_STR)`, and both will be valid. But the first one peeks a single char and matches both `.` and `..`, the second one -- only `.`. To help to avoid such mistakes, there should be no char token that is in the prefix of a String token, such as DOT and DDOT (and now DOT_STR); COLON and DCOLON. I think making DOT a char is the step back. Instead, I would assume that COLON_CHAR should be renamed back to COLON but made also a String (to fix the last remaining char/String pair of tokens) -- but it is a bit tricky. 

Worth to note the new DOT_STR is not aligned stylistically with the rest of String tokens like DDOT and DCOLON, so I don't feel the new change is elegant, but it is a matter of personal taste.

**Comment by TheRealMDoerr** [comment]
Yeah, I think your version has advantages. Sounds like there should be a cleanup change in jdk master.

**Comment by RealCLanger** [comment]
> Worth to note the new DOT_STR is not aligned stylistically with the rest of String tokens like DDOT and DCOLON, so I don't feel the new change is elegant, but it is a matter of personal taste.

OK, sorry, I shouldn't have used the word "elegant" without really looking at the implementation. What I rather wanted to point out was the fact that Oracle's change was touching less LOC.

I think, after all, we should have the same code in all OpenJDK versions. That's why I would still suggest to do this backport and additionally improve the implementation in OpenJDK head and then backport this enhancement. WDYT?

@AntonKozlov, would you mind proposing your changes in jdk/jdk?

**Review by TheRealMDoerr — APPROVED** [review]
That makes sense. This backport LGTM. Improvement in jdk (and possibly backport) would be appreciated.

**Review by AntonKozlov — APPROVED** [review]
Yes, I think I don't need to block this. I'll take the enhancement in my queue.

**Pull request closed without merging**
