### PR TITLE
8324123: aarch64: fix prfm literal encoding in assembler

### PR DESCRIPTION
**Pull request by mmyxym**
Unclean backport of fixing aarch64 PRFM (literal) encoding.

Additional testing:
 - [x] Linux aarch64 server fastdebug, tier1

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [ ] [JDK-8324123](https://bugs.openjdk.org/browse/JDK-8324123) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8324123](https://bugs.openjdk.org/browse/JDK-8324123): aarch64: fix prfm literal encoding in assembler (**Bug** - P5)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2256/head:pull/2256` \
`$ git checkout pull/2256`

Update a local copy of the PR: \
`$ git checkout pull/2256` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2256/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2256`

View PR using the GUI difftool: \
`$ git pr show -t 2256`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2256.diff">https://git.openjdk.org/jdk17u-dev/pull/2256.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2256#issuecomment-1970601950)

### CODE REVIEW

**Comment by mmyxym** [comment]
Could reviewers please help with the review? The risk is very low as the original wrong encoding is not used in code base. riscv64 build failed because of the risc GHA infra which is also seen in JDK21u.

**Comment by theRealAph** [comment]
> Could reviewers please help with the review? The risk is very low as the original wrong encoding is not used in code base. 

There is, therefore, no reason to backport this. It should not be approved.

**Comment by mmyxym** [comment]
> > Could reviewers please help with the review? The risk is very low as the original wrong encoding is not used in code base.
> 
> There is, therefore, no reason to backport this. It should not be approved.

Hi @theRealAph , I guess we might have enhancements in the future depending on this correct instruction encoding. 17u still accepts enhancements with substantial benefit.

**Comment by theRealAph** [comment]
> > > Could reviewers please help with the review? The risk is very low as the original wrong encoding is not used in code base.
> > 
> > There is, therefore, no reason to backport this. It should not be approved.
> 
> Hi @theRealAph , I guess we might have enhancements in the future depending on this correct instruction encoding. 17u still accepts enhancements with substantial benefit.

... to the users. I guess what you say is possible, and applying this patch now might avoid some future risk. Having said that, if we can speculate about any and every possible future we'd backport an awful lot of stuff, with the risk that implies.

As it stands, this backport is outside the current rules. The maintainers are allowed to make an exception for a special case, though.

**Comment by mmyxym** [comment]
> > > > Could reviewers please help with the review? The risk is very low as the original wrong encoding is not used in code base.
> > > 
> > > 
> > > There is, therefore, no reason to backport this. It should not be approved.
> > 
> > 
> > Hi @theRealAph , I guess we might have enhancements in the future depending on this correct instruction encoding. 17u still accepts enhancements with substantial benefit.
> 
> ... to the users. I guess what you say is possible, and applying this patch now might avoid some future risk. Having said that, if we can speculate about any and every possible future we'd backport an awful lot of stuff, with the risk that implies.
> 
> As it stands, this backport is outside the current rules. The maintainers are allowed to make an exception for a special case, though.

Sure. We can still have a review before maintainer makes the decision. It's not just a normal pre-requisite enhancement which seems unnecessary as you described but an incorrect instruction encoding mistake which really makes compiler engineers nervous. The wrong encoding may not lead to crash but cannot perform the prefetch as expected and very difficult for engineers to find out the root cause.

**Pull request closed without merging**
