### PR TITLE
8297878: KEM: Implementation

### PR DESCRIPTION
**Pull request by wangweij**
This is the backport of the KEM API. The change is identical to https://github.com/openjdk/jdk17u-ri/commit/e9d2641a14407380264b50fa2fe299980fe5f214.

@gnu-andrew, please take a review. Thanks.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8322971](https://bugs.openjdk.org/browse/JDK-8322971) needs maintainer approval
- [x] Commit message must refer to an issue
- [x] [JDK-8297878](https://bugs.openjdk.org/browse/JDK-8297878) needs maintainer approval
- [x] Change requires CSR request [JDK-8330545](https://bugs.openjdk.org/browse/JDK-8330545) to be approved

### Issues
 * [JDK-8297878](https://bugs.openjdk.org/browse/JDK-8297878): KEM: Implementation (**Enhancement** - P3 - Approved)
 * [JDK-8322971](https://bugs.openjdk.org/browse/JDK-8322971): KEM.getInstance() should check if a 3rd-party security provider is signed (**Bug** - P3 - Approved)
 * [JDK-8330545](https://bugs.openjdk.org/browse/JDK-8330545): KEM: Implementation (**CSR**)

### Reviewers
 * [Sean Mullan](https://openjdk.org/census#mullan) (@seanjmullan - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/2518/head:pull/2518` \
`$ git checkout pull/2518`

Update a local copy of the PR: \
`$ git checkout pull/2518` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/2518/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2518`

View PR using the GUI difftool: \
`$ git pr show -t 2518`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/2518.diff">https://git.openjdk.org/jdk17u-dev/pull/2518.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/2518#issuecomment-2144089943)

### CODE REVIEW

**Review by seanjmullan — APPROVED** [review]

**Comment by wangweij** [comment]
/approval request Backporting KEM API to jdk17u-dev which is already integrated injdk17u-ri

**Review by gnu-andrew — APPROVED** [review]
Thanks for porting to jdk17u-dev. I can confirm this matches the patch we reviewed for 17u-ri.

**Comment by wangweij** [comment]
I'll push the change on July 30, which is the first merge for 17.0.13 according to https://wiki.openjdk.org/display/JDKUpdates/JDK+17u.

**Comment by gnu-andrew** [comment]
> I'll push the change on July 30, which is the first merge for 17.0.13 according to https://wiki.openjdk.org/display/JDKUpdates/JDK+17u.

@wangweij there's no need to wait. All the changes for 17.0.12 are isolated in github.com/openjdk/jdk17u. If you wait until the 30th, you might actually miss the promotion of 17.0.13+1.

**Pull request closed without merging**
